//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseState.h"

@class NSArray, NSDictionary, NSString, YTVideoRecorder;

@interface ActionLivenessState : BaseState
{
    struct YTFaceCheckLivePose *faceCheckLivePose;
    struct TC_FaceShape bestImgShape;
    struct Mat eyeImg;
    struct Mat mouthImg;
    struct TC_FaceShape eyeShape;
    struct TC_FaceShape mouthShape;
    vector_837431aa currentFrameList;
    struct Mat currentBestFrame;
    YTVideoRecorder *videoRecorder;
    NSString *videoPath;
    NSString *extraTips;
    _Bool currentActionDoneAndWaitRecordFlag;
    _Bool needLocalConfig;
    _Bool isRecordFinished;
    int codecSettingBitRate;
    int codecSettingiFrameInterval;
    int stableFrameCount;
    int innerWaitFrameCount;
    _Bool isManual;
    int poseType;
    NSString *controlConfig;
    int actReflectMode;
    NSDictionary *innerConfig;
    _Bool _needReflect;
    _Bool _canTransitToReflect;
    _Bool _ActionFinished;
    int _actCurrent;
    int _continuousPassCount;
    NSArray *_actArray;
    unsigned long long _actIndex;
    CDStruct_092ca6c0 *_trackInfo;
    struct YTPOSE *_facePose;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(nonatomic) _Bool ActionFinished; // @synthesize ActionFinished=_ActionFinished;
@property(nonatomic) struct YTPOSE *facePose; // @synthesize facePose=_facePose;
@property(nonatomic) _Bool canTransitToReflect; // @synthesize canTransitToReflect=_canTransitToReflect;
@property(nonatomic) _Bool needReflect; // @synthesize needReflect=_needReflect;
@property(nonatomic) CDStruct_092ca6c0 *trackInfo; // @synthesize trackInfo=_trackInfo;
@property(nonatomic) int continuousPassCount; // @synthesize continuousPassCount=_continuousPassCount;
@property(nonatomic) int actCurrent; // @synthesize actCurrent=_actCurrent;
@property(nonatomic) unsigned long long actIndex; // @synthesize actIndex=_actIndex;
@property(retain, nonatomic) NSArray *actArray; // @synthesize actArray=_actArray;
- (void)resetCountDown;
- (void)handleEvent:(id)arg1;
- (void)resetParam;
- (void)sendStateEvent;
- (void)sendUIEvent;
- (void)resetPoseDetect;
- (_Bool)changeToNextAction;
- (int)poseDetect:(struct TC_FaceShape)arg1 visVec:(vector_7584168e)arg2 poseType:(int)arg3 matRgb:(struct Mat)arg4 pitch:(float)arg5 yaw:(float)arg6 roll:(float)arg7;
- (int)handleActionFinished:(long long)arg1;
- (void)update:(struct Mat)arg1 withTimeStamp:(unsigned long long)arg2;
- (void)reset;
- (void)enter;
- (void)unload;
- (void)loadWithName:(id)arg1 withSDKConfigData:(id)arg2;

@end

