//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface AddBypChat : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int createTime; // @dynamic createTime;
@property(retain, nonatomic) NSString *digestContent; // @dynamic digestContent;
@property(retain, nonatomic) NSString *fromusername; // @dynamic fromusername;
@property(retain, nonatomic) NSString *msgSessionId; // @dynamic msgSessionId;
@property(nonatomic) int msgType; // @dynamic msgType;
@property(nonatomic) unsigned long long newmsgid; // @dynamic newmsgid;
@property(nonatomic) unsigned int seq; // @dynamic seq;
@property(nonatomic) unsigned int unreadCount; // @dynamic unreadCount;

@end

