//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class BaseRequest, NSData, NSString;

@interface BizOcrChatImageRequest : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BaseRequest *baseRequest; // @dynamic baseRequest;
@property(retain, nonatomic) NSString *imageAesKey; // @dynamic imageAesKey;
@property(retain, nonatomic) NSString *imageFileId; // @dynamic imageFileId;
@property(retain, nonatomic) NSString *imageUrl; // @dynamic imageUrl;
@property(retain, nonatomic) NSData *imgData; // @dynamic imgData;
@property(nonatomic) unsigned int seqNum; // @dynamic seqNum;
@property(nonatomic) unsigned long long sessionid64; // @dynamic sessionid64;
@property(nonatomic) unsigned int source; // @dynamic source;

@end

