//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IContactMgrExt.h"
#import "IMMNewSessionMgrExt.h"
#import "IMsgExt.h"
#import "MMImageLoaderObserver.h"
#import "MMKernelExt.h"
#import "MMService.h"
#import "PBMessageObserverDelegate.h"

@class BrandTimelineMsgDB, MMBaseSessionStorage, MemoryMappedKV, NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface BrandTimelineMsgMgr : MMService <IMsgExt, IMMNewSessionMgrExt, IContactMgrExt, MMKernelExt, PBMessageObserverDelegate, MMService, MMImageLoaderObserver>
{
    _Bool _isMigratingData;
    MemoryMappedKV *_mappedKV;
    BrandTimelineMsgDB *_brandMsgDB;
    MMBaseSessionStorage *_sessionStorage;
    NSObject<OS_dispatch_queue> *_m_workerThread;
    NSMutableArray *_arrTmpToAddMsg;
}

@property(retain, nonatomic) NSMutableArray *arrTmpToAddMsg; // @synthesize arrTmpToAddMsg=_arrTmpToAddMsg;
@property(nonatomic) _Bool isMigratingData; // @synthesize isMigratingData=_isMigratingData;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *m_workerThread; // @synthesize m_workerThread=_m_workerThread;
@property(retain, nonatomic) MMBaseSessionStorage *sessionStorage; // @synthesize sessionStorage=_sessionStorage;
@property(retain, nonatomic) BrandTimelineMsgDB *brandMsgDB; // @synthesize brandMsgDB=_brandMsgDB;
@property(retain, nonatomic) MemoryMappedKV *mappedKV; // @synthesize mappedKV=_mappedKV;
- (void).cxx_destruct;
- (void)onDeleteSessionOfUser:(id)arg1;
- (void)handleReadLaterResp:(id)arg1;
- (void)handleFetchItemInfoResp:(id)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)onModifyContact:(id)arg1;
- (void)onDeleteContact:(id)arg1;
- (void)onFinishMigrate;
- (void)OnDelMsg:(id)arg1 DelAll:(_Bool)arg2;
- (void)OnDelMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)OnAddMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)onMsgDBInitFinish;
- (void)laterReadReaderMsg:(id)arg1;
- (void)fetchTimelineMsgItemInfo:(id)arg1;
- (_Bool)isBrandTimelineOpen;
- (void)checkIfNeedHandleMsg;
- (void)checkIfNeedMigrate;
- (void)onServiceClearData;
- (void)onMainControllStart;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)dealloc;
- (void)clearBrandTimelineData;
- (void)migrateBrandSessionAndMsg2Timeline;
- (_Bool)isFinishMigrateBrandMsg;
- (void)setMigrateFinishFlag:(_Bool)arg1;
- (void)OnUnReadCountChange:(id)arg1;
- (void)clearAllNotificationUnreadStatus;
- (_Bool)setNotificationDelFlag:(id)arg1 msgWrap:(id)arg2;
- (void)deleteUnreadNotificationForSession:(id)arg1;
- (_Bool)deleteNotification:(id)arg1;
- (id)getNotificationFromCreateTime:(unsigned int)arg1 limit:(unsigned int)arg2;
- (id)getUnreadNotificationFromCreateTime:(unsigned int)arg1 limit:(unsigned int)arg2;
- (unsigned int)getNotificationUnreadCountByUserName:(id)arg1;
- (unsigned int)getNotificationUnreadCount;
- (id)getLastUnreadNotification;
- (void)handleNewNotification:(id)arg1;
- (void)ImageDidFail:(id)arg1;
- (void)ImageDidLoadWithData:(id)arg1 Url:(id)arg2;
- (void)downloadReaderWrapsCoverImage:(id)arg1;
- (void)preDownLoadCoverImageIfNeed:(id)arg1;
- (void)handleNewMsgByTimeline:(id)arg1;
- (_Bool)isListMsgClearUnread;
- (void)setListMsgClearUnread:(_Bool)arg1;
- (void)setStarContactUnreadStatus:(id)arg1;
- (void)clearStarContactUnreadStatus:(id)arg1;
- (void)clearTimelineUnreadFromSequenceId:(unsigned long long)arg1;
- (unsigned int)getTimelineUnreadMsgCount;
- (unsigned int)getStarUnreadMsgCount;
- (unsigned long long)getDividingLineSequenceId;
- (void)setDividingLineSequenceId:(unsigned long long)arg1;
- (void)setTimelineMsgBrowsed:(id)arg1;
- (void)setTimelineMsgRead:(id)arg1;
- (void)setTimelineMsgWrapExpand:(id)arg1;
- (void)deleteBrandMsg:(id)arg1 msgWrap:(id)arg2;
- (void)deleteBrandSession:(id)arg1;
- (id)getTimelineMsgFromSequenceId:(unsigned long long)arg1 toCreateTime:(unsigned int)arg2 limit:(unsigned int)arg3;
- (id)getTimelineMsgFromSequenceId:(unsigned long long)arg1 toSequenceId:(unsigned long long)arg2 limit:(unsigned int)arg3;
- (id)getTimelineMsgToSequenceId:(unsigned long long)arg1 limit:(unsigned int)arg2;
- (id)getTimelineMsgFromSequenceId:(unsigned long long)arg1 limit:(unsigned int)arg2;
- (id)getNewestTimelineMsg;
- (id)getFirstTimelineMsg;
- (id)getFirstStarMsg;
- (id)getLastMsg;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

