//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface BrandTimelineDBMsg : NSObject <WCTTableCoding>
{
    _Bool isAutoIncrement;
    _Bool _isExpan;
    _Bool _isStarContact;
    _Bool _isBrowsed;
    unsigned int _msgId;
    unsigned int _groupId;
    unsigned int _groupOrderId;
    unsigned int _msgPredict;
    unsigned int _msgLocalId;
    unsigned int _createTime;
    unsigned int _status;
    unsigned int _type;
    unsigned int _msgClusterType;
    long long lastInsertedRowID;
    unsigned long long _sequenceId;
    long long _msgServerId;
    NSString *_message;
    NSString *_msgIdentify;
    NSString *_userName;
    NSString *_msgSource;
}

+ (const struct WCTProperty *)isBrowsed;
+ (const struct WCTProperty *)isStarContact;
+ (const struct WCTProperty *)isExpan;
+ (const struct WCTProperty *)msgSource;
+ (const struct WCTProperty *)userName;
+ (const struct WCTProperty *)msgIdentify;
+ (const struct WCTProperty *)msgClusterType;
+ (const struct WCTProperty *)type;
+ (const struct WCTProperty *)status;
+ (const struct WCTProperty *)message;
+ (const struct WCTProperty *)createTime;
+ (const struct WCTProperty *)msgServerId;
+ (const struct WCTProperty *)msgLocalId;
+ (const struct WCTProperty *)msgPredict;
+ (const struct WCTProperty *)groupOrderId;
+ (const struct WCTProperty *)groupId;
+ (const struct WCTProperty *)sequenceId;
+ (const struct WCTProperty *)msgId;
+ (CDUnknownBlockType)PropertyNamed;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTPropertyList *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
@property(nonatomic) _Bool isBrowsed; // @synthesize isBrowsed=_isBrowsed;
@property(nonatomic) _Bool isStarContact; // @synthesize isStarContact=_isStarContact;
@property(nonatomic) _Bool isExpan; // @synthesize isExpan=_isExpan;
@property(retain, nonatomic) NSString *msgSource; // @synthesize msgSource=_msgSource;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain, nonatomic) NSString *msgIdentify; // @synthesize msgIdentify=_msgIdentify;
@property(nonatomic) unsigned int msgClusterType; // @synthesize msgClusterType=_msgClusterType;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(nonatomic) unsigned int status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(nonatomic) unsigned int createTime; // @synthesize createTime=_createTime;
@property(nonatomic) long long msgServerId; // @synthesize msgServerId=_msgServerId;
@property(nonatomic) unsigned int msgLocalId; // @synthesize msgLocalId=_msgLocalId;
@property(nonatomic) unsigned int msgPredict; // @synthesize msgPredict=_msgPredict;
@property(nonatomic) unsigned int groupOrderId; // @synthesize groupOrderId=_groupOrderId;
@property(nonatomic) unsigned int groupId; // @synthesize groupId=_groupId;
@property(nonatomic) unsigned long long sequenceId; // @synthesize sequenceId=_sequenceId;
@property(nonatomic) unsigned int msgId; // @synthesize msgId=_msgId;
@property(nonatomic) long long lastInsertedRowID; // @synthesize lastInsertedRowID;
@property(nonatomic) _Bool isAutoIncrement; // @synthesize isAutoIncrement;
- (void).cxx_destruct;

@end

