//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@interface BypSyncKey : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned long long bypMsgAvatarKey; // @dynamic bypMsgAvatarKey;
@property(nonatomic) unsigned long long bypMsgFinderKey; // @dynamic bypMsgFinderKey;
@property(nonatomic) unsigned long long bypMsgGameKey; // @dynamic bypMsgGameKey;

@end

