//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CameraScanGoodsMarkDotInfo : NSObject
{
    struct CGPoint _normalizedCenter;
    struct CGSize _normalizedSize;
    struct CGPoint _geometryCenter;
    struct CGSize _geometrySize;
}

@property(nonatomic) struct CGSize geometrySize; // @synthesize geometrySize=_geometrySize;
@property(nonatomic) struct CGPoint geometryCenter; // @synthesize geometryCenter=_geometryCenter;
@property(nonatomic) struct CGSize normalizedSize; // @synthesize normalizedSize=_normalizedSize;
@property(nonatomic) struct CGPoint normalizedCenter; // @synthesize normalizedCenter=_normalizedCenter;

@end

