//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface EditFinderImageAttr : NSObject
{
    _Bool _isFinderFullScreenLogic;
    NSMutableArray *_unCropImagesArray;
    NSString *_fullScreenAttachedHalfScreenVideoUrl;
    struct CGRect _fullScreenRectInScreen;
    struct CGRect _cropRectInScreen;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *fullScreenAttachedHalfScreenVideoUrl; // @synthesize fullScreenAttachedHalfScreenVideoUrl=_fullScreenAttachedHalfScreenVideoUrl;
@property(nonatomic) struct CGRect cropRectInScreen; // @synthesize cropRectInScreen=_cropRectInScreen;
@property(nonatomic) struct CGRect fullScreenRectInScreen; // @synthesize fullScreenRectInScreen=_fullScreenRectInScreen;
@property(retain, nonatomic) NSMutableArray *unCropImagesArray; // @synthesize unCropImagesArray=_unCropImagesArray;
@property(nonatomic) _Bool isFinderFullScreenLogic; // @synthesize isFinderFullScreenLogic=_isFinderFullScreenLogic;
- (id)genEditCropRectWithImageSize:(struct CGSize)arg1;
- (id)init;

@end

