//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FaceRecogPayBaseHandler.h"

#import "FaceRecogRamdomPoseViewDelegate-Protocol.h"

@class FaceRecogRamdomPoseView, NSString;

@interface FaceRecogPayRamdomPoseHandler : FaceRecogPayBaseHandler <FaceRecogRamdomPoseViewDelegate>
{
    FaceRecogRamdomPoseView *_verifyView;
    int _poseMode;
}

- (void).cxx_destruct;
@property(nonatomic) int poseMode; // @synthesize poseMode=_poseMode;
- (void)encodeVideoAsync:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)onStartVerifyResult:(id)arg1;
- (void)onShowUITips:(id)arg1;
- (void)didDetectFace;
- (void)onCameraStart;
- (void)didAccessConfig;
- (void)showView;
- (void)didAccessVideo;
- (void)initView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

