//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

@class UIButton, UIImageView, UILabel, UIView;

@interface FaceRecogPrepareView : MMUIView
{
    UILabel *_waitLabel;
    UIImageView *_loadingBlurView;
    UIImageView *_loadingIndicator;
    UIView *_faceIconBgView;
    UIImageView *_faceIcon;
    UIButton *_closeButton;
    UIButton *_feedbackButton;
}

- (void).cxx_destruct;
- (struct CGRect)getTipIconFrame;
- (void)stopLoading;
- (void)showOKView;
- (void)showFailedTip:(id)arg1;
- (void)showCloseBtn:(id)arg1 target:(id)arg2 sel:(SEL)arg3;
- (void)showFeedBackBtn:(id)arg1 sel:(SEL)arg2;
- (void)startLoadingAnimate;
- (void)showLoadingWithTip:(id)arg1;
- (void)resetView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

