//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSMutableArray;

@interface FinderSnsGetLiveObjectListCtx : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *cacheFriendWatchingId; // @dynamic cacheFriendWatchingId;
@property(nonatomic) unsigned int cacheFriendWatchingIdSrc; // @dynamic cacheFriendWatchingIdSrc;
@property(retain, nonatomic) NSMutableArray *cacheFriendWatchingIdWatchCount; // @dynamic cacheFriendWatchingIdWatchCount;
@property(retain, nonatomic) NSMutableArray *cacheSnsShareId; // @dynamic cacheSnsShareId;
@property(retain, nonatomic) NSMutableArray *cacheSnsShareIdShareCount; // @dynamic cacheSnsShareIdShareCount;
@property(retain, nonatomic) NSMutableArray *cacheSnsShareIdShareFriend; // @dynamic cacheSnsShareIdShareFriend;
@property(retain, nonatomic) NSMutableArray *cacheSnsShareIdShareTime; // @dynamic cacheSnsShareIdShareTime;
@property(nonatomic) unsigned int cacheSnsShareIdSrc; // @dynamic cacheSnsShareIdSrc;
@property(nonatomic) unsigned int lastShareType; // @dynamic lastShareType;
@property(nonatomic) unsigned int pageNum; // @dynamic pageNum;
@property(nonatomic) unsigned long long sessionId; // @dynamic sessionId;

@end

