//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@interface FinderStreamPrefechTimeIntervalConf : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int followNoReddotPrefetchInnerInterval; // @dynamic followNoReddotPrefetchInnerInterval;
@property(nonatomic) unsigned int followNoReddotPrefetchOutterInterval; // @dynamic followNoReddotPrefetchOutterInterval;
@property(nonatomic) unsigned int followReddotPrefetchInnerInterval; // @dynamic followReddotPrefetchInnerInterval;
@property(nonatomic) unsigned int followReddotPrefetchOutterInterval; // @dynamic followReddotPrefetchOutterInterval;
@property(nonatomic) unsigned int friendNoReddotPrefetchInnerInterval; // @dynamic friendNoReddotPrefetchInnerInterval;
@property(nonatomic) unsigned int friendNoReddotPrefetchOutterInterval; // @dynamic friendNoReddotPrefetchOutterInterval;
@property(nonatomic) unsigned int friendReddotPrefetchInnerInterval; // @dynamic friendReddotPrefetchInnerInterval;
@property(nonatomic) unsigned int friendReddotPrefetchOutterInterval; // @dynamic friendReddotPrefetchOutterInterval;
@property(nonatomic) unsigned int hotNoReddotPrefetchInnerInterval; // @dynamic hotNoReddotPrefetchInnerInterval;
@property(nonatomic) unsigned int hotNoReddotPrefetchOutterInterval; // @dynamic hotNoReddotPrefetchOutterInterval;
@property(nonatomic) unsigned int hotReddotPrefetchInnerInterval; // @dynamic hotReddotPrefetchInnerInterval;
@property(nonatomic) unsigned int hotReddotPrefetchOutterInterval; // @dynamic hotReddotPrefetchOutterInterval;
@property(nonatomic) unsigned int nearbyNoReddotPrefetchInnerInterval; // @dynamic nearbyNoReddotPrefetchInnerInterval;
@property(nonatomic) unsigned int nearbyNoReddotPrefetchOutterInterval; // @dynamic nearbyNoReddotPrefetchOutterInterval;
@property(nonatomic) unsigned int nearbyReddotPrefetchInnerInterval; // @dynamic nearbyReddotPrefetchInnerInterval;
@property(nonatomic) unsigned int nearbyReddotPrefetchOutterInterval; // @dynamic nearbyReddotPrefetchOutterInterval;
@property(nonatomic) _Bool tabInnerHotPrefetchSwitch; // @dynamic tabInnerHotPrefetchSwitch;

@end

