//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class FinderAuthInfo, FinderContactExtInfo, FinderContactLiveInfo, FinderContactMsgInfo, FinderLiveNoticeInfo, FinderOriginalInfo, NSString;

@interface FinderContact : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) FinderAuthInfo *authInfo; // @dynamic authInfo;
@property(retain, nonatomic) NSString *coverImgUrl; // @dynamic coverImgUrl;
@property(nonatomic) unsigned int extFlag; // @dynamic extFlag;
@property(retain, nonatomic) FinderContactExtInfo *extInfo; // @dynamic extInfo;
@property(nonatomic) unsigned int fansCount; // @dynamic fansCount;
@property(nonatomic) unsigned int followFlag; // @dynamic followFlag;
@property(nonatomic) unsigned int followTime; // @dynamic followTime;
@property(nonatomic) unsigned int foreignUserFlag; // @dynamic foreignUserFlag;
@property(nonatomic) unsigned int friendFollowCount; // @dynamic friendFollowCount;
@property(retain, nonatomic) NSString *headUrl; // @dynamic headUrl;
@property(retain, nonatomic) NSString *liveCoverImgUrl; // @dynamic liveCoverImgUrl;
@property(retain, nonatomic) FinderContactLiveInfo *liveInfo; // @dynamic liveInfo;
@property(retain, nonatomic) FinderLiveNoticeInfo *liveNoticeInfo; // @dynamic liveNoticeInfo;
@property(nonatomic) unsigned int liveStatus; // @dynamic liveStatus;
@property(retain, nonatomic) NSString *loggingoutWording; // @dynamic loggingoutWording;
@property(retain, nonatomic) FinderContactMsgInfo *msgInfo; // @dynamic msgInfo;
@property(retain, nonatomic) NSString *nickname; // @dynamic nickname;
@property(nonatomic) unsigned int originalEntranceFlag; // @dynamic originalEntranceFlag;
@property(nonatomic) unsigned int originalFlag; // @dynamic originalFlag;
@property(retain, nonatomic) FinderOriginalInfo *originalInfo; // @dynamic originalInfo;
@property(nonatomic) unsigned long long seq; // @dynamic seq;
@property(retain, nonatomic) NSString *signature; // @dynamic signature;
@property(nonatomic) unsigned int spamStatus; // @dynamic spamStatus;
@property(retain, nonatomic) NSString *username; // @dynamic username;

@end

