//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class FinderContact, FinderGetLikedListResponse, FinderStreamResponse, NSMutableArray, NSString;

@interface FinderShakeContactItem : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) FinderGetLikedListResponse *likeResp; // @dynamic likeResp;
@property(retain, nonatomic) FinderContact *shakeContact; // @dynamic shakeContact;
@property(retain, nonatomic) NSMutableArray *shakeObjects; // @dynamic shakeObjects;
@property(retain, nonatomic) NSString *shakeReason; // @dynamic shakeReason;
@property(nonatomic) unsigned int shakeType; // @dynamic shakeType;
@property(retain, nonatomic) FinderStreamResponse *streamResp; // @dynamic streamResp;

@end

