//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUserService.h"

#import "IFunctionMsgExt-Protocol.h"
#import "MMResourceMgrExt-Protocol.h"
#import "MMServiceProtocol-Protocol.h"

@class ExpressMatcher, MMKeywordMather, NSString;

@interface FingertipSearchMgr : MMUserService <MMResourceMgrExt, IFunctionMsgExt, MMServiceProtocol>
{
    _Bool _isBuilding;
    _Bool _isNeedUpdateRealData;
    _Bool _isNeedUpdateStaticData;
    int _keywordCount;
    unsigned int _resourceVersion;
    unsigned int _maxSearchCount;
    MMKeywordMather *_matcher;
    ExpressMatcher *_expressMatcher;
    NSString *_keywordsVersion;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int maxSearchCount; // @synthesize maxSearchCount=_maxSearchCount;
@property(nonatomic) unsigned int resourceVersion; // @synthesize resourceVersion=_resourceVersion;
@property(nonatomic) int keywordCount; // @synthesize keywordCount=_keywordCount;
@property(nonatomic) _Bool isNeedUpdateStaticData; // @synthesize isNeedUpdateStaticData=_isNeedUpdateStaticData;
@property(nonatomic) _Bool isNeedUpdateRealData; // @synthesize isNeedUpdateRealData=_isNeedUpdateRealData;
@property(nonatomic) _Bool isBuilding; // @synthesize isBuilding=_isBuilding;
@property(retain, nonatomic) NSString *keywordsVersion; // @synthesize keywordsVersion=_keywordsVersion;
@property(retain, nonatomic) ExpressMatcher *expressMatcher; // @synthesize expressMatcher=_expressMatcher;
@property(retain, nonatomic) MMKeywordMather *matcher; // @synthesize matcher=_matcher;
- (void)onFunctionMsgResponse:(id)arg1 bussinessId:(unsigned long long)arg2 functionMsgId:(id)arg3;
- (void)onResUpdateFinish:(long long)arg1 resType:(unsigned int)arg2 subResType:(unsigned int)arg3;
- (void)checkMainKeywordResource;
- (int)updateMatherWithWordInfo:(id)arg1 Matcher:(id)arg2;
- (int)addKeywordsWithPath:(id)arg1 Mather:(id)arg2;
- (void)onMatchModelBuidSuccess;
- (void)rebuildMatchModel;
- (void)refreshResourceWithPath:(id)arg1 TargetPath:(id)arg2;
- (long long)getFootprintResidentMemory;
- (id)getRealTimeDataPath;
- (id)getMainKeywordsPath;
- (id)localUsrDirPath;
- (unsigned int)getMatchContentMaxLength;
- (unsigned int)getMatchContentMinLength;
- (id)extractKeywordsWithContent:(id)arg1 version:(id *)arg2;
- (_Bool)containKeywords:(id)arg1;
- (_Bool)isClose;
- (void)dealloc;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

