//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "GameVideoAlbumControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class MMTableView, NSMutableArray, NSString, UINavigationController;

@interface GameCenterMsgListBaseTabViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, GameVideoAlbumControllerDelegate>
{
    _Bool _hasMoreRead;
    unsigned int _showType;
    unsigned int _lastLocalId;
    NSMutableArray *_unreadMsgList;
    long long _sourceScene;
    long long _focusUnreadIndex;
    MMTableView *_tableView;
    NSMutableArray *_readMsgList;
    NSString *_cellReuseIdentifier;
    Class _cellClassType;
    UINavigationController *_startViewController;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UINavigationController *startViewController; // @synthesize startViewController=_startViewController;
@property(nonatomic) _Bool hasMoreRead; // @synthesize hasMoreRead=_hasMoreRead;
@property(nonatomic) unsigned int lastLocalId; // @synthesize lastLocalId=_lastLocalId;
@property(retain, nonatomic) Class cellClassType; // @synthesize cellClassType=_cellClassType;
@property(retain, nonatomic) NSString *cellReuseIdentifier; // @synthesize cellReuseIdentifier=_cellReuseIdentifier;
@property(nonatomic) unsigned int showType; // @synthesize showType=_showType;
@property(retain, nonatomic) NSMutableArray *readMsgList; // @synthesize readMsgList=_readMsgList;
@property(retain, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) long long focusUnreadIndex; // @synthesize focusUnreadIndex=_focusUnreadIndex;
@property(nonatomic) long long sourceScene; // @synthesize sourceScene=_sourceScene;
@property(retain, nonatomic) NSMutableArray *unreadMsgList; // @synthesize unreadMsgList=_unreadMsgList;
- (void)clearAllMsg;
- (id)buildReportObj12909WithArea:(long long)arg1 action:(long long)arg2 position:(unsigned int)arg3 reportType:(unsigned int)arg4 externInfoBuilder:(CDUnknownBlockType)arg5;
- (void)reportMsgExplosure:(unsigned int)arg1 reportType:(unsigned int)arg2 externInfoBuilder:(CDUnknownBlockType)arg3;
- (long long)jumpToWebView:(id)arg1;
- (void)jumpWithJumpInfo:(id)arg1 indexPath:(id)arg2 cellData:(id)arg3;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)handleQuickJump;
- (id)getCellDataForIndexPath:(id)arg1;
- (id)getDataArrayForSection:(long long)arg1;
- (void)loadMoreData;
- (void)tryLoadMoreData;
- (void)showEmptyView;
- (void)setupTableView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

