//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

@class UIButton;

@interface GameLifeTestController : MMUIViewController
{
    UIButton *_getChatSessionIdButton;
    UIButton *_getChatUserInfoButton;
    UIButton *_getBlackListButton;
    UIButton *_setBlackListButton;
    UIButton *_cancelSetBlackListButton;
    UIButton *_getChatSessionDataButton;
    UIButton *_setChatTopButton;
    UIButton *_cancelSetChatTopButton;
    UIButton *_setOffButton;
    UIButton *_cancelSetOffButton;
    UIButton *_sendTextButton;
    UIButton *_enterChat;
}

- (void).cxx_destruct;
- (void)enterChat;
- (void)cancelSetChatOff;
- (void)setChatOff;
- (void)cancelSetChatTop;
- (void)setChatTop;
- (void)getChatSessionData;
- (void)getBlackList;
- (void)cancelSetBlackList;
- (void)setBlackList;
- (void)getChatUserInfo;
- (void)getChatSessionId;
- (void)viewDidLoad;
- (id)init;

@end

