//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JSContextDeallocator : NSObject
{
    _Bool _newGameEngine;
    struct OpaqueContex *_pup_context;
}

@property(nonatomic) _Bool newGameEngine; // @synthesize newGameEngine=_newGameEngine;
@property(nonatomic) struct OpaqueContex *pup_context; // @synthesize pup_context=_pup_context;
- (void)dealloc;

@end

