//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KidsWatchBaseViewController.h"

@class KidsWatchActionCardView, MMUILabel, SightIconView, UIImageView;
@protocol KidsWatchMainViewControllerDelegate;

@interface KidsWatchMainViewController : KidsWatchBaseViewController
{
    MMUILabel *_titleLabel;
    KidsWatchActionCardView *_loginCardView;
    KidsWatchActionCardView *_registerCardView;
    SightIconView *_loadingView;
    UIImageView *_shapeView;
    UIImageView *_bottomBackgroundView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *bottomBackgroundView; // @synthesize bottomBackgroundView=_bottomBackgroundView;
@property(retain, nonatomic) UIImageView *shapeView; // @synthesize shapeView=_shapeView;
@property(retain, nonatomic) SightIconView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) KidsWatchActionCardView *registerCardView; // @synthesize registerCardView=_registerCardView;
@property(retain, nonatomic) KidsWatchActionCardView *loginCardView; // @synthesize loginCardView=_loginCardView;
@property(retain, nonatomic) MMUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)onTapCloseBarButtonItem;
- (void)onTapHelpBarButton;
- (void)onTapRegisterButton;
- (void)onTapLoginButton;
- (void)showMainViewNeedShowRegister:(_Bool)arg1;
- (void)layoutSubviews;
- (void)initSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(nonatomic) __weak id <KidsWatchMainViewControllerDelegate> delegate; // @dynamic delegate;

@end

