//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol LocalJSEventHandlerContextDelegate;

@interface LocalJSEventHandler_BaseEvent : NSObject
{
    NSString *_callbackId;
    id <LocalJSEventHandlerContextDelegate> _context;
    NSString *_cgiIdentifierKey;
    NSString *_requestId;
    LocalJSEventHandler_BaseEvent *_attachEventHandler;
}

- (void).cxx_destruct;
@property(retain, nonatomic) LocalJSEventHandler_BaseEvent *attachEventHandler; // @synthesize attachEventHandler=_attachEventHandler;
@property(copy, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
@property(copy, nonatomic) NSString *cgiIdentifierKey; // @synthesize cgiIdentifierKey=_cgiIdentifierKey;
@property(nonatomic) __weak id <LocalJSEventHandlerContextDelegate> context; // @synthesize context=_context;
@property(copy, nonatomic) NSString *callbackId; // @synthesize callbackId=_callbackId;
- (id)description;
- (id)webViewPluginScheduler;
@property(readonly, copy, nonatomic) NSString *debugModuleName;
- (void)endWithEvent:(id)arg1 result:(id)arg2;
- (void)endWithErrormsg:(id)arg1;
- (void)endWithMessage:(id)arg1;
- (void)endWithParams:(id)arg1;
- (unsigned long long)authorityType;
- (id)JSAPIName;
- (void)handleJSEvent:(id)arg1;
- (void)handleJSEventMain:(id)arg1;
- (void)dealloc;
- (id)init;

@end

