//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUserService.h"

#import "INewEmojiPlayStateExt-Protocol.h"
#import "MEFrameworkLoadDelegate-Protocol.h"
#import "MMServiceProtocol-Protocol.h"

@class MEFramework, MMTableView, NSMutableArray, NSString;
@protocol MEMessageDelegate;

@interface MagicEmojiMgr : MMUserService <INewEmojiPlayStateExt, MEFrameworkLoadDelegate, MMServiceProtocol>
{
    _Bool hasInit;
    _Bool hasInitExpt;
    long long initMagicEmojiType;
    long long benchMarkLevel;
    long long maxRamAlertCount;
    long long maxReloadCount;
    long long refreshReloadTime;
    _Bool destroyOnBack;
    _Bool destroyOnExit;
    long long hasRamAlertNum;
    long long hasReloadNum;
    _Bool hasRamAlertRelease;
    struct timeval ramAlertReleaseTimeval;
    NSMutableArray *msgArray;
    NSString *sessionID;
    _Bool _isViewReady;
    MMTableView *_tableView;
    MEFramework *_meFramework;
    id <MEMessageDelegate> _messageDelegate;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isViewReady; // @synthesize isViewReady=_isViewReady;
@property(nonatomic) __weak id <MEMessageDelegate> messageDelegate; // @synthesize messageDelegate=_messageDelegate;
@property(retain, nonatomic) MEFramework *meFramework; // @synthesize meFramework=_meFramework;
- (void)onWKTerminate;
- (void)onInject:(_Bool)arg1;
- (void)onServiceMemoryWarning;
- (void)onEmojiAnimateStateChange:(unsigned long long)arg1 bindedMsg:(id)arg2;
- (void)onTouchEnded;
- (id)getRuntimeView;
- (void)setupWithDelegate:(id)arg1;
- (void)releaseMEFramework:(unsigned int)arg1;
- (void)clearAllEffect;
@property(readonly, nonatomic) __weak MMTableView *tableView; // @synthesize tableView=_tableView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

