//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData;

@protocol MMConfSDKVideoHWencDelegate <NSObject>
- (int)gotEncodedData:(NSData *)arg1 isKeyFrame:(_Bool)arg2 codecType:(int)arg3 streamID:(int)arg4;
- (int)gotXpsData:(NSData *)arg1 codecType:(int)arg2 streamID:(int)arg3;
@end

