//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MMEasterEggNewYearActivityReportObject : NSObject
{
    unsigned int _videoTimeInMs;
    unsigned int _videoPlayCount;
    unsigned int _loadingTimeInMs;
    unsigned int _videoPlayTotalTimeInMs;
    NSString *_sessionId;
    NSString *_appId;
    NSString *_moneyAccount;
    unsigned long long _enterTimeInMs;
    unsigned long long _videoStartPlayTimeInMs;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int videoPlayTotalTimeInMs; // @synthesize videoPlayTotalTimeInMs=_videoPlayTotalTimeInMs;
@property(nonatomic) unsigned int loadingTimeInMs; // @synthesize loadingTimeInMs=_loadingTimeInMs;
@property(nonatomic) unsigned long long videoStartPlayTimeInMs; // @synthesize videoStartPlayTimeInMs=_videoStartPlayTimeInMs;
@property(nonatomic) unsigned long long enterTimeInMs; // @synthesize enterTimeInMs=_enterTimeInMs;
@property(retain, nonatomic) NSString *moneyAccount; // @synthesize moneyAccount=_moneyAccount;
@property(nonatomic) unsigned int videoPlayCount; // @synthesize videoPlayCount=_videoPlayCount;
@property(nonatomic) unsigned int videoTimeInMs; // @synthesize videoTimeInMs=_videoTimeInMs;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
- (void)reportWithAction:(unsigned long long)arg1;
- (void)closeViewController;
- (void)startPlayVideo;
- (void)showCardView;
- (void)enterViewController;

@end

