//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMLiveTask.h"

@class FinderLiveBadgeInfo, FinderLiveNoticeInfo, FinderLiveQoSInfo, FinderLiveTabInfo, FinderLiveTagInfo, MMFinderLiveAccountInfo, MMFinderLiveContext, MMFinderLiveShopContext, MMLiveTaskId, MMTimer, NSArray, NSMutableArray, NSMutableDictionary, NSString, OrderedDictionary, WCFinderDataItem, WCFinderLiveShareItem;

@interface MMFinderLiveTask : MMLiveTask
{
    _Bool _isEnableComment;
    _Bool _isOnlineStateButtonDisabled;
    _Bool _hasNotifySelfAgree;
    _Bool _hasShopWindowInitiated;
    _Bool _hasOpenedWxaShopProduct;
    _Bool _disableForwardByPrivateAccount;
    _Bool _hasCloseLiveByAnchor;
    _Bool _isAllowRotateInIphone;
    _Bool _lotteryRecordVisible;
    _Bool _isOnlineStateViewShownForAudience;
    _Bool _hasReportedQosInfoAtStop;
    int _currentLiveAliasRoleType;
    unsigned int _startScene;
    unsigned int _userFlag;
    unsigned int _liveGlobalFlag;
    unsigned int _liveStatus;
    unsigned int _finderLiveSourceType;
    int _currVisibilityMode;
    unsigned int _lastCdnQuality;
    int _recentNetType;
    unsigned int _lastReportTimeStamp;
    MMLiveTaskId *_taskId;
    WCFinderDataItem *_finderDataItem;
    WCFinderLiveShareItem *_finderLiveShareItem;
    NSArray *_liveAccountInfoList;
    FinderLiveNoticeInfo *_liveNoticeInfo;
    unsigned long long _commentScene;
    MMFinderLiveContext *_liveContext;
    MMFinderLiveShopContext *_liveShopContext;
    OrderedDictionary *_goodsViewModelOrderedDict;
    NSString *_joinLiveTips;
    long long _lastGiftPage;
    NSArray *_allTagInfos;
    FinderLiveTagInfo *_currentTagInfo;
    FinderLiveBadgeInfo *_currentSelfBadgeInfo;
    FinderLiveTabInfo *_currentTabInfo;
    NSArray *_allVisibilityFileLists;
    NSString *_verifyInfo;
    NSMutableDictionary *_cdnPlayUrlDict;
    NSString *_mCNDPlayUrl;
    FinderLiveQoSInfo *_currentQoSInfo;
    NSMutableArray *_lastQoSInfoList;
    NSMutableArray *_qosInfoListForReport;
    MMTimer *_timer;
}

+ (_Bool)checkFinderDataItemIsValidForLive:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) _Bool hasReportedQosInfoAtStop; // @synthesize hasReportedQosInfoAtStop=_hasReportedQosInfoAtStop;
@property(retain, nonatomic) MMTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) unsigned int lastReportTimeStamp; // @synthesize lastReportTimeStamp=_lastReportTimeStamp;
@property(retain, nonatomic) NSMutableArray *qosInfoListForReport; // @synthesize qosInfoListForReport=_qosInfoListForReport;
@property(nonatomic) int recentNetType; // @synthesize recentNetType=_recentNetType;
@property(retain, nonatomic) NSMutableArray *lastQoSInfoList; // @synthesize lastQoSInfoList=_lastQoSInfoList;
@property(retain, nonatomic) FinderLiveQoSInfo *currentQoSInfo; // @synthesize currentQoSInfo=_currentQoSInfo;
@property(retain, nonatomic) NSString *mCNDPlayUrl; // @synthesize mCNDPlayUrl=_mCNDPlayUrl;
@property(retain, nonatomic) NSMutableDictionary *cdnPlayUrlDict; // @synthesize cdnPlayUrlDict=_cdnPlayUrlDict;
@property(nonatomic) unsigned int lastCdnQuality; // @synthesize lastCdnQuality=_lastCdnQuality;
@property(copy, nonatomic) NSString *verifyInfo; // @synthesize verifyInfo=_verifyInfo;
@property(nonatomic) _Bool isOnlineStateViewShownForAudience; // @synthesize isOnlineStateViewShownForAudience=_isOnlineStateViewShownForAudience;
@property(nonatomic) int currVisibilityMode; // @synthesize currVisibilityMode=_currVisibilityMode;
@property(retain, nonatomic) NSArray *allVisibilityFileLists; // @synthesize allVisibilityFileLists=_allVisibilityFileLists;
@property(retain, nonatomic) FinderLiveTabInfo *currentTabInfo; // @synthesize currentTabInfo=_currentTabInfo;
@property(nonatomic) unsigned int finderLiveSourceType; // @synthesize finderLiveSourceType=_finderLiveSourceType;
@property(retain, nonatomic) FinderLiveBadgeInfo *currentSelfBadgeInfo; // @synthesize currentSelfBadgeInfo=_currentSelfBadgeInfo;
@property(retain, nonatomic) FinderLiveTagInfo *currentTagInfo; // @synthesize currentTagInfo=_currentTagInfo;
@property(retain, nonatomic) NSArray *allTagInfos; // @synthesize allTagInfos=_allTagInfos;
@property(nonatomic) long long lastGiftPage; // @synthesize lastGiftPage=_lastGiftPage;
@property(nonatomic) _Bool lotteryRecordVisible; // @synthesize lotteryRecordVisible=_lotteryRecordVisible;
@property(nonatomic) _Bool isAllowRotateInIphone; // @synthesize isAllowRotateInIphone=_isAllowRotateInIphone;
@property(nonatomic) _Bool hasCloseLiveByAnchor; // @synthesize hasCloseLiveByAnchor=_hasCloseLiveByAnchor;
@property(copy, nonatomic) NSString *joinLiveTips; // @synthesize joinLiveTips=_joinLiveTips;
@property(nonatomic) _Bool disableForwardByPrivateAccount; // @synthesize disableForwardByPrivateAccount=_disableForwardByPrivateAccount;
@property(retain, nonatomic) OrderedDictionary *goodsViewModelOrderedDict; // @synthesize goodsViewModelOrderedDict=_goodsViewModelOrderedDict;
@property(retain, nonatomic) MMFinderLiveShopContext *liveShopContext; // @synthesize liveShopContext=_liveShopContext;
@property(retain, nonatomic) MMFinderLiveContext *liveContext; // @synthesize liveContext=_liveContext;
@property(nonatomic) unsigned int liveStatus; // @synthesize liveStatus=_liveStatus;
@property(nonatomic) _Bool hasOpenedWxaShopProduct; // @synthesize hasOpenedWxaShopProduct=_hasOpenedWxaShopProduct;
@property(nonatomic) _Bool hasShopWindowInitiated; // @synthesize hasShopWindowInitiated=_hasShopWindowInitiated;
@property(nonatomic) _Bool hasNotifySelfAgree; // @synthesize hasNotifySelfAgree=_hasNotifySelfAgree;
@property(nonatomic) unsigned int liveGlobalFlag; // @synthesize liveGlobalFlag=_liveGlobalFlag;
@property(nonatomic) unsigned int userFlag; // @synthesize userFlag=_userFlag;
@property(nonatomic) unsigned long long commentScene; // @synthesize commentScene=_commentScene;
@property(retain, nonatomic) FinderLiveNoticeInfo *liveNoticeInfo; // @synthesize liveNoticeInfo=_liveNoticeInfo;
@property(nonatomic) unsigned int startScene; // @synthesize startScene=_startScene;
@property(retain, nonatomic) NSArray *liveAccountInfoList; // @synthesize liveAccountInfoList=_liveAccountInfoList;
@property(nonatomic) int currentLiveAliasRoleType; // @synthesize currentLiveAliasRoleType=_currentLiveAliasRoleType;
@property(retain, nonatomic) WCFinderLiveShareItem *finderLiveShareItem; // @synthesize finderLiveShareItem=_finderLiveShareItem;
@property(retain, nonatomic) WCFinderDataItem *finderDataItem; // @synthesize finderDataItem=_finderDataItem;
@property(nonatomic) _Bool isEnableComment; // @synthesize isEnableComment=_isEnableComment;
@property(retain, nonatomic) MMLiveTaskId *taskId; // @synthesize taskId=_taskId;
- (id)getQosParamKey:(id)arg1;
- (void)printFinderLiveQoSInfo:(id)arg1;
- (void)doLivePlayReport:(_Bool)arg1;
- (void)onTimerCallback;
- (void)clearReportTimer;
- (void)stopReportTimer;
- (void)startReportTimer;
- (void)updateLiveParamsWithMediaSpec:(id)arg1;
- (id)getCurrentFinderLiveClientStatus;
- (void)onNetStatus:(id)arg1;
- (void)onNetworkQuality:(id)arg1 remoteQuality:(id)arg2;
- (void)onStatistics:(id)arg1;
- (void)setRemoteVideoFrameSize:(struct CGSize)arg1;
- (_Bool)isTrtcAnchor;
- (_Bool)shouldForbidLandScapeForIphone;
- (_Bool)isLiveVideoNeedFill;
- (void)updateMainRemoteViewFrame;
- (id)conflictWording;
- (_Bool)hasResolvedConflictsToTask:(id)arg1;
- (_Bool)judgeExternalConflicts;
- (_Bool)resolveExternalConflicts;
- (_Bool)resolveConflictsWithLiveTask:(id)arg1 navigationController:(id)arg2 maximizeLiveBlock:(CDUnknownBlockType)arg3 switchLiveBlock:(CDUnknownBlockType)arg4;
- (void)stopPreviewCdnPlay;
- (void)startPreviewCdnPlay;
- (id)onMMLiveViewGetAvatarUrl;
- (id)createLiveViewWithFrame:(struct CGRect)arg1 andTaskId:(id)arg2 andDelegate:(id)arg3;
- (void)updateIsEnableComment:(_Bool)arg1;
@property(readonly, nonatomic) _Bool supportSwitchAccount;
@property(readonly, nonatomic) MMFinderLiveAccountInfo *currentLiveAccoutInfo;
- (id)liveShopContextCreateIfNotFound;
- (id)liveContextCreateIfNotFound;
- (_Bool)isOnlineStateButtonDisabled;
- (void)setIsOnlineStateButtonDisabled:(_Bool)arg1;
- (unsigned int)liveStartTime;
- (id)anchorIdentityId;
- (void)updateFinderLiveShareItem:(id)arg1;
- (void)updateFinderDataItem:(id)arg1;
- (_Bool)isLiveClosed;
- (_Bool)isSameToTask:(id)arg1;
- (id)createNewTaskId;
- (long long)trtcRoleTypeFromMMLiveRoleType:(long long)arg1;
- (void)initDefaultData;
- (void)initFaceBeautyParam;
- (unsigned long long)currentLiveScene;
- (_Bool)isFinderLive;
- (void)initFrontCameraMirrorMode;
- (_Bool)canEnableCustomEffect;
- (id)initWithFinderDataItem:(id)arg1;
- (id)initWithFinderContact:(id)arg1;
- (id)initWithFinderUserName:(id)arg1;
- (_Bool)useSmallVideoRectRatioFromLiveView;
@property(copy, nonatomic) NSString *finderUserName; // @dynamic finderUserName;
- (_Bool)isSupportPreviewCdnPlay;
- (_Bool)isShopAssistantSupportPrefetch;
- (_Bool)isLiveShoppingEnabled;
- (_Bool)isShopMiddlePageOptimizationEnabled;
- (_Bool)isShopMiddlePageEnabled;
- (_Bool)isLiveCutByAntispam;
- (_Bool)isLiveConnectMicEnabled;
- (_Bool)isLiveBanComment;
- (_Bool)isLiveEnableReward;
- (_Bool)isLiveShoppingAvailable;
- (void)preloadWeAppForShopProduct:(id)arg1 shouldHotPreload:(_Bool)arg2;
- (void)preloadWeAppForShopProduct:(unsigned long long)arg1 sceneName:(id)arg2 appId:(id)arg3 fullBuyPath:(id)arg4 productExtData:(id)arg5 shouldHotPreload:(_Bool)arg6;
- (void)openWeAppForShopProduct:(unsigned long long)arg1 sceneName:(id)arg2 sceneNote:(id)arg3 appId:(id)arg4 fullBuyPath:(id)arg5 productExtData:(id)arg6 closeBlock:(CDUnknownBlockType)arg7;
- (id)getWeAppPagePathWithPushMode:(id)arg1;

// Remaining properties
@property(nonatomic) unsigned long long frontCameraMirrorMode; // @dynamic frontCameraMirrorMode;
@property(nonatomic) _Bool isFrontCameraMirrored; // @dynamic isFrontCameraMirrored;

@end

