//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMFinderLiveConnectedMicUserCellView.h"

@class UIImageView;

@interface MMFinderLiveConnectedMicAudienceCellView : MMFinderLiveConnectedMicUserCellView
{
    UIImageView *_connectTypeIcon;
}

+ (id)ReuseIdentifier;
- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *connectTypeIcon; // @synthesize connectTypeIcon=_connectTypeIcon;
- (void)layoutUI;
- (void)updateWithConnectMicUser:(id)arg1 searchText:(id)arg2;
- (void)configNickNameLabelWithSearchText:(id)arg1;
- (void)configConnectTypeIcon;
- (void)layoutSubviews;
- (void)prepareForReuse;

@end

