//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MMFinderLiveRewardGiftItem, NSString;

@interface MMFinderLiveGiftNotificationItem : NSObject
{
    _Bool _sentByMe;
    unsigned int _giftCount;
    MMFinderLiveRewardGiftItem *_giftItem;
    NSString *_nickname;
    NSString *_avatarUri;
    NSString *_comboId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *comboId; // @synthesize comboId=_comboId;
@property(nonatomic) _Bool sentByMe; // @synthesize sentByMe=_sentByMe;
@property(nonatomic) unsigned int giftCount; // @synthesize giftCount=_giftCount;
@property(retain, nonatomic) NSString *avatarUri; // @synthesize avatarUri=_avatarUri;
@property(retain, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(retain, nonatomic) MMFinderLiveRewardGiftItem *giftItem; // @synthesize giftItem=_giftItem;
- (id)initWithGiftItem:(id)arg1 nickname:(id)arg2 avatarUri:(id)arg3 giftCount:(unsigned int)arg4 sentByMe:(_Bool)arg5;

@end

