//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMLiveConnectMicLogic.h"

#import "IRecordPermissionCheckExt-Protocol.h"
#import "MMFinderLiveConnectMicOperationPanelDelegate-Protocol.h"
#import "MMFinderLiveConnectMicUserViewDelegate-Protocol.h"
#import "MMFinderLiveConnectMicVideoOperationViewDelegate-Protocol.h"
#import "MMLiveTaskMgrExt-Protocol.h"
#import "MMLiveViewExt-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"

@class MMFinderLiveConnectMicOperationPanel, MMFinderLiveConnectMicUser, MMFinderLiveOperationView, MMFinderLiveTaskId, MMTimer, NSMutableDictionary, NSMutableSet, NSString, OrderedDictionary, UIView, WCLiveActionSheet;
@protocol MMFinderLiveConnectMicActionDelegate;

@interface MMFinderLiveConnectMicLogic : MMLiveConnectMicLogic <MMFinderLiveConnectMicUserViewDelegate, WCActionSheetDelegate, MMFinderLiveConnectMicOperationPanelDelegate, MMFinderLiveConnectMicVideoOperationViewDelegate, MMLiveViewExt, MMLiveTaskMgrExt, IRecordPermissionCheckExt>
{
    _Bool _recordPermissionCheckOK;
    id <MMFinderLiveConnectMicActionDelegate> _actionDelegate;
    MMFinderLiveConnectMicUser *_connectMicUser;
    OrderedDictionary *_applyConnectMicAudienceDic;
    NSMutableSet *_unreadApplyConnectMicAudienceSet;
    OrderedDictionary *_applyConnectMicAnchorDic;
    NSMutableSet *_unreadApplyConnectMicAnchorSet;
    NSMutableDictionary *_allConnectMicAnchorUserIdToRoomId;
    unsigned long long _currentCdnVideoDisplayType;
    unsigned long long _maxConnectMicAudienceSequence;
    WCLiveActionSheet *_applyConnectMicActionSheet;
    WCLiveActionSheet *_cancelOrStopConnectMicActionSheet;
    MMTimer *_activateLiveConnectMicTimer;
    NSMutableDictionary *_closeInfoDic;
    MMFinderLiveConnectMicOperationPanel *_connectMicOperationPanel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMFinderLiveConnectMicOperationPanel *connectMicOperationPanel; // @synthesize connectMicOperationPanel=_connectMicOperationPanel;
@property(retain, nonatomic) NSMutableDictionary *closeInfoDic; // @synthesize closeInfoDic=_closeInfoDic;
@property(retain, nonatomic) MMTimer *activateLiveConnectMicTimer; // @synthesize activateLiveConnectMicTimer=_activateLiveConnectMicTimer;
@property(retain, nonatomic) WCLiveActionSheet *cancelOrStopConnectMicActionSheet; // @synthesize cancelOrStopConnectMicActionSheet=_cancelOrStopConnectMicActionSheet;
@property(retain, nonatomic) WCLiveActionSheet *applyConnectMicActionSheet; // @synthesize applyConnectMicActionSheet=_applyConnectMicActionSheet;
@property(nonatomic) unsigned long long maxConnectMicAudienceSequence; // @synthesize maxConnectMicAudienceSequence=_maxConnectMicAudienceSequence;
@property(nonatomic) _Bool recordPermissionCheckOK; // @synthesize recordPermissionCheckOK=_recordPermissionCheckOK;
@property(nonatomic) unsigned long long currentCdnVideoDisplayType; // @synthesize currentCdnVideoDisplayType=_currentCdnVideoDisplayType;
@property(retain, nonatomic) NSMutableDictionary *allConnectMicAnchorUserIdToRoomId; // @synthesize allConnectMicAnchorUserIdToRoomId=_allConnectMicAnchorUserIdToRoomId;
@property(retain, nonatomic) NSMutableSet *unreadApplyConnectMicAnchorSet; // @synthesize unreadApplyConnectMicAnchorSet=_unreadApplyConnectMicAnchorSet;
@property(retain, nonatomic) OrderedDictionary *applyConnectMicAnchorDic; // @synthesize applyConnectMicAnchorDic=_applyConnectMicAnchorDic;
@property(retain, nonatomic) NSMutableSet *unreadApplyConnectMicAudienceSet; // @synthesize unreadApplyConnectMicAudienceSet=_unreadApplyConnectMicAudienceSet;
@property(retain, nonatomic) OrderedDictionary *applyConnectMicAudienceDic; // @synthesize applyConnectMicAudienceDic=_applyConnectMicAudienceDic;
@property(retain, nonatomic) MMFinderLiveConnectMicUser *connectMicUser; // @synthesize connectMicUser=_connectMicUser;
@property(nonatomic) __weak id <MMFinderLiveConnectMicActionDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
- (void)OnRecordDenied;
- (void)OnRecordPermissioned;
- (void)onExtendFromCollapseAnimationDidEndWithLiveTask:(id)arg1;
- (void)onLiveView:(id)arg1 videoViewAppearanceChanged:(_Bool)arg2;
- (void)onLiveViewMainVideoViewFrameChanged:(id)arg1 newVideoViewFrame:(struct CGRect)arg2;
- (void)onMMFinderLiveConnectMicVideoOperationViewTapAvatar;
- (void)onMMFinderLiveConnectMicVideoOperationViewSwitchCamera;
- (void)onMMFinderLiveConnectMicVideoOperationViewTapHangup;
- (void)handleAcceptLiveMicResult:(_Bool)arg1 error:(id)arg2 sessionId:(id)arg3 userInfo:(id)arg4;
- (void)onMMFinderLiveConnectMicOperationPanelApplyConnectToUser:(id)arg1;
- (void)realAcceptConnectMicWithUser:(id)arg1;
- (void)onMMFinderLiveConnectMicOperationPanelAcceptConnectFromUser:(id)arg1;
- (id)onMMFinderLiveConnectMicOperationPanelGetConnectMicUserListWithType:(unsigned long long)arg1;
- (_Bool)onMMFinderLiveConnectMicOperationPanelShouldShowRedDotAtTab:(unsigned long long)arg1;
- (void)onMMFinderLiveConnectMicOperationPanelClose;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onMMFinderLiveConnectMicUserViewTapped;
- (void)onMMFinderLiveConnectMicUserViewTapHangup;
- (void)onMMFinderLiveConnectMicUserViewMoveEnd;
@property(readonly, nonatomic) _Bool isConnectingMic;
@property(readonly, nonatomic) UIView *containerView;
- (id)getFinderLiveTask;
@property(readonly, nonatomic) MMFinderLiveOperationView *finderLiveOperationView;
@property(readonly, nonatomic) MMFinderLiveTaskId *finderLiveTaskId;
- (void)delayStopConnectMicWithSessionId:(id)arg1;
- (void)activateLiveConnectMic;
- (void)stopActivateLiveConnectMicTimer;
- (void)startActivateLiveConnectMicTimer;
- (void)updateCloseInfoDicWithSessionId:(id)arg1 connectMicUserInfo:(id)arg2 shouldResetCount:(_Bool)arg3 shouldRemove:(_Bool)arg4;
- (void)sendCloseConnectMicCgiWithConnectMicUser:(id)arg1 andCloseScene:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)sendCloseConnectMicCgiWithConnectMicUser:(id)arg1 andCloseScene:(long long)arg2;
- (void)sendCloseConnectMicCgiWithCloseScene:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)sendCloseConnectMicCgiWithCloseScene:(long long)arg1;
- (void)checkAndNotifyConnectMicEnd;
- (void)notifyConnectMic;
- (void)updateConnectMicButtonBadge;
- (void)clearApplyConnectMicUserList;
- (void)checkAndDismissAllActionSheet;
- (void)realStopConnectMicWithTask:(id)arg1;
- (void)stopConnectMicWithConnectMicUser:(id)arg1 andCloseScene:(long long)arg2;
- (void)stopConnectMicWithCloseScene:(long long)arg1;
- (void)checkAndStopConnectMic;
- (void)checkConnectingMicTimeOutForAnchor;
- (void)cancelConnectMicWithToast:(_Bool)arg1 isTimeOut:(_Bool)arg2;
- (void)checkAndCancelConnectMic;
- (id)applyConnectMicFailedToastMsgForErrorCode:(long long)arg1;
- (_Bool)isApplyConnectMicFailedToastErrorCode:(long long)arg1;
- (void)handleApplyLiveMicResult:(_Bool)arg1 error:(id)arg2 sessionId:(id)arg3 userInfo:(id)arg4;
- (void)startApplyConnectMicWithVideo:(_Bool)arg1;
- (void)showCancelApplyOrStopConnectActionSheet;
- (_Bool)tryStopConnectMicWithCloseScene:(long long)arg1;
- (_Bool)tryStopConnectMic;
- (void)connectMicAction;
- (void)switchCamera;
- (void)changeAndUpdateConnectMicButtonStateHighlighted;
- (void)clearConnectMicUserInfoWithToast:(_Bool)arg1;
- (void)clearConnectMicUserInfo;
- (void)handleConnectToOtherRoomResult:(_Bool)arg1 userId:(id)arg2 errCode:(int)arg3 errMsg:(id)arg4;
- (void)handleRemoteUserEnterRoomWithSdkUserId:(id)arg1;
- (void)handleUser:(id)arg1 videoAvailable:(_Bool)arg2;
- (void)handleUser:(id)arg1 audioAvailable:(_Bool)arg2;
- (void)onTrtcSwitchRoleError:(int)arg1 errMsg:(id)arg2;
- (void)onTrtcSwitchRoleFinished;
- (void)notifyCanApplyConnectMicValueChanged:(_Bool)arg1;
- (void)checkAndShowConnectMicVideoOperationView;
- (void)showConnectMicUserViewWithState:(unsigned long long)arg1;
- (void)updateCanApplyConnectMic:(_Bool)arg1 fromJoinLive:(_Bool)arg2;
- (void)enableApplyConnectMic:(_Bool)arg1;
- (void)checkConnectMicUserInfoAndVideoSizeForCdnAudience;
- (void)receiveAnchorConnectMicStatus:(long long)arg1 connectMicFinderContact:(id)arg2 sessionId:(id)arg3 sequence:(unsigned long long)arg4 sdkUserId:(id)arg5 fromJoinLive:(_Bool)arg6;
- (void)receiveAnchorCloseConnectMicFromContact:(id)arg1 sessionId:(id)arg2;
- (void)receiveAnchorAcceptConnectMicFromContact:(id)arg1 sdkUserId:(id)arg2 sdkRoomId:(unsigned int)arg3 sdkPkSign:(id)arg4 sessionId:(id)arg5 sequence:(unsigned long long)arg6;
- (void)receiveAnchorApplyConnectMicFromContact:(id)arg1 sdkUserId:(id)arg2 sdkRoomId:(unsigned int)arg3 sessionId:(id)arg4;
- (void)receiveConnectMicUserForAudience:(id)arg1;
- (void)receiveSelfConnectMicUserInfo:(id)arg1 fromJoinLive:(_Bool)arg2;
- (void)receiveConnectMicUserForAnchor:(id)arg1 expiredTime:(unsigned long long)arg2 fromJoinLive:(_Bool)arg3;
- (void)receiveConnectMicFinderContact:(id)arg1 withVideo:(_Bool)arg2 sdkUserId:(id)arg3 expiredTime:(unsigned long long)arg4 sessionId:(id)arg5 sequence:(unsigned long long)arg6 fromJoinLive:(_Bool)arg7;
- (void)receiveConnectMicLiveSdkInfo:(id)arg1 expiredTime:(unsigned long long)arg2 sessionId:(id)arg3 sequence:(unsigned long long)arg4;
- (void)receiveApplyConnectMicFromContact:(id)arg1 sdkUserId:(id)arg2 sessionId:(id)arg3 andUseVideo:(_Bool)arg4;
- (void)receiveCloseConnectMicMsgForAudienceWithSessionId:(id)arg1;
- (void)receiveCloseConnectMicMsgWithContact:(id)arg1 sessionId:(id)arg2;
- (void)dealloc;
- (id)initWithTaskId:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

