//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MMFinderLiveGiftNotificationItem, NSString;

@interface MMFinderLiveGiftSendingComboItem : NSObject
{
    _Bool _isBatchFinished;
    NSString *_comboId;
    MMFinderLiveGiftNotificationItem *_notificationItem;
    long long _displayingSeconds;
}

- (void).cxx_destruct;
@property(nonatomic) long long displayingSeconds; // @synthesize displayingSeconds=_displayingSeconds;
@property(nonatomic) _Bool isBatchFinished; // @synthesize isBatchFinished=_isBatchFinished;
@property(retain, nonatomic) MMFinderLiveGiftNotificationItem *notificationItem; // @synthesize notificationItem=_notificationItem;
@property(retain, nonatomic) NSString *comboId; // @synthesize comboId=_comboId;

@end

