//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMMultiMenuTableViewCell.h"

@class CAShapeLayer, MMFinderLiveGoodsViewModel, MMLiveRichTextLabel, MMUIButton, MMUILabel, MMWebImageView, UIImageView, UIView;
@protocol MMFinderLiveGoodsCellDelegate;

@interface MMFinderLiveGoodsCell : MMMultiMenuTableViewCell
{
    id <MMFinderLiveGoodsCellDelegate> _cellDelegate;
    MMUILabel *_serialNumLabel;
    MMLiveRichTextLabel *_goodsTitleLabel;
    MMUILabel *_stockLabel;
    MMUILabel *_priceLabel;
    MMWebImageView *_goodsImageView;
    MMUIButton *_actionButton;
    CAShapeLayer *_shapeLayer;
    MMFinderLiveGoodsViewModel *_goodsViewModel;
    UIView *_gradientShawdowView;
    UIImageView *_promotingIconView;
    MMUILabel *_promotingLabel;
}

+ (id)buildAttributedStringWithTitle:(id)arg1 platformIcon:(id)arg2;
+ (id)getPlatformIconPaddingImage;
+ (double)getCellSeperatorXOffset;
+ (double)getCellHeight;
+ (double)getFirstCellHeight;
+ (id)identifier;
- (void).cxx_destruct;
@property(retain, nonatomic) MMUILabel *promotingLabel; // @synthesize promotingLabel=_promotingLabel;
@property(retain, nonatomic) UIImageView *promotingIconView; // @synthesize promotingIconView=_promotingIconView;
@property(retain, nonatomic) UIView *gradientShawdowView; // @synthesize gradientShawdowView=_gradientShawdowView;
@property(retain, nonatomic) MMFinderLiveGoodsViewModel *goodsViewModel; // @synthesize goodsViewModel=_goodsViewModel;
@property(retain, nonatomic) CAShapeLayer *shapeLayer; // @synthesize shapeLayer=_shapeLayer;
@property(retain, nonatomic) MMUIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) MMWebImageView *goodsImageView; // @synthesize goodsImageView=_goodsImageView;
@property(retain, nonatomic) MMUILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(retain, nonatomic) MMUILabel *stockLabel; // @synthesize stockLabel=_stockLabel;
@property(retain, nonatomic) MMLiveRichTextLabel *goodsTitleLabel; // @synthesize goodsTitleLabel=_goodsTitleLabel;
@property(retain, nonatomic) MMUILabel *serialNumLabel; // @synthesize serialNumLabel=_serialNumLabel;
@property(nonatomic) __weak id <MMFinderLiveGoodsCellDelegate> cellDelegate; // @synthesize cellDelegate=_cellDelegate;
- (void)updateWithGoodsViewModel:(id)arg1;
- (void)layoutUI;
- (void)layoutSubviews;
- (void)createActionButton;
- (void)initViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

