//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMLiveViewController.h"

#import "MMFinderLiveInfluencerMarketingViewDelegate-Protocol.h"
#import "MMFinderLiveLogicDelegate-Protocol.h"
#import "MMFinderLiveOperationViewDelegate-Protocol.h"
#import "MMLiveCompleteViewControllerDelegate-Protocol.h"
#import "MMLiveFaceVerifyViewControllerDelegate-Protocol.h"
#import "MMLiveFullScreenTipsViewDelegate-Protocol.h"
#import "MMLiveStarterViewControllerDelegate-Protocol.h"
#import "MMScrollActionSheetDelegate-Protocol.h"
#import "MMUIViewControllerExt-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"
#import "WCFinderLiveExt-Protocol.h"
#import "WCFinderLiveHalfScreenUtilControllerDelegate-Protocol.h"
#import "WCFinderLiveStarterViewControllerDelegate-Protocol.h"

@class FinderLiveShopWindowProductItem, MMFinderLiveGoodsItem, MMFinderLiveInfluencerMarketingView, MMFinderLiveOnlineUserProfileView, MMFinderLiveOperationView, MMFinderLiveShopContext, MMFinderLiveTask, MMLiveFullScreenTipsView, NSDictionary, NSString, WCFinderDataItem, WCFinderFeedContentVM, WCFinderLiveBaseLogReporter, WCFinderLiveCompleteViewController, WCFinderLiveHalfScreenUtilController, WCLiveScrollActionSheet;

@interface MMFinderLiveViewController : MMLiveViewController <MMFinderLiveLogicDelegate, WCFinderLiveStarterViewControllerDelegate, MMLiveStarterViewControllerDelegate, MMLiveCompleteViewControllerDelegate, MMScrollActionSheetDelegate, WCActionSheetDelegate, MMFinderLiveInfluencerMarketingViewDelegate, WCFinderLiveExt, MMUIViewControllerExt, MMLiveFullScreenTipsViewDelegate, MMFinderLiveOperationViewDelegate, WCFinderLiveHalfScreenUtilControllerDelegate, MMLiveFaceVerifyViewControllerDelegate>
{
    _Bool _hasOpenedWeAppInFullScreen;
    _Bool _shouldCloseSheetModeWeApp;
    _Bool _canShowPoorNetworkTip;
    _Bool _isShowCompleteViewController;
    _Bool _shouldUpdateTRTCCloudMixtureParams;
    _Bool _isFinderLiveIdentityChangedInMinimizeMode;
    unsigned int _lastPoorNetworkTipTime;
    unsigned int _lastLiveExtFlag;
    int _localPoorNetworkCount;
    int _lastSelectLiveAliasRole;
    WCFinderLiveCompleteViewController *_completeViewController;
    NSString *_finderUserName;
    WCFinderDataItem *_dataItem;
    MMFinderLiveOnlineUserProfileView *_profileView;
    MMFinderLiveInfluencerMarketingView *_marketingView;
    WCFinderFeedContentVM *_contentVM;
    MMLiveFullScreenTipsView *_kickedOutTipsView;
    MMLiveFullScreenTipsView *_privateJoinBlockView;
    WCFinderLiveHalfScreenUtilController *_verifyAndPolicyView;
    NSString *_weAppIdInFullScreen;
    WCFinderLiveBaseLogReporter *_reporter;
    WCLiveScrollActionSheet *_settingScrollActionSheet;
    NSString *_lastFromVC;
    long long _currentMarketActionType;
    MMFinderLiveGoodsItem *_currentHandleGoodsItem;
    MMFinderLiveShopContext *_currentHandleShopContext;
    FinderLiveShopWindowProductItem *_currentAudienceProductItem;
    long long _currentComplainEntrance;
    NSDictionary *_currentComplainExtraData;
    NSDictionary *_currentComplainExtraQuery;
    long long _currentUserActionType;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isFinderLiveIdentityChangedInMinimizeMode; // @synthesize isFinderLiveIdentityChangedInMinimizeMode=_isFinderLiveIdentityChangedInMinimizeMode;
@property(nonatomic) _Bool shouldUpdateTRTCCloudMixtureParams; // @synthesize shouldUpdateTRTCCloudMixtureParams=_shouldUpdateTRTCCloudMixtureParams;
@property(nonatomic) long long currentUserActionType; // @synthesize currentUserActionType=_currentUserActionType;
@property(retain, nonatomic) NSDictionary *currentComplainExtraQuery; // @synthesize currentComplainExtraQuery=_currentComplainExtraQuery;
@property(retain, nonatomic) NSDictionary *currentComplainExtraData; // @synthesize currentComplainExtraData=_currentComplainExtraData;
@property(nonatomic) long long currentComplainEntrance; // @synthesize currentComplainEntrance=_currentComplainEntrance;
@property(nonatomic) _Bool isShowCompleteViewController; // @synthesize isShowCompleteViewController=_isShowCompleteViewController;
@property(retain, nonatomic) FinderLiveShopWindowProductItem *currentAudienceProductItem; // @synthesize currentAudienceProductItem=_currentAudienceProductItem;
@property(retain, nonatomic) MMFinderLiveShopContext *currentHandleShopContext; // @synthesize currentHandleShopContext=_currentHandleShopContext;
@property(retain, nonatomic) MMFinderLiveGoodsItem *currentHandleGoodsItem; // @synthesize currentHandleGoodsItem=_currentHandleGoodsItem;
@property(nonatomic) long long currentMarketActionType; // @synthesize currentMarketActionType=_currentMarketActionType;
@property(retain, nonatomic) NSString *lastFromVC; // @synthesize lastFromVC=_lastFromVC;
@property(nonatomic) int lastSelectLiveAliasRole; // @synthesize lastSelectLiveAliasRole=_lastSelectLiveAliasRole;
@property(nonatomic) int localPoorNetworkCount; // @synthesize localPoorNetworkCount=_localPoorNetworkCount;
@property(nonatomic) _Bool canShowPoorNetworkTip; // @synthesize canShowPoorNetworkTip=_canShowPoorNetworkTip;
@property(nonatomic) unsigned int lastLiveExtFlag; // @synthesize lastLiveExtFlag=_lastLiveExtFlag;
@property(nonatomic) unsigned int lastPoorNetworkTipTime; // @synthesize lastPoorNetworkTipTime=_lastPoorNetworkTipTime;
@property(retain, nonatomic) WCLiveScrollActionSheet *settingScrollActionSheet; // @synthesize settingScrollActionSheet=_settingScrollActionSheet;
@property(retain, nonatomic) WCFinderLiveBaseLogReporter *reporter; // @synthesize reporter=_reporter;
@property(retain, nonatomic) NSString *weAppIdInFullScreen; // @synthesize weAppIdInFullScreen=_weAppIdInFullScreen;
@property(nonatomic) _Bool shouldCloseSheetModeWeApp; // @synthesize shouldCloseSheetModeWeApp=_shouldCloseSheetModeWeApp;
@property(nonatomic) _Bool hasOpenedWeAppInFullScreen; // @synthesize hasOpenedWeAppInFullScreen=_hasOpenedWeAppInFullScreen;
@property(retain, nonatomic) WCFinderLiveHalfScreenUtilController *verifyAndPolicyView; // @synthesize verifyAndPolicyView=_verifyAndPolicyView;
@property(retain, nonatomic) MMLiveFullScreenTipsView *privateJoinBlockView; // @synthesize privateJoinBlockView=_privateJoinBlockView;
@property(retain, nonatomic) MMLiveFullScreenTipsView *kickedOutTipsView; // @synthesize kickedOutTipsView=_kickedOutTipsView;
@property(retain, nonatomic) WCFinderFeedContentVM *contentVM; // @synthesize contentVM=_contentVM;
@property(retain, nonatomic) MMFinderLiveInfluencerMarketingView *marketingView; // @synthesize marketingView=_marketingView;
@property(retain, nonatomic) MMFinderLiveOnlineUserProfileView *profileView; // @synthesize profileView=_profileView;
@property(retain, nonatomic) WCFinderDataItem *dataItem; // @synthesize dataItem=_dataItem;
@property(readonly, nonatomic) NSString *finderUserName; // @synthesize finderUserName=_finderUserName;
@property(retain, nonatomic) WCFinderLiveCompleteViewController *completeViewController; // @synthesize completeViewController=_completeViewController;
- (void)exitAndClearLive;
- (id)toAudienceReporter;
- (id)toAnchorReporter;
- (void)handleUIOrientationChanged:(id)arg1;
- (void)clearGoToTrumpetSelectActionState;
- (void)clearGoToSingleLiveLotteryRecordActionState;
- (void)clearGoToLotteryWinRecordActionState;
- (void)clearShareToTextStateActionState;
- (void)clearShareToMomentActionState;
- (void)clearShareToFriendActionState;
- (void)clearCurrentUserActionState;
- (void)checkCurrentUserActionState;
- (_Bool)invokeExposeComplain;
- (void)clearComplaintEntryComplainState;
- (void)clearFansProfileComplainState;
- (void)clearCommentActionSheetComplainState;
- (void)clearCurrentComplainState;
- (void)checkCurrentComplainState;
- (void)clearShowCompleteState;
- (void)clearCompleteViewController;
- (void)clearGoodsOrderClickState;
- (void)clearGoodsItemSelectedState;
- (void)clearPurchaseState;
- (void)clearGoodsPubbleClickState;
- (void)clearMarketActionState;
- (void)checkCurrentMarketActionState;
- (void)invokeHandlerAfterPortrait;
- (void)clearAllStateAfterPortrait;
- (void)updateCurrOrientation;
- (void)onWCFinderLiveHalfScreenConfirmButtonClicked:(long long)arg1;
- (void)MMUIViewControllerDidDisappear:(id)arg1;
- (void)MMUIViewControllerWillDisppear:(id)arg1;
- (void)MMUIViewControllerWillAppear:(id)arg1;
- (void)MMUIViewControllerDidAppear:(id)arg1;
- (void)onShowConnectedMicUserProfileWithContact:(id)arg1;
- (void)onShowLiveHalfScreenViewFromScene:(long long)arg1;
- (void)onExtendFromCollapseAnimationDidEndWithLiveTask:(id)arg1;
- (void)onLiveTask:(id)arg1 networkLocalQuality:(id)arg2 remoteQuality:(id)arg3;
- (void)onLiveTask:(id)arg1 enterLiveRoom:(id)arg2;
- (void)onLiveTask:(id)arg1 exitLiveRoom:(long long)arg2 error:(id)arg3;
- (void)onMMLiveStarterViewControllerAddGoods;
- (void)onGetFinderLiveMessage:(id)arg1 taskId:(id)arg2 onlineContacts:(id)arg3 msgList:(id)arg4 finderLiveInfo:(id)arg5 onlineCount:(unsigned int)arg6 liveInfoEnable:(_Bool)arg7 liveClosed:(_Bool)arg8 liveExtFlag:(unsigned int)arg9 onlineViewCount:(unsigned int)arg10;
- (void)onGetFinderContact:(id)arg1 contact:(id)arg2;
- (void)onGetFinderLiveBanComment:(id)arg1 enableComment:(_Bool)arg2 forUserName:(id)arg3;
- (void)finderLiveIdentityChange;
@property(readonly, nonatomic) _Bool hasOpenedWeAppInHalfScreen;
- (id)finderLiveLogic;
@property(readonly, nonatomic) MMFinderLiveOperationView *finderOperationView;
- (void)switchLiveAliasRoleTypeIfIdentityChanged;
- (void)gotoChatViewVCWithContact:(id)arg1;
- (void)trySharingToTextStateWithBlock:(CDUnknownBlockType)arg1;
- (void)trySharingWithBlock:(CDUnknownBlockType)arg1;
- (void)showPrivateJoinBlockView;
- (void)onShowForbidLiveViewWithError:(id)arg1;
- (void)onShowErrorPage:(id)arg1;
- (void)onKickedOut;
- (void)banOrOpenReward:(_Bool)arg1;
- (void)banOrOpenComment:(_Bool)arg1;
- (void)complaintEntry;
- (id)createOperationViewWithTaskId:(id)arg1;
- (void)setupProfileActionCallback:(id)arg1 isCommentEnable:(_Bool)arg2 openProfileScene:(long long)arg3;
- (void)showFansProfileViewWithContact:(id)arg1 isCommentEnable:(_Bool)arg2;
- (void)showProfileView:(id)arg1 isCommentEnable:(_Bool)arg2 extraInfo:(id)arg3;
- (_Bool)invokeHandleForGoodsItemSelected;
- (void)onMMFinderLiveGoodsItemSelected:(id)arg1 shopContext:(id)arg2;
- (_Bool)invokeGoodsOrderButtonClicked;
- (void)onMMFinderLiveGoodsOrderButtonClicked:(id)arg1;
- (void)onMMFinderLiveAddGoodsButtonClicked:(id)arg1;
- (void)onMMFinderLivePromoteStatusChanged:(id)arg1 promoteStatus:(_Bool)arg2;
- (_Bool)goToShopBusinessPage;
- (void)onMMFinderLivePurchaseButtonClicked:(id)arg1 shopContext:(id)arg2;
- (void)scrollActionSheet:(id)arg1 didSelecteItem:(id)arg2;
- (_Bool)invokeGotoTrumpetSelectViewController;
- (void)gotoTrumpetSelectViewController;
- (_Bool)invokeGotoSingleLiveLotteryRecordViewController;
- (void)gotoSingleLiveLotteryRecordViewController;
- (_Bool)invokeGoToLotteryWinRecordViewController;
- (void)gotoLotteryWinRecordViewController;
- (_Bool)invokeShareToTextState;
- (void)shareToTextState;
- (_Bool)invokeShareToMoment;
- (void)shareToMoment;
- (_Bool)invokeShareToFriend;
- (void)shareToFriend;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (_Bool)shouldSupportLiveSwitchingWithGestureRecognizer:(id)arg1;
- (_Bool)shouldInvokeInteractiveTransition;
- (_Bool)shouldSupportInteractiveTransition;
- (void)onMMLiveOperationFindMoreLive;
- (void)checkAndCloseHalfScreenView;
- (void)onMMLiveOperationSelectAccount:(id)arg1;
- (void)onMMLiveOperationCreateLotteryBtnClicked;
- (_Bool)showHalfScreenShopBusinessPageForAudience;
- (void)onMMLiveOperationLiveGoodsTipViewClickedForAudience:(id)arg1;
- (void)onMMLiveOperationOpenRewardInstructionPage;
- (void)onMMLiveOperationLiveShoppingButtonClicked:(id)arg1;
- (void)onMMLiveOperationInviteFriendsBtnClicked;
- (void)onMMLiveOperationUserHeadImageClicked:(id)arg1 userInfo:(id)arg2;
- (void)onMMLiveOrientationButtonClicked;
- (void)onMMLiveActionButtonClicked;
- (void)onOperationPermissionChanged;
- (void)onShowToastFromAppMsg:(id)arg1;
- (void)onShowAlertFromAppMsg:(id)arg1;
- (void)onFinderDataItemUpdated;
- (void)onLiveClosed:(id)arg1;
- (void)onJoinLive:(id)arg1;
- (void)checkAndResumeLive;
- (void)reloadDataForMarketingView;
- (void)closeWithoutNavigation;
- (void)closeDirectly;
- (void)close;
- (id)onlineUserLogic;
- (void)showActionSheetForCommentItemFromAnchor:(id)arg1;
- (void)showActionSheetForCommentItemFromAudience:(id)arg1;
- (void)layoutOperationView;
- (_Bool)invokeShowCompleteViewController;
- (void)showCompleteViewController:(id)arg1;
- (id)createCompleteViewController;
- (void)showLiveStarterViewController;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)unRegisterExtension;
- (void)registerExtension;
@property(readonly, nonatomic) MMFinderLiveTask *liveTask;
- (void)initLiveLogic;
- (void)initNotifications;
- (void)initData;
- (void)initAbnormalState;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

