//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "MMGroupLiveMgrExt-Protocol.h"
#import "MMLiveCommentDataPostExt-Protocol.h"
#import "MMLiveConnectMicExt-Protocol.h"
#import "MMLiveInputToolViewDelegate-Protocol.h"
#import "MMLiveTaskMgrExt-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"

@class CAGradientLayer, EmoticonBoardView, MMFinderLiveNotifyCommentLogic, MMFinderLiveTopCommentLogic, MMLiveCommentDataFetchEngne, MMLiveCommentDataMgr, MMLiveCommentDataPostEngine, MMLiveCommentPubbleView, MMLiveCommentTableViewModel, MMLiveCustomTouchView, MMLiveInputToolView, MMLiveTask, MMLiveTaskId, MMLiveUnReadCountView, MMTableView, MMUIButton, NSIndexPath, NSMutableArray, NSString, WCLiveBottomTextButton;
@protocol MMLiveCommentViewDelegate;

@interface MMLiveCommentView : UIView <MMGroupLiveMgrExt, WCActionSheetDelegate, MMLiveConnectMicExt, MMLiveTaskMgrExt, MMLiveInputToolViewDelegate, MMLiveCommentDataPostExt>
{
    _Bool _isAssumingAudienceCommentEnabled;
    _Bool _isForeignerUnableComment;
    _Bool _isCloseComment;
    _Bool _isContentShow;
    _Bool _isAntispamUnableComment;
    _Bool _isInLive;
    id <MMLiveCommentViewDelegate> _delegate;
    MMLiveTaskId *_taskId;
    unsigned long long _liveId;
    NSString *_roomId;
    NSMutableArray *_selfCommitTimeArray;
    MMLiveCommentDataFetchEngne *_commentFetchEngine;
    unsigned long long _previousCommentState;
    unsigned long long _lastCommentState;
    unsigned long long _commentState;
    long long _roleType;
    WCLiveBottomTextButton *_commentButton;
    MMFinderLiveNotifyCommentLogic *_notifyCommentLogic;
    MMFinderLiveTopCommentLogic *_topCommentNotifyLogic;
    UIView *_cancelEditMaskView;
    MMLiveCustomTouchView *_contentBackView;
    MMUIButton *_cancelEditButton;
    UIView *_commentTableBackView;
    CAGradientLayer *_commentTableBackGradientLayer;
    MMTableView *_commentTableView;
    MMLiveCustomTouchView *_commentTableTapView;
    MMLiveCommentTableViewModel *_commentTableViewModel;
    MMLiveInputToolView *_liveInputView;
    EmoticonBoardView *_emoticonBoardView;
    MMLiveUnReadCountView *_unReadCountLabel;
    MMLiveCommentPubbleView *_banCommentPubbleView;
    NSIndexPath *_visbleIndexPathBeforeCollapse;
    long long _currentOrientation;
    long long _currentLayoutOrientation;
}

- (void).cxx_destruct;
@property(nonatomic) long long currentLayoutOrientation; // @synthesize currentLayoutOrientation=_currentLayoutOrientation;
@property(nonatomic) long long currentOrientation; // @synthesize currentOrientation=_currentOrientation;
@property(retain, nonatomic) NSIndexPath *visbleIndexPathBeforeCollapse; // @synthesize visbleIndexPathBeforeCollapse=_visbleIndexPathBeforeCollapse;
@property(nonatomic) _Bool isInLive; // @synthesize isInLive=_isInLive;
@property(nonatomic) _Bool isAntispamUnableComment; // @synthesize isAntispamUnableComment=_isAntispamUnableComment;
@property(nonatomic) _Bool isContentShow; // @synthesize isContentShow=_isContentShow;
@property(nonatomic) _Bool isCloseComment; // @synthesize isCloseComment=_isCloseComment;
@property(nonatomic) _Bool isForeignerUnableComment; // @synthesize isForeignerUnableComment=_isForeignerUnableComment;
@property(retain, nonatomic) MMLiveCommentPubbleView *banCommentPubbleView; // @synthesize banCommentPubbleView=_banCommentPubbleView;
@property(retain, nonatomic) MMLiveUnReadCountView *unReadCountLabel; // @synthesize unReadCountLabel=_unReadCountLabel;
@property(retain, nonatomic) EmoticonBoardView *emoticonBoardView; // @synthesize emoticonBoardView=_emoticonBoardView;
@property(retain, nonatomic) MMLiveInputToolView *liveInputView; // @synthesize liveInputView=_liveInputView;
@property(retain, nonatomic) MMLiveCommentTableViewModel *commentTableViewModel; // @synthesize commentTableViewModel=_commentTableViewModel;
@property(retain, nonatomic) MMLiveCustomTouchView *commentTableTapView; // @synthesize commentTableTapView=_commentTableTapView;
@property(retain, nonatomic) MMTableView *commentTableView; // @synthesize commentTableView=_commentTableView;
@property(retain, nonatomic) CAGradientLayer *commentTableBackGradientLayer; // @synthesize commentTableBackGradientLayer=_commentTableBackGradientLayer;
@property(retain, nonatomic) UIView *commentTableBackView; // @synthesize commentTableBackView=_commentTableBackView;
@property(retain, nonatomic) MMUIButton *cancelEditButton; // @synthesize cancelEditButton=_cancelEditButton;
@property(retain, nonatomic) MMLiveCustomTouchView *contentBackView; // @synthesize contentBackView=_contentBackView;
@property(retain, nonatomic) UIView *cancelEditMaskView; // @synthesize cancelEditMaskView=_cancelEditMaskView;
@property(retain, nonatomic) MMFinderLiveTopCommentLogic *topCommentNotifyLogic; // @synthesize topCommentNotifyLogic=_topCommentNotifyLogic;
@property(retain, nonatomic) MMFinderLiveNotifyCommentLogic *notifyCommentLogic; // @synthesize notifyCommentLogic=_notifyCommentLogic;
@property(retain, nonatomic) WCLiveBottomTextButton *commentButton; // @synthesize commentButton=_commentButton;
@property(nonatomic) long long roleType; // @synthesize roleType=_roleType;
@property(nonatomic) unsigned long long commentState; // @synthesize commentState=_commentState;
@property(nonatomic) unsigned long long lastCommentState; // @synthesize lastCommentState=_lastCommentState;
@property(nonatomic) unsigned long long previousCommentState; // @synthesize previousCommentState=_previousCommentState;
@property(readonly, nonatomic) MMLiveCommentDataFetchEngne *commentFetchEngine; // @synthesize commentFetchEngine=_commentFetchEngine;
@property(nonatomic) _Bool isAssumingAudienceCommentEnabled; // @synthesize isAssumingAudienceCommentEnabled=_isAssumingAudienceCommentEnabled;
@property(retain, nonatomic) NSMutableArray *selfCommitTimeArray; // @synthesize selfCommitTimeArray=_selfCommitTimeArray;
@property(copy, nonatomic) NSString *roomId; // @synthesize roomId=_roomId;
@property(nonatomic) unsigned long long liveId; // @synthesize liveId=_liveId;
@property(retain, nonatomic) MMLiveTaskId *taskId; // @synthesize taskId=_taskId;
@property(nonatomic) __weak id <MMLiveCommentViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onAppendCommentDataItem:(id)arg1 forTaskId:(id)arg2;
- (void)restoreCommentDataAfterMinimize;
- (void)onExtendFromCollapseAnimationDidEndWithLiveTask:(id)arg1;
- (void)storeCommentDataBeforeMinimize;
- (void)onMinimizeInteractiveWillEnd:(id)arg1;
- (void)onCollapseAnimationWillStartBeforeRotation:(id)arg1;
- (void)handleUIOrientationChanged:(id)arg1;
- (void)handleLiveIsEnableCommentForAudience:(_Bool)arg1;
- (void)handleLiveIsEnableCommentForAnchor:(_Bool)arg1;
- (void)handleOnNotifyLiveIsEnableComment:(_Bool)arg1;
- (void)handleOnUpdateLiveCommentEnabledResult:(id)arg1 taskId:(id)arg2 enableComment:(_Bool)arg3 silence:(_Bool)arg4;
- (_Bool)applyUpdateLiveCommentEnabled:(_Bool)arg1 taskId:(id)arg2;
@property(readonly, nonatomic) MMLiveCommentDataPostEngine *commentPostEngine;
- (void)scrollToCommentTableBottom:(id)arg1;
- (void)closeGesture:(id)arg1;
- (void)onCancelEditTouched:(id)arg1;
- (void)onPostFailError:(id)arg1 localSeq:(long long)arg2 taskId:(id)arg3;
- (void)onLiveCanApplyConnecteMicChanged:(_Bool)arg1;
- (void)onLiveUnConnectedMic:(id)arg1;
- (void)onLiveConnectedMic:(id)arg1;
- (void)showToastForBanOrAllowComment:(_Bool)arg1 success:(_Bool)arg2;
- (void)handleBanOrOpenCommentFailed:(_Bool)arg1;
- (void)onInputViewShowChange:(_Bool)arg1;
- (double)getVisibleHeight;
- (_Bool)checkIsSelfCommitOverFrequency;
- (void)didCommitText:(id)arg1;
- (_Bool)checkCommentAbilityForAudience;
- (void)recordSelfComment;
- (void)showInputViewAtCommentTableViewRow:(long long)arg1;
@property(readonly, nonatomic) MMLiveTask *liveTask;
- (double)commentTableRight;
@property(readonly, nonatomic) _Bool isShowingInputView;
- (void)banOrOpenComment;
- (void)updateCommentButtonLeft;
- (void)updateCommentTableHeight;
- (void)updateCommentTableBottom;
- (void)onExitLive;
- (void)onEnterLive;
- (void)adjustCommentTableViewHeight;
@property(readonly, nonatomic) MMLiveCommentDataMgr *commentDataMgr;
- (id)createCommentTableViewModel;
- (_Bool)isChangeToDisableState;
- (void)displayBanCommentPubbleView:(id)arg1;
- (void)handleDisableCommentState:(id)arg1;
- (void)handleEnableCommentState:(id)arg1;
- (void)updateComponentHiddenForCommentEnableChanged;
- (void)resignCommentInput;
- (void)updateCommentState:(unsigned long long)arg1 banOrAllowCommentNotify:(id)arg2;
- (void)updateCommentState:(unsigned long long)arg1;
- (void)updateCommentButtonImage:(id)arg1 forState:(unsigned long long)arg2;
- (void)layoutCancelEditButton;
- (void)layoutCancelEditMaskView;
- (void)updateTableBackViewHidden;
- (void)updateCommentButtonHidden;
- (void)layoutCommentButton;
- (id)createUnReadCountStr;
- (void)updateUnReadCountLabel;
- (void)layoutUnReadCountLabel;
- (id)createUnReadCountLabel;
- (void)layoutEmoticonBoardView;
- (void)adjustCommentTableHeightForInputShowChange:(_Bool)arg1;
- (struct CGSize)getCommentTableBackBottomAreaSize;
- (void)layoutInputView;
- (void)layoutCommentTableTapView;
- (struct CGRect)commentTableTapViewFrame;
- (void)handleTableViewPanGesture:(id)arg1;
- (void)layoutCommentTableView;
- (id)registerCellClasses;
- (Class)commentTableCellClass;
- (double)commentTableHeight;
- (double)commentTableWidth;
- (double)commentTableHeightForInputShow:(_Bool)arg1;
- (void)layoutCommentTableBackView;
- (double)commentTableBackViewBottom;
- (void)layoutContentBackView;
- (void)forceLayoutForOrientationChanged;
- (void)showContent;
- (void)hideContent;
- (void)layoutUI;
- (void)addGestureRecognizers;
- (void)initDefaultData;
- (void)restoreVisibleCommentAfterRotate;
- (void)storeVisibleCommentBeforeRotate;
- (void)handleLayoutOrientationChanged;
- (void)layoutSubviews;
- (void)initNotification;
- (void)unRegisterExtension;
- (void)registerExtension;
- (void)dealloc;
- (id)initWithTaskId:(id)arg1 assumeAudienceCommentEnabled:(_Bool)arg2 delegate:(id)arg3;
- (id)initWithTaskId:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

