//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMLiveCommentPubbleCell.h"

@class UIImageView, UIView;

@interface MMLiveCommentPubbleUserGeneralCell : MMLiveCommentPubbleCell
{
    UIView *_selfLikeTagBackView;
    UIImageView *_selfLikeIconView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *selfLikeIconView; // @synthesize selfLikeIconView=_selfLikeIconView;
@property(retain, nonatomic) UIView *selfLikeTagBackView; // @synthesize selfLikeTagBackView=_selfLikeTagBackView;
- (void)layoutSelfLikeIconView;
- (void)layoutSelfLikeTagBackView;
- (void)updateCommentLabelOrigin;
- (_Bool)isSelfLike;
- (_Bool)isUITypeValid;
- (void)layoutUI;

@end

