//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

#import "MMLiveGestureRecognizerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class MMFinderLiveCommentCollectionViewModel, MMLiveTaskId, MMLivecCommentCollectionView, MMUILabel, NSString, UIView;

@interface MMLivecCommentCollectionBackView : MMUIView <MMLiveGestureRecognizerDelegate, UIGestureRecognizerDelegate>
{
    MMLiveTaskId *_taskId;
    MMLivecCommentCollectionView *_commmentCollectionView;
    CDUnknownBlockType _pressShowProfileCallback;
    CDUnknownBlockType _backViewDidTapCallback;
    UIView *_collectionContentBackView;
    MMFinderLiveCommentCollectionViewModel *_commentCollectionViewModel;
    MMUILabel *_unReadCountLabel;
    unsigned long long _currentUnReadCount;
}

+ (double)TopMostLikeCommentPartHeight;
+ (double)liveCommentCollectionBackHeight;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long currentUnReadCount; // @synthesize currentUnReadCount=_currentUnReadCount;
@property(retain, nonatomic) MMUILabel *unReadCountLabel; // @synthesize unReadCountLabel=_unReadCountLabel;
@property(retain, nonatomic) MMFinderLiveCommentCollectionViewModel *commentCollectionViewModel; // @synthesize commentCollectionViewModel=_commentCollectionViewModel;
@property(retain, nonatomic) UIView *collectionContentBackView; // @synthesize collectionContentBackView=_collectionContentBackView;
@property(copy, nonatomic) CDUnknownBlockType backViewDidTapCallback; // @synthesize backViewDidTapCallback=_backViewDidTapCallback;
@property(copy, nonatomic) CDUnknownBlockType pressShowProfileCallback; // @synthesize pressShowProfileCallback=_pressShowProfileCallback;
@property(retain, nonatomic) MMLivecCommentCollectionView *commmentCollectionView; // @synthesize commmentCollectionView=_commmentCollectionView;
@property(retain, nonatomic) MMLiveTaskId *taskId; // @synthesize taskId=_taskId;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)onTouchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)onTouchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)handleCollectionViewScrollToBottom:(id)arg1;
- (void)handleCollectionViewLongPressGesture:(id)arg1;
- (void)handleCollectionViewSingleTapGesture:(id)arg1;
- (void)handleCollectionViewPanGesture:(id)arg1;
- (void)updateUnReadCountContent;
- (id)createUnReadCountStr;
- (double)currentUnReadCountBottom;
- (void)layoutUnReadCountLabel;
- (void)layoutCommentCollectionView;
- (void)layoutCollectionContentBackView;
- (void)layoutUI;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

