//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MMLiveCommentDataExt-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class MMLiveCommentDataItem, MMLiveCommentDataMgr, MMLiveTaskId, NSMutableArray, NSMutableString, NSString, UITableView;

@interface MMLiveCommentTableViewModel : NSObject <MMLiveCommentDataExt, UITableViewDelegate, UITableViewDataSource>
{
    _Bool _enableScroll;
    _Bool _isReloading;
    _Bool _isScrolling;
    _Bool _isAutoScroll;
    _Bool _isEnterBackground;
    _Bool _isPubbleCellLongPressTouching;
    _Bool _isTableViewNeedStopAutoScrolling;
    unsigned long long _unReadCount;
    UITableView *_commentTableView;
    CDUnknownBlockType _tableReloadBlock;
    CDUnknownBlockType _unReadUnpdateBlock;
    CDUnknownBlockType _refreshCallbackBlock;
    CDUnknownBlockType _toastBlock;
    CDUnknownBlockType _cellDidTapBlock;
    CDUnknownBlockType _cellDidLongPressedBlock;
    CDUnknownBlockType _tableViewDidTapBlock;
    NSMutableArray *_tableOperationQueue;
    long long _currentOperationType;
    MMLiveTaskId *_taskId;
    NSMutableArray *_commentArray;
    NSMutableArray *_commentCellFrameArray;
    double _lastCheckContentOffsetY;
    MMLiveCommentDataItem *_lastDisplayCommentItem;
    NSMutableArray *_deleteCommentArray;
    long long _maxCommentSeq;
    double _logCommentTime;
    NSMutableString *_logCommentStr;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableString *logCommentStr; // @synthesize logCommentStr=_logCommentStr;
@property(nonatomic) double logCommentTime; // @synthesize logCommentTime=_logCommentTime;
@property(nonatomic) long long maxCommentSeq; // @synthesize maxCommentSeq=_maxCommentSeq;
@property(nonatomic) _Bool isTableViewNeedStopAutoScrolling; // @synthesize isTableViewNeedStopAutoScrolling=_isTableViewNeedStopAutoScrolling;
@property(nonatomic) _Bool isPubbleCellLongPressTouching; // @synthesize isPubbleCellLongPressTouching=_isPubbleCellLongPressTouching;
@property(retain, nonatomic) NSMutableArray *deleteCommentArray; // @synthesize deleteCommentArray=_deleteCommentArray;
@property(retain, nonatomic) MMLiveCommentDataItem *lastDisplayCommentItem; // @synthesize lastDisplayCommentItem=_lastDisplayCommentItem;
@property(nonatomic) _Bool isEnterBackground; // @synthesize isEnterBackground=_isEnterBackground;
@property(nonatomic) _Bool isAutoScroll; // @synthesize isAutoScroll=_isAutoScroll;
@property(nonatomic) _Bool isScrolling; // @synthesize isScrolling=_isScrolling;
@property(nonatomic) double lastCheckContentOffsetY; // @synthesize lastCheckContentOffsetY=_lastCheckContentOffsetY;
@property(retain, nonatomic) NSMutableArray *commentCellFrameArray; // @synthesize commentCellFrameArray=_commentCellFrameArray;
@property(retain, nonatomic) NSMutableArray *commentArray; // @synthesize commentArray=_commentArray;
@property(nonatomic) _Bool isReloading; // @synthesize isReloading=_isReloading;
@property(retain, nonatomic) MMLiveTaskId *taskId; // @synthesize taskId=_taskId;
@property(nonatomic) long long currentOperationType; // @synthesize currentOperationType=_currentOperationType;
@property(retain, nonatomic) NSMutableArray *tableOperationQueue; // @synthesize tableOperationQueue=_tableOperationQueue;
@property(copy, nonatomic) CDUnknownBlockType tableViewDidTapBlock; // @synthesize tableViewDidTapBlock=_tableViewDidTapBlock;
@property(copy, nonatomic) CDUnknownBlockType cellDidLongPressedBlock; // @synthesize cellDidLongPressedBlock=_cellDidLongPressedBlock;
@property(copy, nonatomic) CDUnknownBlockType cellDidTapBlock; // @synthesize cellDidTapBlock=_cellDidTapBlock;
@property(copy, nonatomic) CDUnknownBlockType toastBlock; // @synthesize toastBlock=_toastBlock;
@property(copy, nonatomic) CDUnknownBlockType refreshCallbackBlock; // @synthesize refreshCallbackBlock=_refreshCallbackBlock;
@property(copy, nonatomic) CDUnknownBlockType unReadUnpdateBlock; // @synthesize unReadUnpdateBlock=_unReadUnpdateBlock;
@property(copy, nonatomic) CDUnknownBlockType tableReloadBlock; // @synthesize tableReloadBlock=_tableReloadBlock;
@property(nonatomic) _Bool enableScroll; // @synthesize enableScroll=_enableScroll;
@property(retain, nonatomic) UITableView *commentTableView; // @synthesize commentTableView=_commentTableView;
@property(nonatomic) unsigned long long unReadCount; // @synthesize unReadCount=_unReadCount;
- (void)didEnterBackground:(id)arg1;
- (void)willEnterForeground:(id)arg1;
@property(readonly, nonatomic) _Bool isAutoScrollToRefreshNewData;
@property(readonly, nonatomic) _Bool isLastCommentItemDisplaying;
@property(readonly, nonatomic) _Bool hasLoadedLastItem;
@property(readonly, nonatomic) MMLiveCommentDataMgr *commentDataMgr;
- (void)handleTableViewPanGesture:(id)arg1;
- (void)startRefresh;
- (void)scrollCommentTableViewToRow:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)scrollCommentTableViewToBottomAnimated:(_Bool)arg1;
- (_Bool)isTableViewScrollToBottom;
- (unsigned long long)currentCommentCount;
- (void)onExitLive;
- (void)onEnterLive;
- (void)appendCommentToBottom:(_Bool)arg1;
- (id)appendComboLiveRewardCommentWithReward:(id)arg1 sendingComboId:(id)arg2 comboGiftCount:(unsigned long long)arg3;
- (id)appendCommentContentFromMySelf:(id)arg1;
- (double)getCellHeightFromCellFrame:(id)arg1 inPortrait:(_Bool)arg2;
- (long long)lastRowForVisibleContentOffsetY:(double)arg1 inPortrait:(_Bool)arg2;
- (double)tableViewHeightFromTopToRow:(long long)arg1;
- (id)createCommentPubbleViewWithCommentItem:(id)arg1;
- (_Bool)checkIsPreAppendComments;
- (_Bool)checkIsNeedPreInsertComments;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)onMMLiveCommentDataDeleted:(long long)arg1 forTaskId:(id)arg2;
- (void)onMMLiveCommentDataUpdateForTaskId:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)prepareTableViewCellForReuse:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)reloadTableWithRestoreInitialOffset:(double)arg1;
- (double)firstVisibleContentOffset;
- (id)firstVisibleComment;
- (void)handleCommentsDelete;
- (void)checkCommentArrayOverLimitAndClear;
- (_Bool)isRemovedRangeContainVisible:(struct _NSRange)arg1;
- (long long)getCommentArrayOverLimitCount;
- (void)insertCellFrameArray:(id)arg1;
- (_Bool)insertLiveCommentArray;
- (void)appendCellFrameArray:(id)arg1;
- (unsigned long long)appendLiveCommentArray:(_Bool)arg1 mostAppendCount:(long long)arg2;
- (void)logForNewComments:(id)arg1 append:(_Bool)arg2;
- (id)lastValidCommentItem;
- (unsigned long long)appendLiveCommentArray:(_Bool)arg1;
- (void)updateLastLineCellFrame:(_Bool)arg1;
- (void)reloadTable;
- (void)updateUnReadCount:(long long)arg1;
- (void)appendCommentToMost:(_Bool)arg1;
- (unsigned long long)getLiveBusinessType;
- (void)preAppendComment;
- (void)preInsertComment;
- (void)insertCommentForRefresh;
- (void)endOperationTypeAfterScrollToBottom;
- (void)updateTable:(_Bool)arg1 scrollToBottom:(_Bool)arg2 scrollAnimated:(_Bool)arg3;
- (void)refreshData;
- (long long)getUnMergedCount;
- (void)endTableOperation:(long long)arg1;
- (void)clearAllOperations;
- (void)clearAllOperation:(long long)arg1;
- (void)logOperationStr:(long long)arg1;
- (void)handleTableOperation:(long long)arg1;
- (void)operateCommentTable;
- (_Bool)checkTypeNeedAdded:(long long)arg1;
- (void)insertOperationType:(long long)arg1 after:(long long)arg2;
- (void)addOperationType:(long long)arg1;
- (void)dealloc;
- (id)initWithTaskId:(id)arg1;
- (Class)commentTableViewCellFrameClass;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

