//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ILinkEventExt-Protocol.h"
#import "MMLimitedModeConfigListViewDelegate-Protocol.h"
#import "MMLimitedModeExt-Protocol.h"

@class MMLimitedModeConfigListView, MMUIButton, MMUILabel, NSString, RichTextView, UIButton, UIImageView;

@interface MMLimitedModeEntryViewController : MMUIViewController <MMLimitedModeConfigListViewDelegate, MMLimitedModeExt, ILinkEventExt>
{
    _Bool _isSelected;
    MMUILabel *_titleLabel;
    UIImageView *_iconImageView;
    MMUILabel *_descLabel;
    MMUILabel *_openTipLabel;
    UIButton *_openButton;
    UIButton *_closeButton;
    MMLimitedModeConfigListView *_listView;
    MMUIButton *_selectedButton;
    UIImageView *_selectImageView;
    RichTextView *_confirmTextView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) RichTextView *confirmTextView; // @synthesize confirmTextView=_confirmTextView;
@property(retain, nonatomic) UIImageView *selectImageView; // @synthesize selectImageView=_selectImageView;
@property(retain, nonatomic) MMUIButton *selectedButton; // @synthesize selectedButton=_selectedButton;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(retain, nonatomic) MMLimitedModeConfigListView *listView; // @synthesize listView=_listView;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UIButton *openButton; // @synthesize openButton=_openButton;
@property(retain, nonatomic) MMUILabel *openTipLabel; // @synthesize openTipLabel=_openTipLabel;
@property(retain, nonatomic) MMUILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) MMUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)onChangeLimitedModeFail;
- (void)onLimitedModeBizLevelChange:(long long)arg1 bizType:(long long)arg2;
- (void)onLimitedModeChanged;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onHelpButtonClick;
- (void)onSelectButtonClick;
- (void)onBack;
- (void)onCloseButtonClick;
- (void)onOpenButtonClick;
- (void)onSelectedAtBizCell:(long long)arg1;
- (id)navigationBarBackgroundColor;
- (void)reloadContent;
- (void)initUI;
- (void)tryPopPreviousEntryViewControllerInNavBar;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

