//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

@class MMFinderLiveTask, MMFinderPivotLiveViewController, MMLivePivotViewController, UINavigationController, WCFinderDataItem;

@interface MMLivePivotItemViewController : MMUIViewController
{
    _Bool _isInPreview;
    UINavigationController *_presentingNavCon;
    MMLivePivotViewController *_pivotViewController;
    MMFinderPivotLiveViewController *_controller;
    MMFinderLiveTask *_liveTask;
    WCFinderDataItem *_dataItem;
    UINavigationController *_navControl;
}

- (void).cxx_destruct;
@property _Bool isInPreview; // @synthesize isInPreview=_isInPreview;
@property __weak UINavigationController *navControl; // @synthesize navControl=_navControl;
@property(retain) WCFinderDataItem *dataItem; // @synthesize dataItem=_dataItem;
@property(retain) MMFinderLiveTask *liveTask; // @synthesize liveTask=_liveTask;
@property(retain) MMFinderPivotLiveViewController *controller; // @synthesize controller=_controller;
@property(nonatomic) __weak MMLivePivotViewController *pivotViewController; // @synthesize pivotViewController=_pivotViewController;
@property(nonatomic) __weak UINavigationController *presentingNavCon; // @synthesize presentingNavCon=_presentingNavCon;
- (void)checkAndResumeLive;
- (void)updateSafeAreaInsets;
- (void)viewSafeAreaInsetsDidChange;
- (void)viewWillLayoutSubviews;
- (void)onLiveComplete;
- (void)layoutController;
- (id)liveController;
- (void)endLive;
- (void)startLive;
- (void)stopPreview;
- (void)startPreview;
- (void)prepareController;
- (void)prepareLiveTask;
- (void)loadView;
- (id)initWithFinderDataItem:(id)arg1;

@end

