//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMLiveCommentPubbleCell.h"

@class MMHeadImageView, RichTextView;

@interface MMLiveCommentPubbleAudienceJoinCell : MMLiveCommentPubbleCell
{
    MMHeadImageView *_headImageView;
    RichTextView *_nickLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) RichTextView *nickLabel; // @synthesize nickLabel=_nickLabel;
@property(retain, nonatomic) MMHeadImageView *headImageView; // @synthesize headImageView=_headImageView;
- (void)updateCommentLabelOrigin;
- (void)updateNickLabelOrigin;
- (void)layoutNickLabel;
- (void)updateHeadImageViewOrigin;
- (void)layoutHeadImageView;
- (_Bool)isUITypeValid;
- (void)layoutUI;

@end

