//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ILiveTaskMgrExt-Protocol.h"
#import "TXLivePlayListener-Protocol.h"
#import "WCFinderFeedImageCDNViewDelegate-Protocol.h"

@class NSString, TRTCCdnPlayerManager, WCFinderAnimationLoadingView, WCFinderFeedImageCDNView;
@protocol MMLiveCDNPlayerViewDelegate;

@interface MMLiveCDNPlayerView : UIView <TXLivePlayListener, WCFinderFeedImageCDNViewDelegate, ILiveTaskMgrExt>
{
    _Bool _isMuted;
    _Bool _isPlayerLoading;
    id <MMLiveCDNPlayerViewDelegate> _delegate;
    NSString *_url;
    WCFinderAnimationLoadingView *_loadingView;
    UIView *_cdnPlayerView;
    TRTCCdnPlayerManager *_cdnPlayer;
    WCFinderFeedImageCDNView *_coverView;
    unsigned long long _feedScreenStyle;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long feedScreenStyle; // @synthesize feedScreenStyle=_feedScreenStyle;
@property(retain, nonatomic) WCFinderFeedImageCDNView *coverView; // @synthesize coverView=_coverView;
@property(nonatomic) _Bool isPlayerLoading; // @synthesize isPlayerLoading=_isPlayerLoading;
@property(nonatomic) _Bool isMuted; // @synthesize isMuted=_isMuted;
@property(retain, nonatomic) TRTCCdnPlayerManager *cdnPlayer; // @synthesize cdnPlayer=_cdnPlayer;
@property(retain, nonatomic) UIView *cdnPlayerView; // @synthesize cdnPlayerView=_cdnPlayerView;
@property(retain, nonatomic) WCFinderAnimationLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) __weak id <MMLiveCDNPlayerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)updatePlayerMuted;
- (void)onMMLiveFinishedForNotifyOuter;
- (void)onMMLiveStartForNotifyOuter;
- (void)onNetStatus:(id)arg1;
- (void)onPlayEvent:(int)arg1 withParam:(id)arg2;
- (void)finderFeedImageLoadFinish;
- (void)hiddenLoadingView;
- (void)showLoadingView;
- (void)updateLoadingViewToCenter;
- (_Bool)isAlreadyConfigured;
- (void)updateImageWithMediaWrap:(id)arg1 downloadFlag:(unsigned long long)arg2 isPriority:(_Bool)arg3;
- (void)showLive;
- (void)showCover;
- (_Bool)isPlaying;
- (void)setMute:(_Bool)arg1;
- (void)pause;
- (void)resume;
- (void)stopPlay;
- (void)startPlayWithUrl:(id)arg1;
- (void)checkAndInitLoadingView;
- (void)updateCoverViewBlurStateFeedScreenStyle:(unsigned long long)arg1;
- (void)checkAndInitCoverImageView;
- (void)checkAndInitCdnPlayerView;
- (void)layoutUI;
- (void)setFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 andDelegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

