//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewLayout.h>

#import "UICollectionViewDataSource-Protocol.h"

@class MMLivePivotFooterView, NSArray, NSString;
@protocol MMLivePivotViewDelegate;

@interface MMLivePivotView : UICollectionViewLayout <UICollectionViewDataSource>
{
    _Bool _isRecommendationLoading;
    NSArray *_finderDataItems;
    id <MMLivePivotViewDelegate> _delegate;
    MMLivePivotFooterView *_footerView;
}

- (void).cxx_destruct;
@property(retain) MMLivePivotFooterView *footerView; // @synthesize footerView=_footerView;
@property __weak id <MMLivePivotViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isRecommendationLoading; // @synthesize isRecommendationLoading=_isRecommendationLoading;
@property(readonly, nonatomic) NSArray *finderDataItems; // @synthesize finderDataItems=_finderDataItems;
- (id)footerLayoutAttributesWithContentSize:(struct CGSize)arg1;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (struct CGSize)collectionViewContentSize;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

