//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMMusicMVModelConverter : NSObject
{
}

+ (id)genMusicInfoFromMVModel:(id)arg1;
+ (id)finderOriginalInfoFromMVOriginalInfo:(id)arg1;
+ (id)mvOriginalInfoFromFinderOriginalInfo:(id)arg1;
+ (id)finderSongInfoFromMVSongInfo:(id)arg1;
+ (id)mvSongInfoFromFinderSongInfo:(id)arg1;
+ (id)finderMVInfoFromMusicMVModel:(id)arg1;
+ (id)musicMVModelFromFinderDataItem:(id)arg1 finderObject:(id)arg2;

@end

