//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IMMMusicLyricServiceExt-Protocol.h"
#import "IMusicPlayerExt-Protocol.h"
#import "MMMusicEditVideoCellViewDelegate-Protocol.h"
#import "MMMusicLiveCGIMgrDelegate-Protocol.h"
#import "MMMusicLyricsRtnExt-Protocol.h"
#import "MMMusicMVEditorCardCellDelegate-Protocol.h"
#import "MMMusicMVPostPublishLogicDelegate-Protocol.h"
#import "MMMusicPostVideoDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class MMMusicEditVideoCellView, MMMusicLiveCGIMgr, MMMusicLiveLyricDisplayView, MMMusicMVEditorCardCell, MMMusicMVEditorCollectionView, MMMusicMVModel, MMMusicMVPostPublishLogic, MMMusicPostVideoAnimHelper, MMMusicPostVideoViewController, MMTimer, MMUIButton, NSString, UIView;
@protocol MMMusicMVEditorViewControllerDelegate;

@interface MMMusicMVEditorViewController : MMUIViewController <MMMusicLyricsRtnExt, UICollectionViewDataSource, UICollectionViewDelegate, MMMusicMVPostPublishLogicDelegate, IMusicPlayerExt, IMMMusicLyricServiceExt, MMMusicPostVideoDelegate, MMMusicEditVideoCellViewDelegate, MMMusicMVEditorCardCellDelegate, MMMusicLiveCGIMgrDelegate>
{
    _Bool _seekSpecifyTimeFlag;
    _Bool _isEditVideoMode;
    id <MMMusicMVEditorViewControllerDelegate> _delegate;
    unsigned long long _currentIndex;
    NSString *_songId;
    MMMusicMVEditorCollectionView *_collectionView;
    MMUIButton *_cancelButton;
    MMUIButton *_doneButton;
    MMMusicLiveLyricDisplayView *_lyricView;
    MMTimer *_musicMonitorTimer;
    MMMusicMVPostPublishLogic *_publishLogic;
    UIView *_videoTransitionMask;
    MMMusicPostVideoViewController *_videoSourceViewController;
    MMMusicEditVideoCellView *_editVideoCellView;
    MMMusicMVEditorCardCell *_lastPlayingCardCell;
    MMMusicMVModel *_mvModel;
    MMMusicLiveCGIMgr *_cgiMgr;
    MMMusicPostVideoAnimHelper *_postAnimhelper;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMMusicPostVideoAnimHelper *postAnimhelper; // @synthesize postAnimhelper=_postAnimhelper;
@property(retain, nonatomic) MMMusicLiveCGIMgr *cgiMgr; // @synthesize cgiMgr=_cgiMgr;
@property(retain, nonatomic) MMMusicMVModel *mvModel; // @synthesize mvModel=_mvModel;
@property(nonatomic) _Bool isEditVideoMode; // @synthesize isEditVideoMode=_isEditVideoMode;
@property(nonatomic) __weak MMMusicMVEditorCardCell *lastPlayingCardCell; // @synthesize lastPlayingCardCell=_lastPlayingCardCell;
@property(retain, nonatomic) MMMusicEditVideoCellView *editVideoCellView; // @synthesize editVideoCellView=_editVideoCellView;
@property(retain, nonatomic) MMMusicPostVideoViewController *videoSourceViewController; // @synthesize videoSourceViewController=_videoSourceViewController;
@property(nonatomic) _Bool seekSpecifyTimeFlag; // @synthesize seekSpecifyTimeFlag=_seekSpecifyTimeFlag;
@property(retain, nonatomic) UIView *videoTransitionMask; // @synthesize videoTransitionMask=_videoTransitionMask;
@property(retain, nonatomic) MMMusicMVPostPublishLogic *publishLogic; // @synthesize publishLogic=_publishLogic;
@property(retain, nonatomic) MMTimer *musicMonitorTimer; // @synthesize musicMonitorTimer=_musicMonitorTimer;
@property(retain, nonatomic) MMMusicLiveLyricDisplayView *lyricView; // @synthesize lyricView=_lyricView;
@property(retain, nonatomic) MMUIButton *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) MMUIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) MMMusicMVEditorCollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSString *songId; // @synthesize songId=_songId;
@property(nonatomic) unsigned long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(nonatomic) __weak id <MMMusicMVEditorViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onMMMusicEditVideoCellViewFinish:(id)arg1;
- (void)onMMMusicEditVideoCellViewCancel:(id)arg1;
- (void)onMusicLiveGetSongStatusWithIsSuccess:(_Bool)arg1 resp:(id)arg2;
- (void)onPostPublishLogicFinishedCancelPublishing;
- (void)onPostPublishLogicFinishedPosting:(id)arg1;
- (void)onPostPublishLogicFinishedSavingAsDraft:(id)arg1;
- (void)onClickDoneBtn;
- (void)onClickCancelBtn;
- (void)updateMusicPlayProress;
- (id)trackItems;
- (void)onMusicPlayStatusChanged;
- (void)onLyricService:(id)arg1 curentLyricChangeTo:(id)arg2 timeToNext:(double)arg3 currIndex:(unsigned int)arg4;
- (_Bool)isMusicMVEditorCardCellInUse:(id)arg1;
- (void)setupLyricForCellIfNeeded:(id)arg1;
- (void)scrollEpisodeToIndex:(unsigned long long)arg1;
- (void)updateCurrentIndexAndPlayTime:(unsigned long long)arg1;
- (void)reloadData;
- (void)updateVideoPlayingCell:(id)arg1;
- (void)updateVideoViewLayer:(id)arg1 isCurrentIndex:(_Bool)arg2;
- (void)refreshVisibleItemsPlayState;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)clickCropButton:(id)arg1;
- (void)revertPostForTrack:(id)arg1;
- (void)setupCreateMVState;
- (void)onPostVideoShortVideoTaken:(id)arg1 thumbImg:(id)arg2 editVideoAttr:(id)arg3 paramModel:(id)arg4;
- (void)onSelectLocalVideoAsset:(id)arg1 thumbImage:(id)arg2 thumbFrameInVC:(struct CGRect)arg3;
- (void)onSelectFinderVideo:(id)arg1 thumbImage:(id)arg2 cellFrameInVC:(struct CGRect)arg3;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)handleTap:(id)arg1;
- (void)resetEditVideoCellView;
- (void)initEditVideoCellView;
- (void)setupSubviews;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithMVModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

