//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IMMMusicLyricServiceExt-Protocol.h"
#import "InputControllerDelegate-Protocol.h"
#import "MMMusicLiveCommentViewDelegate-Protocol.h"
#import "MMMusicLiveMVAuthorInfoViewDelegate-Protocol.h"
#import "MMMusicLiveMusicOperationViewDelegate-Protocol.h"
#import "MMMusicLiveVCTopBarViewDelegate-Protocol.h"
#import "MMMusicLyricsViewControllerDelegate-Protocol.h"
#import "MMScrollActionSheetDelegate-Protocol.h"
#import "MMUIHalfScreenViewControllerDelegate-Protocol.h"
#import "SendAppMsgHandleDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"
#import "WCFinderDynamicFetchIconDelegate-Protocol.h"

@class CAGradientLayer, MMGrowTextView, MMMusicDotMVDataSource, MMMusicInfo, MMMusicInfoHalfViewController, MMMusicLiveCommentModel, MMMusicLiveCommentView, MMMusicLiveLyricDisplayView, MMMusicLiveMVAuthorInfoView, MMMusicLiveMusicOperationView, MMMusicLiveVCTopBarView, MMMusicLyricsViewController, MMMusicMVPostingStateView, MMScrollActionSheet, MMUIActivityIndicatorView, MMUIButton, NSString, SendAppMsgHandler, UIButton, UIImageView, UILabel, UIView, WCActionSheet, WCInputController;
@protocol MMMusicLiveViewControllerDelegate;

@interface MMMusicLiveViewController : MMUIViewController <MMMusicLiveMusicOperationViewDelegate, IMMMusicLyricServiceExt, MMMusicLiveCommentViewDelegate, InputControllerDelegate, MMMusicLiveMVAuthorInfoViewDelegate, MMMusicLiveVCTopBarViewDelegate, WCFinderDynamicFetchIconDelegate, SendAppMsgHandleDelegate, MMUIHalfScreenViewControllerDelegate, MMMusicLyricsViewControllerDelegate, WCActionSheetDelegate, UIScrollViewDelegate, MMScrollActionSheetDelegate>
{
    int _pushedFromType;
    MMScrollActionSheet *_scrollActionSheet;
    CAGradientLayer *m_topMaskLayer;
    CAGradientLayer *m_bottomMaskLayer;
    MMMusicLiveMVAuthorInfoView *_finderAuthorInfoView;
    WCActionSheet *_shareActionSheet;
    MMMusicInfoHalfViewController *_musicInfoHalfVC;
    MMMusicLyricsViewController *m_lyricsVC;
    _Bool _isDragging;
    _Bool _isClearing;
    _Bool _isShowingKeyboard;
    _Bool _isInLyricsVC;
    id <MMMusicLiveViewControllerDelegate> _delegate;
    MMMusicDotMVDataSource *_mvDataSource;
    MMMusicInfo *_musicInfo;
    NSString *_songId;
    MMMusicLiveMusicOperationView *_musicOperationView;
    MMMusicLiveLyricDisplayView *_lyricView;
    UIView *_lyricViewContainerView;
    MMMusicLiveVCTopBarView *_topBarView;
    UILabel *_likeNumLabel;
    MMUIButton *_likeBtn;
    UILabel *_commentNumLabel;
    MMUIButton *_commentBtn;
    UILabel *_shareTipsLabel;
    MMUIButton *_shareBtn;
    MMUIButton *_playBtn;
    MMUIButton *_pauseBtn;
    MMUIActivityIndicatorView *_loadingView;
    unsigned long long _state;
    SendAppMsgHandler *_sendAppMsgHandler;
    UIView *_commentActivatedBgView;
    MMMusicLiveCommentModel *_commentModel;
    MMMusicLiveCommentView *_commentView;
    MMGrowTextView *_commentInputView;
    UIView *_inputAreaView;
    WCInputController *_inputController;
    UILabel *_noneCreatedTipsLabel;
    UIButton *_createBtn;
    UIView *_bottomContainerView;
    UIImageView *_deletedLogoImageView;
    UILabel *_deletedTipsLabel;
    UIButton *_nextBtn;
    MMMusicMVPostingStateView *_postingStateView;
}

+ (id)logStr:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) MMMusicMVPostingStateView *postingStateView; // @synthesize postingStateView=_postingStateView;
@property(retain, nonatomic) UIButton *nextBtn; // @synthesize nextBtn=_nextBtn;
@property(retain, nonatomic) UILabel *deletedTipsLabel; // @synthesize deletedTipsLabel=_deletedTipsLabel;
@property(retain, nonatomic) UIImageView *deletedLogoImageView; // @synthesize deletedLogoImageView=_deletedLogoImageView;
@property(retain, nonatomic) UIView *bottomContainerView; // @synthesize bottomContainerView=_bottomContainerView;
@property(retain, nonatomic) UIButton *createBtn; // @synthesize createBtn=_createBtn;
@property(retain, nonatomic) UILabel *noneCreatedTipsLabel; // @synthesize noneCreatedTipsLabel=_noneCreatedTipsLabel;
@property(retain, nonatomic) WCInputController *inputController; // @synthesize inputController=_inputController;
@property(retain, nonatomic) UIView *inputAreaView; // @synthesize inputAreaView=_inputAreaView;
@property(retain, nonatomic) MMGrowTextView *commentInputView; // @synthesize commentInputView=_commentInputView;
@property(retain, nonatomic) MMMusicLiveCommentView *commentView; // @synthesize commentView=_commentView;
@property(retain, nonatomic) MMMusicLiveCommentModel *commentModel; // @synthesize commentModel=_commentModel;
@property(retain, nonatomic) UIView *commentActivatedBgView; // @synthesize commentActivatedBgView=_commentActivatedBgView;
@property(retain, nonatomic) SendAppMsgHandler *sendAppMsgHandler; // @synthesize sendAppMsgHandler=_sendAppMsgHandler;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(retain, nonatomic) MMUIActivityIndicatorView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) MMUIButton *pauseBtn; // @synthesize pauseBtn=_pauseBtn;
@property(retain, nonatomic) MMUIButton *playBtn; // @synthesize playBtn=_playBtn;
@property(retain, nonatomic) MMUIButton *shareBtn; // @synthesize shareBtn=_shareBtn;
@property(retain, nonatomic) UILabel *shareTipsLabel; // @synthesize shareTipsLabel=_shareTipsLabel;
@property(retain, nonatomic) MMUIButton *commentBtn; // @synthesize commentBtn=_commentBtn;
@property(retain, nonatomic) UILabel *commentNumLabel; // @synthesize commentNumLabel=_commentNumLabel;
@property(retain, nonatomic) MMUIButton *likeBtn; // @synthesize likeBtn=_likeBtn;
@property(retain, nonatomic) UILabel *likeNumLabel; // @synthesize likeNumLabel=_likeNumLabel;
@property(retain, nonatomic) MMMusicLiveVCTopBarView *topBarView; // @synthesize topBarView=_topBarView;
@property(retain, nonatomic) UIView *lyricViewContainerView; // @synthesize lyricViewContainerView=_lyricViewContainerView;
@property(retain, nonatomic) MMMusicLiveLyricDisplayView *lyricView; // @synthesize lyricView=_lyricView;
@property(retain, nonatomic) MMMusicLiveMusicOperationView *musicOperationView; // @synthesize musicOperationView=_musicOperationView;
@property(retain, nonatomic) NSString *songId; // @synthesize songId=_songId;
@property(retain, nonatomic) MMMusicInfo *musicInfo; // @synthesize musicInfo=_musicInfo;
@property(nonatomic) _Bool isInLyricsVC; // @synthesize isInLyricsVC=_isInLyricsVC;
@property(nonatomic) _Bool isShowingKeyboard; // @synthesize isShowingKeyboard=_isShowingKeyboard;
@property(nonatomic) _Bool isClearing; // @synthesize isClearing=_isClearing;
@property(nonatomic) _Bool isDragging; // @synthesize isDragging=_isDragging;
@property(retain, nonatomic) MMMusicDotMVDataSource *mvDataSource; // @synthesize mvDataSource=_mvDataSource;
@property(nonatomic) __weak id <MMMusicLiveViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onSwitchToMMMusicLiveViewController;
- (void)actionSheetCancel:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)updateLiveVCStateByAction:(unsigned long long)arg1;
- (unsigned long long)calcStatusFromAction:(unsigned long long)arg1 andCurStatus:(unsigned long long)arg2;
- (id)getLikeCountStr:(unsigned long long)arg1;
- (void)onClickOpenStatusSetting;
- (void)onClickOpenMusicAppLabel;
- (void)onAuthorInfoViewClickSwitch;
- (void)onAuthorInfoViewClickFinderHitLabel;
- (void)onAuthorInfoViewClickMVNickName;
- (void)onAuthorInfoViewClickMVAvatar;
- (void)onMusicResume:(double)arg1;
- (void)onMusicPause:(double)arg1;
- (void)onMusicSliderProgressDidClick:(double)arg1;
- (void)onMusicSliderProgressDidSeek:(double)arg1;
- (void)onMusicSliderProgressBeginSeeking;
- (void)onMusicSliderProgressChanged:(double)arg1 isSliding:(_Bool)arg2;
- (void)didTapLyrics;
- (void)didClickCreateBtn;
- (void)didClickCommentBtn;
- (void)didClickPauseBtn;
- (void)didClickPlayBtn;
- (void)didClickShareBtn;
- (void)triggerLikeAnimationIsPrivate:(_Bool)arg1;
- (void)didClickLikeBtn;
- (void)appendCommentWithModel:(id)arg1 isNotice:(_Bool)arg2;
- (void)setShowTitleOpenAppView:(_Bool)arg1;
- (void)hideBufferingView;
- (void)showBufferingView;
- (void)updateWhenMusicPlayed;
- (void)updateWhenMusicPaused;
- (void)setCurrentAudienceCount:(unsigned long long)arg1;
- (void)updateInfoBarNickName:(id)arg1 avatarUrl:(id)arg2;
- (void)updateFinderAuthorWithDesc:(id)arg1;
- (double)getAbsorptionProgress:(double)arg1;
- (double)getSliderMusicTimeInSecondPerPx;
- (unsigned int)updateSliderProgressEnd;
- (void)updateSliderProgress:(double)arg1;
- (void)onLyricService:(id)arg1 curentLyricChangeTo:(id)arg2 timeToNext:(double)arg3 currIndex:(unsigned int)arg4;
- (void)onTopBarOpenApp;
- (void)onTopBarOpenMusicInfoHalfScreen;
- (id)requestGetAppIconUrl;
- (id)requestGetAppIconImage;
- (void)onTopBarTappedMoreButton:(id)arg1;
- (void)onTopBarTappedBack;
- (void)onClickOpenMVListBtn;
- (void)onClickCreateMV;
- (void)onClickSetStatus;
- (void)didCommitText:(id)arg1;
- (void)leaveCommentInputState;
- (void)enterCommentInputState;
- (void)InputViewFrameDidChange:(id)arg1;
- (void)keyboardHiding;
- (void)keyboardWillHide;
- (void)keyboardShowing;
- (void)keyboardWillShow;
- (double)getVisibleHeight;
- (void)onCommentLongPressed:(id)arg1;
- (void)liveCommentView:(id)arg1 didTappedDetailWithRow:(long long)arg2;
- (void)handleTapActivatedCommentBgView;
- (void)resetInputView;
- (void)resetCommentFrame;
- (id)roundButtonImageWithSize:(struct CGSize)arg1 icon:(id)arg2 offset:(struct CGPoint)arg3;
- (long long)adaptivePresentationStyleForPresentationController:(id)arg1;
- (void)onClickOpen3rdMusicApp;
- (void)layoutCollectionToolItems;
- (void)layout;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)initPostingStateView;
- (void)initCommentView;
- (void)setPushedFromType:(int)arg1;
- (void)reloadSongStatus;
- (void)reloadData;
- (void)initView;
- (void)loadView;
- (void)dealloc;
- (id)initWithMusicInfo:(id)arg1;
- (void)onDoneForwardForForwardView:(id)arg1;
- (void)OnSendAppMsgOKToContacts:(id)arg1;
- (id)getMessageWrap:(id)arg1;
- (void)scrollActionSheet:(id)arg1 didSelecteItem:(id)arg2;
- (id)genLogMusicInfo;
- (void)doAddToFavorites;
- (void)doShareToWc;
- (void)doShareToFriends;
- (id)getUpLoadTask:(id)arg1;
- (id)getCoverImageData;
- (void)open3rdAp;
- (void)openQQMusicApp;
- (void)onClickOpenMusicApp;
- (void)showMoreMenuInView:(id)arg1 justShare:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

