//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUserService.h"

#import "MMServiceProtocol-Protocol.h"

@class MMMusicViewController, NSString;

@interface MMMusicVCCacheMgr : MMUserService <MMServiceProtocol>
{
    NSString *_curCachedKey;
    MMMusicViewController *_curCachedVC;
}

+ (id)openParamsWithMusicInfo:(id)arg1;
+ (id)openParamsWithMVModel:(id)arg1;
- (void).cxx_destruct;
- (void)clearCachedVC;
- (id)popUsableViewControllerAndMayNilIfConflictWithOpenParams:(id)arg1;
- (void)commonInit;
- (void)onServiceClearData;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

