//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIHalfScreenViewController.h"

#import "MMMusicPostVideoBasePageDelegate-Protocol.h"
#import "MMMusicPostVideoTabAlbumControllerDelegate-Protocol.h"
#import "MMMusicPostVideoTabFinderControllerDelegate-Protocol.h"
#import "MMMusicPostVideoTabViewDelegate-Protocol.h"

@class MMMusicMVModel, MMMusicPostVideoTabFinderController, MMMusicPostVideoTabView, MMScrollView, MMUIButton, NSMutableArray, NSString;
@protocol MMMusicPostVideoDelegate;

@interface MMMusicPostVideoViewController : MMUIHalfScreenViewController <MMMusicPostVideoTabViewDelegate, MMMusicPostVideoTabFinderControllerDelegate, MMMusicPostVideoBasePageDelegate, MMMusicPostVideoTabAlbumControllerDelegate>
{
    MMMusicPostVideoTabView *_tabView;
    MMMusicPostVideoTabFinderController *finderVC;
    MMScrollView *_scrollView;
    NSMutableArray *_arrPageInfo;
    unsigned long long _curMode;
    long long _curTabIndex;
    struct CGPoint startLocation;
    MMUIButton *m_searchBtn;
    _Bool isInFinderSearchMode;
    MMMusicMVModel *_mvModel;
    id <MMMusicPostVideoDelegate> _postVideoDelegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <MMMusicPostVideoDelegate> postVideoDelegate; // @synthesize postVideoDelegate=_postVideoDelegate;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (void)onPanGes:(id)arg1;
- (void)onTapGes:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)doClickCloseWithNeedAnimated:(_Bool)arg1 action:(long long)arg2;
- (void)onPageSelectVideo:(id)arg1 thumbImage:(id)arg2 cellFrameInVCAcquireBlock:(CDUnknownBlockType)arg3 contentOffsetResetBlock:(CDUnknownBlockType)arg4;
- (void)handleSearchBtnTap;
- (void)handleTabSelected:(long long)arg1 tabConfig:(id)arg2 manualyTappedType:(unsigned long long)arg3 doubleClicked:(_Bool)arg4;
- (void)onSelectFinderSearchResultVideo:(id)arg1 thumbImage:(id)arg2 cellFrameInVCAcquireBlock:(CDUnknownBlockType)arg3 contentOffsetResetBlock:(CDUnknownBlockType)arg4;
- (void)onSelectFinderResultVideo:(id)arg1 thumbImage:(id)arg2 cellFrameInVCAcquireBlock:(CDUnknownBlockType)arg3 contentOffsetResetBlock:(CDUnknownBlockType)arg4;
- (void)onExitTabFinderSearchMode;
- (void)onEnterTabFinderSearchMode;
- (void)onTabAlbumVCShortVideoTaken:(id)arg1 thumbImg:(id)arg2 editVideoAttr:(id)arg3 paramModel:(id)arg4;
- (void)onSelectLocalVideoAsset:(id)arg1 thumbImage:(id)arg2 thumbFrameInVCAcquireBlock:(CDUnknownBlockType)arg3 contentOffsetResetBlock:(CDUnknownBlockType)arg4;
- (void)updateCurrEposideDuration:(double)arg1;
- (void)setCurrEposideDuration:(double)arg1;
- (void)viewDidLayoutSubviews;
- (void)initData;
- (void)initPageInfo;
- (void)initView;
- (void)setHalfModeWithoutAnim;
- (void)setEditModeWithoutAnim;
- (double)getHeightByMode:(unsigned long long)arg1;
- (void)setMode:(unsigned long long)arg1 alongside:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setMode:(unsigned long long)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithMVModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

