//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MMUIViewController, UIView;

@interface MMMusicPostVideoTabBaseController : NSObject
{
    UIView *_contentView;
    MMUIViewController *_viewController;
}

- (void).cxx_destruct;
@property __weak MMUIViewController *viewController; // @synthesize viewController=_viewController;
- (void)viewWillAppear:(_Bool)arg1;
- (void)layoutWithFrame:(struct CGRect)arg1;
- (void)updateCurrEposideDuration:(double)arg1;
- (void)setCurrEposideDuration:(double)arg1;
- (void)onSwitchToThisPage:(_Bool)arg1;
- (id)arrPanGestures;
- (id)contentView;
- (id)initWithViewController:(id)arg1;

@end

