//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWebViewPluginBase.h"

#import "MMWebHalfScreenDelegate-Protocol.h"
#import "WebTransCgiLogicDelegate-Protocol.h"
#import "WebTransHelpButtonDelegate-Protocol.h"

@class MMWebTransHelpButton, NSCache, NSString, UIView, WebTransCgiLogic;

@interface MMWebViewPlugin_handleTranslate : MMWebViewPluginBase <MMWebHalfScreenDelegate, WebTransCgiLogicDelegate, WebTransHelpButtonDelegate>
{
    _Bool _canUseWebTransAbility;
    _Bool _isInTransABtestList;
    _Bool _thisPageNeedTrans;
    _Bool _doingAnimationNow;
    _Bool _hasDidAppear;
    _Bool _firstEnterViewAnimation;
    _Bool _firstEnterView;
    _Bool _hasShownBtnOnceInThisPage;
    _Bool _hasHiddenRightButton;
    long long _transHelpButtonStatus;
    long long _status;
    WebTransCgiLogic *_cgiMgr;
    NSCache *_haveTransedTextCache;
    NSString *_brand;
    NSString *_curRandomUUID;
    UIView *_orgTitleView;
    MMWebTransHelpButton *_button;
    long long _dynamicTopNum;
    double _dynamicRatio;
}

- (void).cxx_destruct;
@property(nonatomic) double dynamicRatio; // @synthesize dynamicRatio=_dynamicRatio;
@property(nonatomic) long long dynamicTopNum; // @synthesize dynamicTopNum=_dynamicTopNum;
@property(nonatomic) _Bool hasHiddenRightButton; // @synthesize hasHiddenRightButton=_hasHiddenRightButton;
@property(retain, nonatomic) MMWebTransHelpButton *button; // @synthesize button=_button;
@property(retain, nonatomic) UIView *orgTitleView; // @synthesize orgTitleView=_orgTitleView;
@property(nonatomic) _Bool hasShownBtnOnceInThisPage; // @synthesize hasShownBtnOnceInThisPage=_hasShownBtnOnceInThisPage;
@property(nonatomic) _Bool firstEnterView; // @synthesize firstEnterView=_firstEnterView;
@property(nonatomic) _Bool firstEnterViewAnimation; // @synthesize firstEnterViewAnimation=_firstEnterViewAnimation;
@property(nonatomic) _Bool hasDidAppear; // @synthesize hasDidAppear=_hasDidAppear;
@property(nonatomic) _Bool doingAnimationNow; // @synthesize doingAnimationNow=_doingAnimationNow;
@property(copy, nonatomic) NSString *curRandomUUID; // @synthesize curRandomUUID=_curRandomUUID;
@property(copy, nonatomic) NSString *brand; // @synthesize brand=_brand;
@property(retain, nonatomic) NSCache *haveTransedTextCache; // @synthesize haveTransedTextCache=_haveTransedTextCache;
@property(retain, nonatomic) WebTransCgiLogic *cgiMgr; // @synthesize cgiMgr=_cgiMgr;
@property(nonatomic) _Bool thisPageNeedTrans; // @synthesize thisPageNeedTrans=_thisPageNeedTrans;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(nonatomic) _Bool isInTransABtestList; // @synthesize isInTransABtestList=_isInTransABtestList;
@property(nonatomic) long long transHelpButtonStatus; // @synthesize transHelpButtonStatus=_transHelpButtonStatus;
@property(nonatomic) _Bool canUseWebTransAbility; // @synthesize canUseWebTransAbility=_canUseWebTransAbility;
- (void)clickHelperTransButton;
- (void)onNoticeHalfScreenConfirmBtnClick;
- (void)bounceAfterCgiReturn:(id)arg1;
- (void)hideHelpButton;
- (id)UnzipAndSotreCache:(id)arg1;
- (id)creatJSON:(id)arg1 hashCodeArray:(id)arg2;
- (_Bool)isDoingTransNow;
- (void)handleRevertError:(id)arg1;
- (_Bool)strictCheckSampleArray:(id)arg1;
- (void)transReportWithAction:(long long)arg1 andScene:(long long)arg2 andUrl:(id)arg3;
- (void)cancelLoading;
- (void)tryCancelLoading;
- (void)replaceHTML:(id)arg1;
- (void)handleTranslateTask:(id)arg1;
- (void)prehandleAndCallJSApi;
- (void)doAfterCheckByAnotherPageWithNeedTrans:(_Bool)arg1;
- (void)doAfterCheckByBtnWithNeedTrans:(_Bool)arg1;
- (void)handleTransAction:(id)arg1;
- (void)postMessageDispatch:(id)arg1;
- (void)prehandlePostMessage:(id)arg1;
- (void)pullHalfScreenNotice;
- (_Bool)checkPullNoticeScreenBefore;
- (void)strictCheckNeedTrans:(CDUnknownBlockType)arg1;
- (void)checkNeedTrans:(CDUnknownBlockType)arg1;
- (void)checkDidTransBefore:(CDUnknownBlockType)arg1;
- (void)injectTransJs:(CDUnknownBlockType)arg1;
- (void)callJSTransApi;
- (void)callJSRevertApi;
- (void)dispatchStatusTask;
- (void)prehandleDispatchStatusTask;
- (void)animationChangeTitleView:(id)arg1 toView:(id)arg2 duration:(double)arg3;
- (void)enterDownStatus;
- (void)enterUpStatus;
- (void)titleViewCalculator;
- (_Bool)handleEvent:(unsigned long long)arg1 userInfo:(id)arg2;
- (void)doAfterClickRevertBtn;
- (void)doAfterClickTransBtnFromHelpBtn:(_Bool)arg1;
- (void)changeCgiMgr;
- (void)judgeWebTransAvailable;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

