//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MPLandingCommonSharePerformance : NSObject
{
    unsigned long long _getA8KeyStartTime;
    unsigned long long _getA8KeyEndTime;
    unsigned long long _firstScreenRenderStartTime;
    unsigned long long _firstScreenRenderEndTime;
}

@property(nonatomic) unsigned long long firstScreenRenderEndTime; // @synthesize firstScreenRenderEndTime=_firstScreenRenderEndTime;
@property(nonatomic) unsigned long long firstScreenRenderStartTime; // @synthesize firstScreenRenderStartTime=_firstScreenRenderStartTime;
@property(nonatomic) unsigned long long getA8KeyEndTime; // @synthesize getA8KeyEndTime=_getA8KeyEndTime;
@property(nonatomic) unsigned long long getA8KeyStartTime; // @synthesize getA8KeyStartTime=_getA8KeyStartTime;

@end

