//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MPLandingVideoOptionsPannelInitParams, NSMutableArray, UIView;
@protocol MPLandingVideoOptionsPannelDelegate;

@interface MPLandingVideoOptionsPanelView : NSObject
{
    MPLandingVideoOptionsPannelInitParams *m_initParams;
    id <MPLandingVideoOptionsPannelDelegate> m_delegate;
    UIView *m_containerView;
    unsigned int m_currentIndex;
    NSMutableArray *m_optionsBtnArr;
}

- (void).cxx_destruct;
- (void)destory;
- (void)setHidden:(_Bool)arg1;
- (_Bool)isShowing;
- (void)ensureContentViewNoWiderThanView:(id)arg1;
- (void)showInView:(id)arg1 origin:(struct CGPoint)arg2;
- (void)onClickToSwitchOption:(id)arg1;
- (void)setBtn:(id)arg1 selected:(_Bool)arg2;
- (id)genOptionBtn;
@property(readonly, nonatomic) double viewHeight;
@property(readonly, nonatomic) double viewWidth;
- (void)initViews;
- (id)initWithInitParams:(id)arg1 delegate:(id)arg2;

@end

