//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ReaderMessageCellView.h"

#import "IMMTemplateMsgAuthServiceExt-Protocol.h"
#import "IStrangerBrandContactHeadImageExt-Protocol.h"
#import "MMTipsViewControllerDelegate-Protocol.h"
#import "WAAppDetailInfoManagerExtension-Protocol.h"
#import "WATemplateMsgManagerExt-Protocol.h"

@class BrandTemplateMsgAuthMessageBubbleModel, MMBrandHeadImageView, MMUIButton, MMUILabel, MultiColumnReaderMessageViewModel, NSString, UIButton, UILabel, WAContactGetter;

@interface MultiColumnReaderMessageCellView : ReaderMessageCellView <WATemplateMsgManagerExt, WAAppDetailInfoManagerExtension, IMMTemplateMsgAuthServiceExt, MMTipsViewControllerDelegate, IStrangerBrandContactHeadImageExt>
{
    MMBrandHeadImageView *m_headerView;
    UILabel *m_nickNameLabel;
    MMUILabel *m_muteSloganView;
    UILabel *m_weAppMsgOpTitleLabel;
    UIButton *m_msgOpButton;
    MMUIButton *m_headerMenuButton;
    _Bool m_isMuted;
    _Bool m_needGetOrFetchRecvSwitch;
    WAContactGetter *m_contactGetter;
    BrandTemplateMsgAuthMessageBubbleModel *_messageBubbleModel;
}

- (void).cxx_destruct;
- (void)reportMessageBubbleOperationType:(unsigned long long)arg1;
- (void)fillMessageBubbleModelBottomBtnInfo:(id)arg1;
- (void)fillMessageBubbleModelBaseInfo;
- (_Bool)hasMoneyUnit:(id)arg1;
- (id)operationMenuItems;
- (void)onClickTipsBtn:(id)arg1 Index:(long long)arg2 tipTag:(long long)arg3;
- (void)updateMuteState:(_Bool)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onExpose;
- (void)getWeappContactForUsername:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)onMoreButton:(id)arg1;
- (void)layoutJumpWeappOpButton:(id)arg1 withWeappUsername:(id)arg2;
- (void)layoutHeaderMuteSloganLabelIfNeed;
- (void)layoutHeaderMenuButtonIfNeedOnCenterY:(double)arg1;
- (_Bool)isNewSubscrMsg;
- (_Bool)isOldSubscrMsg;
- (_Bool)isSubscrMsg;
- (_Bool)isNeedHeaderMuteLabel;
- (_Bool)isNeedHeaderMenuButton;
- (void)onDelete:(id)arg1;
- (void)addFavorite;
- (void)forwardMessage;
- (void)jumpFinderLiveOpWrap:(id)arg1;
- (void)jumpOpItem:(id)arg1;
- (void)jumpAdvertiseOpWrap:(id)arg1;
- (void)jumpScheduleOpWrap:(id)arg1;
- (void)jumpWeappOpWrap:(id)arg1;
- (void)onClicked;
- (void)onOPButtonClicked:(id)arg1;
- (_Bool)isForbidJumpProfileWhenClickAvatar;
- (void)onHeadImageClick;
- (void)onHeadObjectClick:(id)arg1;
- (void)onTouchUpInside;
- (void)onTouchDown;
- (double)layoutScheduleContentView:(id)arg1 originY:(double)arg2;
- (void)layoutNickNameLabel;
- (void)addCornerToContentView;
- (void)layoutContentView;
- (void)showAlertViewWhenOpenGlobalRecv:(id)arg1;
- (void)onNewMsgButtonClicked:(id)arg1;
- (void)onOldMsgButtonClicked:(id)arg1;
- (void)onUpdateScopeList:(id)arg1 forUser:(id)arg2;
- (void)onUpdateScopeGlobalRecv:(_Bool)arg1 forUser:(id)arg2;
- (void)onWeAppReceiveMsgStatusChangedSuccess:(_Bool)arg1 WeAppUserName:(id)arg2;
- (void)banListStatusChanged:(id)arg1;
- (void)newMsgUpdateScopeSwitch:(_Bool)arg1;
- (void)oldMsgUpdateGlobalSwitchOff;
- (void)newMsgFetchRecvSwitchFromSvr;
- (void)newMsgGetAndDisplayRecvSwitch;
- (void)oldMsgGetOrFetchAndDisplayRecvSwitch;
- (void)onStrangerBrandHeadImageURLChange:(id)arg1;
- (void)getAndDisplayAvatarUrl;
- (void)onAppear;
- (id)headerView;
- (void)getOrFetchRecvSwitch;
- (void)setViewModel:(id)arg1;
- (void)dealloc;
- (id)initWithViewModel:(id)arg1;
- (_Bool)canBeReused;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) MultiColumnReaderMessageViewModel *viewModel; // @dynamic viewModel;

@end

