//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMAcceptAgreementBaseViewController.h"

#import "ModifyPatSuffixLogicDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class MMTableView, MMTableViewInfo, MMTimer, MMUILabel, MMUITextField, ModifyPatSuffixLogic, NSString, UIButton;
@protocol SettingModifyPatSuffixViewControllerDelegate;

@interface SettingModifyPatSuffixViewController : MMAcceptAgreementBaseViewController <UITextFieldDelegate, ModifyPatSuffixLogicDelegate>
{
    double m_fKeyboardHeight;
    MMUITextField *m_patSuffixTextField;
    ModifyPatSuffixLogic *m_modifyPatSuffixLogic;
    MMUILabel *m_descLabel;
    MMUILabel *m_errorMsgLabel;
    MMTimer *m_timerResetErrorMsgLabelTask;
    MMUILabel *m_topTitleLabel;
    UIButton *m_acceptBtn;
    MMTableViewInfo *m_tableViewInfo;
    MMTableView *m_tableView;
    NSString *m_sessionId;
    id <SettingModifyPatSuffixViewControllerDelegate> _delegate;
    unsigned long long _scene;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long scene; // @synthesize scene=_scene;
@property(nonatomic) __weak id <SettingModifyPatSuffixViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *m_sessionId; // @synthesize m_sessionId;
- (void)setM_tableView:(id)arg1;
- (id)m_tableView;
- (void)setM_tableViewInfo:(id)arg1;
- (id)m_tableViewInfo;
@property(retain, nonatomic) UIButton *m_acceptBtn; // @synthesize m_acceptBtn;
@property(retain, nonatomic) MMUILabel *m_topTitleLabel; // @synthesize m_topTitleLabel;
- (id)navigationBarBackgroundColor;
- (void)reportAction:(unsigned long long)arg1 withErrorCode:(int)arg2;
- (void)OnModifyPatSuffixWithResult:(unsigned int)arg1 errorMsgTitle:(id)arg2 errorMsgContent:(id)arg3 errorCode:(int)arg4;
- (void)onTimerResetErrorMsgLabelTask:(id)arg1;
- (void)startTimerResetErrorMsgLabelTask;
- (void)stopTimerResetErrorMsgLabelTask;
- (void)changeDescLabelAndErrorMsgLabel:(_Bool)arg1;
- (void)handleTextFieldText:(id)arg1;
- (void)updateWordCount:(id)arg1;
- (void)onCancel;
- (_Bool)checkPatSuffixName:(id)arg1;
- (id)formatPatSuffix:(id)arg1;
- (void)didAccept;
- (void)restAcceptBtnWithKeyboardWillShow:(_Bool)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (_Bool)textFieldShouldClear:(id)arg1;
- (void)initFooterView;
- (id)genCellLeftLabel;
- (void)makePatSuffixEditCell:(id)arg1 CellInfo:(id)arg2;
- (id)getChatRoomInfoHeadView;
- (void)reloadTableViewInfo;
- (void)layoutPatSuffixEditView;
- (void)layoutAcceptBtn;
- (void)layoutTopTitleLable;
- (void)layoutTableView;
- (void)layoutNavigationBar;
- (unsigned int)getMaxPatSuffixLen;
- (id)getInitPatSuffixTextFieldText;
- (void)initData;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)initNotificationObservers;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

