//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol TAVAudioProcessingNode <NSObject>
- (void)processTimeRange:(CDStruct_e83c9415)arg1 bufferListInOut:(struct AudioBufferList *)arg2;

@optional
- (void)prepareProcess:(const struct AudioStreamBasicDescription *)arg1;
@end

