//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TAVTimeEffectProtocol-Protocol.h"

@class NSString;

@interface TAVFreezeTimeEffect : NSObject <TAVTimeEffectProtocol>
{
    CDStruct_1b6d18a9 _time;
    CDStruct_1b6d18a9 _duration;
}

@property(nonatomic) CDStruct_1b6d18a9 duration; // @synthesize duration=_duration;
@property(nonatomic) CDStruct_1b6d18a9 time; // @synthesize time=_time;
- (CDStruct_1b6d18a9)additionalDurationAfterApplyEffect;
- (id)applyTimeEffectToClips:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

