//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol TAVAudioTransition, TAVVideoTransition;

@interface TAVTransition : NSObject
{
    id <TAVVideoTransition> _videoTransition;
    id <TAVAudioTransition> _audioTransition;
    CDStruct_1b6d18a9 _duration;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id <TAVAudioTransition> audioTransition; // @synthesize audioTransition=_audioTransition;
@property(retain, nonatomic) id <TAVVideoTransition> videoTransition; // @synthesize videoTransition=_videoTransition;
@property(nonatomic) CDStruct_1b6d18a9 duration; // @synthesize duration=_duration;
- (id)initWithDuration:(CDStruct_1b6d18a9)arg1;

@end

