//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, UIImage;

@interface TextStatePublishSourceInfo : NSObject
{
    _Bool _canEditImage;
    NSArray *_jumpActions;
    NSString *_sourceId;
    NSString *_sourceActivityId;
    NSString *_sourceVerifyInfo;
    NSString *_sourceName;
    NSString *_sourceIconURL;
    NSString *_iconId;
    UIImage *_image;
    NSString *_desc;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool canEditImage; // @synthesize canEditImage=_canEditImage;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *iconId; // @synthesize iconId=_iconId;
@property(retain, nonatomic) NSString *sourceIconURL; // @synthesize sourceIconURL=_sourceIconURL;
@property(retain, nonatomic) NSString *sourceName; // @synthesize sourceName=_sourceName;
@property(retain, nonatomic) NSString *sourceVerifyInfo; // @synthesize sourceVerifyInfo=_sourceVerifyInfo;
@property(retain, nonatomic) NSString *sourceActivityId; // @synthesize sourceActivityId=_sourceActivityId;
@property(retain, nonatomic) NSString *sourceId; // @synthesize sourceId=_sourceId;
@property(retain, nonatomic) NSArray *jumpActions; // @synthesize jumpActions=_jumpActions;
- (_Bool)isValid;

@end

