//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

@class MMToastView, NSArray, UIButton;

@interface ToastDemoViewController : MMUIViewController
{
    MMToastView *_iconTextToast;
    MMToastView *_loadingToast;
    MMToastView *_textToast;
    UIButton *_toastButton;
    UIButton *_loadingButton;
    NSArray *_textArray;
    NSArray *_iconArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *iconArray; // @synthesize iconArray=_iconArray;
@property(retain, nonatomic) NSArray *textArray; // @synthesize textArray=_textArray;
@property(retain, nonatomic) UIButton *loadingButton; // @synthesize loadingButton=_loadingButton;
@property(retain, nonatomic) UIButton *toastButton; // @synthesize toastButton=_toastButton;
@property(retain, nonatomic) MMToastView *textToast; // @synthesize textToast=_textToast;
@property(retain, nonatomic) MMToastView *loadingToast; // @synthesize loadingToast=_loadingToast;
@property(retain, nonatomic) MMToastView *iconTextToast; // @synthesize iconTextToast=_iconTextToast;
- (id)pickText;
- (id)pickIcon;
- (void)onTapLoadingButton;
- (void)onTapToastButton;
- (void)onTapBarButtonItem;
- (void)layoutContent;
- (void)viewDidTransitionToNewSize;
- (void)viewDidLoad;

@end

