//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface VideoCompositionOutputConfig : NSObject
{
    long long _videoBitrate;
    long long _fps;
    long long _iFrameInterval;
    long long _audioBitrate;
    long long _audioSampleRate;
    long long _audioChannelCount;
    struct CGSize _targetSize;
}

@property(nonatomic) long long audioChannelCount; // @synthesize audioChannelCount=_audioChannelCount;
@property(nonatomic) long long audioSampleRate; // @synthesize audioSampleRate=_audioSampleRate;
@property(nonatomic) long long audioBitrate; // @synthesize audioBitrate=_audioBitrate;
@property(nonatomic) long long iFrameInterval; // @synthesize iFrameInterval=_iFrameInterval;
@property(nonatomic) long long fps; // @synthesize fps=_fps;
@property(nonatomic) long long videoBitrate; // @synthesize videoBitrate=_videoBitrate;
@property(nonatomic) struct CGSize targetSize; // @synthesize targetSize=_targetSize;
- (id)init;

@end

