//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMTableViewCell.h"

@class MMUILabel, MMWebImageView, UISwitch, WAFavMsgConfigWrap;
@protocol WAFavMsgSwitchCellDelegate;

@interface WAFavMsgSwtichCell : MMTableViewCell
{
    WAFavMsgConfigWrap *_wrap;
    MMWebImageView *_iconView;
    UISwitch *_switchButton;
    MMUILabel *_nameLabel;
    id <WAFavMsgSwitchCellDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <WAFavMsgSwitchCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) MMUILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UISwitch *switchButton; // @synthesize switchButton=_switchButton;
@property(retain, nonatomic) MMWebImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) WAFavMsgConfigWrap *wrap; // @synthesize wrap=_wrap;
- (void)onSwitch:(id)arg1;
- (void)initSwitchButton;
- (void)initIconView;
- (void)initNameLabel;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

