//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class JSContext, NSDictionary, NSString, WAOpenGLView;

@protocol WAGameContextDelegate <NSObject>
- (void)onInvokeHandler:(NSString *)arg1 eventId:(long long)arg2 param:(NSDictionary *)arg3;
- (void)onInvokeHandler:(NSDictionary *)arg1;
- (void)initWASM:(WAOpenGLView *)arg1;
- (NSString *)getPreloadAppLaunchConfig;
- (NSString *)getGameSceneTree;
- (void)onAfterGameBridgeScriptEvaluated;
- (NSString *)getAppLaunchConfigForWebView:(_Bool)arg1;
- (struct OpaqueJSValue *)getNativeGlobal;
- (JSContext *)getJSContext;
- (struct OpaqueJSContext *)getContext;

@optional
- (NSString *)processInvokeHandler:(NSString *)arg1 param:(NSString *)arg2 callbackId:(unsigned int)arg3;
@end

