//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WALiteBaseObject.h"

#import "WALiteRuntimeDelegate-Protocol.h"

@class NSMutableArray, NSString, NSURL;
@protocol WALitePackageDelegate;

@interface WALiteRuntime : WALiteBaseObject <WALiteRuntimeDelegate>
{
    unsigned int _version;
    NSString *_appId;
    unsigned long long _debugModeType;
    NSURL *_wxapkgPathUrl;
    id <WALitePackageDelegate> _walPackageDelegate;
    NSMutableArray *_walInvokeDelegateArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *walInvokeDelegateArray; // @synthesize walInvokeDelegateArray=_walInvokeDelegateArray;
@property(nonatomic) __weak id <WALitePackageDelegate> walPackageDelegate; // @synthesize walPackageDelegate=_walPackageDelegate;
@property(retain, nonatomic) NSURL *wxapkgPathUrl; // @synthesize wxapkgPathUrl=_wxapkgPathUrl;
@property(nonatomic) unsigned long long debugModeType; // @synthesize debugModeType=_debugModeType;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
- (void)evaluate:(id)arg1;
- (id)getScreenView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

