//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WALiteBaseObject.h"

@class NSMutableDictionary;

@interface WALiteInvokeBase : WALiteBaseObject
{
    unsigned int _bufferIDSequence;
    NSMutableDictionary *_dicID2Buffer;
    _Bool _useTextEncoderEncodingDataProtocol;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool useTextEncoderEncodingDataProtocol; // @synthesize useTextEncoderEncodingDataProtocol=_useTextEncoderEncodingDataProtocol;
- (id)popNativeBuffer:(id)arg1;
- (id)genBufferID;
- (id)addNativeBuffer:(id)arg1;
- (id)parseNative2SdkNativeBufferParam:(id)arg1 getError:(id *)arg2;
- (id)parseInvokeHandlerNativeBufferParam:(id)arg1 getError:(id *)arg2;
- (id)init;

@end

