//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIView, WAAppItemData, WAMainFrameDesktopView;

@protocol WAMainFrameDesktopViewDelegate <NSObject>

@optional
- (UIView *)getRightBarButton;
- (void)taskBarDidDragUpToClose:(WAMainFrameDesktopView *)arg1;
- (void)taskBarViewOnEnterForeground:(WAMainFrameDesktopView *)arg1;
- (double)getFullScreenHeight;
- (void)taskBarView:(WAMainFrameDesktopView *)arg1 notifyOnTranslationYChanged:(double)arg2;
- (void)taskBarViewDidTapOnSearchButton:(WAMainFrameDesktopView *)arg1;
- (void)taskBarViewDidTapOnFakeRightMenuButton:(WAMainFrameDesktopView *)arg1;
- (void)taskBarViewDidTapOnFoldButton:(WAMainFrameDesktopView *)arg1;
- (void)taskBarView:(WAMainFrameDesktopView *)arg1 onStarNodeShowStatusDidChangedTo:(_Bool)arg2;
- (void)taskBarView:(WAMainFrameDesktopView *)arg1 didRotateToInterfaceOrientation:(long long)arg2;
- (void)taskBarViewDidSelectStarMore:(WAMainFrameDesktopView *)arg1;
- (void)taskBarViewDidSelectTaskMore:(WAMainFrameDesktopView *)arg1;
- (void)taskBarView:(WAMainFrameDesktopView *)arg1 heightDidChangeTo:(double)arg2;
- (void)taskBarViewDidSelectMore:(WAMainFrameDesktopView *)arg1;
- (void)taskBarView:(WAMainFrameDesktopView *)arg1 didSelectStarItem:(WAAppItemData *)arg2 onPosition:(unsigned long long)arg3;
- (void)taskBarView:(WAMainFrameDesktopView *)arg1 didSelectTaskItem:(WAAppItemData *)arg2 onPosition:(unsigned long long)arg3;
- (void)taskBarViewStarDidEndDragging:(WAMainFrameDesktopView *)arg1;
- (void)taskBarViewTaskDidEndDragging:(WAMainFrameDesktopView *)arg1;
@end

