//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAReportBaseItem.h"

@class NSString;

@interface WAReportGameHTMLResourceItem : WAReportBaseItem
{
    unsigned int _sentSize;
    unsigned int _receivedSize;
    unsigned int _statusCode;
    unsigned int _visitType;
    NSString *_pageUrl;
    NSString *_url;
    NSString *_method;
    NSString *_referer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *referer; // @synthesize referer=_referer;
@property(nonatomic) unsigned int visitType; // @synthesize visitType=_visitType;
@property(nonatomic) unsigned int statusCode; // @synthesize statusCode=_statusCode;
@property(nonatomic) unsigned int receivedSize; // @synthesize receivedSize=_receivedSize;
@property(nonatomic) unsigned int sentSize; // @synthesize sentSize=_sentSize;
@property(retain, nonatomic) NSString *method; // @synthesize method=_method;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *pageUrl; // @synthesize pageUrl=_pageUrl;
- (id)reportString;
- (int)reportID;

@end

