//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

@class UIImage, WCAdLongPressView, WCAdOutstandingView;

@interface WCAdOutstandingContainerView : MMUIView
{
    UIImage *_spriteImage;
    double _duration;
    long long _spriteType;
    WCAdOutstandingView *_outstandingView;
    WCAdLongPressView *_longPressView;
    struct CGPoint _dotCenter;
    struct CGRect _pressViewFrame;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCAdLongPressView *longPressView; // @synthesize longPressView=_longPressView;
@property(retain, nonatomic) WCAdOutstandingView *outstandingView; // @synthesize outstandingView=_outstandingView;
@property(nonatomic) long long spriteType; // @synthesize spriteType=_spriteType;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic) struct CGRect pressViewFrame; // @synthesize pressViewFrame=_pressViewFrame;
@property(nonatomic) struct CGPoint dotCenter; // @synthesize dotCenter=_dotCenter;
@property(retain, nonatomic) UIImage *spriteImage; // @synthesize spriteImage=_spriteImage;
- (void)beginOutstandingAnimation;
- (void)generateSubviews;
- (id)initWithFrame:(struct CGRect)arg1 dotCenter:(struct CGPoint)arg2 pressViewFrame:(struct CGRect)arg3 duration:(double)arg4 spriteType:(long long)arg5;

@end

