//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCAdvertiseUIUtil : NSObject
{
}

+ (unsigned long long)fetchMonitoringTypeWithTid:(id)arg1 cardView:(id)arg2 requestType:(long long)arg3;
+ (void)requestMonitoringTypeForTid:(id)arg1 cardView:(id)arg2 requestType:(long long)arg3 completionHandler:(CDUnknownBlockType)arg4;
+ (struct CGRect)fetchFirstSectionFrameFromTableView:(id)arg1;
+ (struct CGRect)fetchHeaderFrameFromTableView:(id)arg1;
+ (struct CGRect)fetchCellFrameFromTableView:(id)arg1 forCell:(id)arg2;
+ (id)findCellForSubView:(id)arg1;
+ (id)findTableViewForSubView:(id)arg1;
+ (id)fetchContainerTableViewForSubView:(id)arg1 destFrame:(struct CGRect *)arg2;

@end

