//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ILinkEventExt-Protocol.h"

@class NSString, RichTextView, UIColor, UIImageView, UITapGestureRecognizer;

@interface WCAgreementCheckBox : UIView <ILinkEventExt>
{
    _Bool _selected;
    CDUnknownBlockType _selectBlock;
    CDUnknownBlockType _tapLinkBlock;
    UIColor *_iconColor;
    NSString *_agreement;
    UIColor *_textColor;
    UIImageView *_iconView;
    RichTextView *_richTextView;
    UITapGestureRecognizer *_tapGesture;
    struct UIEdgeInsets _expandHitInsets;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) RichTextView *richTextView; // @synthesize richTextView=_richTextView;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) struct UIEdgeInsets expandHitInsets; // @synthesize expandHitInsets=_expandHitInsets;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) NSString *agreement; // @synthesize agreement=_agreement;
@property(retain, nonatomic) UIColor *iconColor; // @synthesize iconColor=_iconColor;
@property(copy, nonatomic) CDUnknownBlockType tapLinkBlock; // @synthesize tapLinkBlock=_tapLinkBlock;
@property(copy, nonatomic) CDUnknownBlockType selectBlock; // @synthesize selectBlock=_selectBlock;
@property(nonatomic, getter=isSelected) _Bool selected; // @synthesize selected=_selected;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onTextClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onTapCheckBox:(id)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)callSelectBlockIfNeeded;
- (double)richTextViewMaxWidthFromWidth:(double)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)initGestures;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

