//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FinderLiveNoticeInfo, FinderLiveTagInfo, NSArray, NSDate, NSMutableArray, WCFinderDataItem;

@interface WCFinderCreateLiveViewModel : NSObject
{
    _Bool _isCreateLivePrepareChecked;
    unsigned int _userFlag;
    unsigned int _liveGlobalFlag;
    FinderLiveNoticeInfo *_liveNoticeInfo;
    WCFinderDataItem *_recoverDataItem;
    NSArray *_allTagInfos;
    FinderLiveTagInfo *_currentTagInfo;
    NSArray *_visibilityFileList;
    NSMutableArray *_waittingBlocks;
    NSDate *_bookingTime;
    NSMutableArray *_dayArrs;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *dayArrs; // @synthesize dayArrs=_dayArrs;
@property(retain, nonatomic) NSDate *bookingTime; // @synthesize bookingTime=_bookingTime;
@property(retain, nonatomic) NSMutableArray *waittingBlocks; // @synthesize waittingBlocks=_waittingBlocks;
@property(nonatomic) _Bool isCreateLivePrepareChecked; // @synthesize isCreateLivePrepareChecked=_isCreateLivePrepareChecked;
@property(retain, nonatomic) NSArray *visibilityFileList; // @synthesize visibilityFileList=_visibilityFileList;
@property(retain, nonatomic) FinderLiveTagInfo *currentTagInfo; // @synthesize currentTagInfo=_currentTagInfo;
@property(retain, nonatomic) NSArray *allTagInfos; // @synthesize allTagInfos=_allTagInfos;
@property(nonatomic) unsigned int liveGlobalFlag; // @synthesize liveGlobalFlag=_liveGlobalFlag;
@property(nonatomic) unsigned int userFlag; // @synthesize userFlag=_userFlag;
@property(retain, nonatomic) WCFinderDataItem *recoverDataItem; // @synthesize recoverDataItem=_recoverDataItem;
@property(retain, nonatomic) FinderLiveNoticeInfo *liveNoticeInfo; // @synthesize liveNoticeInfo=_liveNoticeInfo;
- (long long)getNearestIndexWithTarggetItem:(id)arg1 itemList:(id)arg2;
- (id)getMinuteArrWithDayComponent:(long long)arg1 hourComponent:(long long)arg2;
- (id)getMinuteDataWithDayComponent:(long long)arg1 hourComponent:(long long)arg2;
- (id)getHourDataWithDayComponent:(long long)arg1;
- (id)dayComponent;
- (void)genDayComponentIfNeed;
- (id)getDatePickerData;
- (id)getHourArrWithDayComponent:(long long)arg1;
- (id)setBookingTimeWithSelectedDayComponent:(long long)arg1 hourComponent:(long long)arg2 minuteComponent:(long long)arg3;
- (void)createLiveNotice:(CDUnknownBlockType)arg1;
- (void)fetchCreateLiveNoticeInfo:(CDUnknownBlockType)arg1 complete:(CDUnknownBlockType)arg2;
- (void)invokeWaittingNoticeInfoBlocks;
- (void)checkLiveNoticeInfo;
- (id)init;

@end

