//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FinderStreamCardActionInfo, FinderStreamTxtCard, NSString, WCFinderMoreContentColumnsView;

@protocol WCFinderMoreContentColumnsViewDelegate <NSObject>

@optional
- (void)moreContentColumnsTableViewCell:(WCFinderMoreContentColumnsView *)arg1 clickedLinkInfo:(FinderStreamCardActionInfo *)arg2 withTitle:(NSString *)arg3 forEndLinkCard:(FinderStreamTxtCard *)arg4;
@end

