//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class MMUIButton, UIView;
@protocol WCFinderNearbyLiveNoMoreFooterViewCellDelegate;

@interface WCFinderNearbyLiveNoMoreFooterViewCell : UICollectionViewCell
{
    id <WCFinderNearbyLiveNoMoreFooterViewCellDelegate> _delegate;
    UIView *_tipsView;
    MMUIButton *_seeRecommendButton;
}

+ (double)cellHeight;
- (void).cxx_destruct;
@property(retain, nonatomic) MMUIButton *seeRecommendButton; // @synthesize seeRecommendButton=_seeRecommendButton;
@property(retain, nonatomic) UIView *tipsView; // @synthesize tipsView=_tipsView;
@property(nonatomic) __weak id <WCFinderNearbyLiveNoMoreFooterViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onSeeRecommendButtonClick;
- (id)initWithFrame:(struct CGRect)arg1;

@end

