//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "MMScrollActionSheetDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"
#import "WCFinderCommentDetailViewControllerDelegate-Protocol.h"
#import "WCFinderContentTableViewCellDelegate-Protocol.h"
#import "WCFinderFeedCommentTableViewCellDelegate-Protocol.h"
#import "WCFinderFeedFriendsLikeListViewControllerDelegate-Protocol.h"
#import "WCFinderFriendLikeTableViewCellDelegate-Protocol.h"
#import "WCFinderFullMultiMediaTableViewCellDelegate-Protocol.h"
#import "WCFinderInduceCommentTableViewCellDelegate-Protocol.h"
#import "WCFinderLiveNoticeTableViewCellDelegate-Protocol.h"
#import "WCFinderMultiMediaTableViewCellDelegate-Protocol.h"
#import "WCFinderPostingCommentExt-Protocol.h"
#import "WCFinderRefreshTableFooterViewDelegate-Protocol.h"
#import "WCFinderToolbarTableViewCellDelegate-Protocol.h"
#import "WCFinderVideoPlayerExt-Protocol.h"
#import "WCGeneralMonitorDelegate-Protocol.h"

@class MMUIButton, NSIndexPath, NSMutableDictionary, NSString, UIImageView, UILabel, UIMonitorTableView, UIViewController, WCActionSheet, WCFinderAnimationLoadingView, WCFinderRefreshTableFooterView;
@protocol WCFinderCommentBaseViewProtocol, WCFinderFeedListViewDataSource, WCFinderFeedListViewDelegate;

@interface WCFinderFeedListView : UIView <UITableViewDelegate, UITableViewDataSource, WCFinderRefreshTableFooterViewDelegate, MMScrollActionSheetDelegate, WCActionSheetDelegate, WCFinderFriendLikeTableViewCellDelegate, WCFinderFeedFriendsLikeListViewControllerDelegate, WCFinderMultiMediaTableViewCellDelegate, WCFinderToolbarTableViewCellDelegate, WCFinderPostingCommentExt, WCFinderContentTableViewCellDelegate, WCFinderVideoPlayerExt, WCFinderCommentDetailViewControllerDelegate, WCGeneralMonitorDelegate, WCFinderInduceCommentTableViewCellDelegate, WCFinderFeedCommentTableViewCellDelegate, WCFinderLiveNoticeTableViewCellDelegate, WCFinderFullMultiMediaTableViewCellDelegate>
{
    _Bool _isSilencePlay;
    _Bool _needsResumeTimelineVideo;
    _Bool _disableVideoAutoPlay;
    id <WCFinderFeedListViewDataSource> _dataSource;
    id <WCFinderFeedListViewDelegate> _delegate;
    UIMonitorTableView *_tableView;
    NSString *_retryTipsTitle;
    NSString *_noDataTipsTitle;
    NSString *_footerNoMoreTips;
    NSString *_latestAutoplayVideoTid;
    WCFinderRefreshTableFooterView *_footerView;
    WCFinderAnimationLoadingView *_loadingView;
    UIView *_loadingViewContainer;
    UILabel *_stateTipsLabel;
    UIImageView *_retryImageView;
    NSString *_currentFocusTid;
    NSIndexPath *_currentFocusIndexPath;
    NSMutableDictionary *_exposureDict;
    UIViewController<WCFinderCommentBaseViewProtocol> *_lastCommentVC;
    WCActionSheet *_forwardActionSheet;
    unsigned long long _createTimestamp;
    unsigned long long _uiStyle;
    MMUIButton *_landScapeButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMUIButton *landScapeButton; // @synthesize landScapeButton=_landScapeButton;
@property(nonatomic) unsigned long long uiStyle; // @synthesize uiStyle=_uiStyle;
@property(nonatomic) _Bool disableVideoAutoPlay; // @synthesize disableVideoAutoPlay=_disableVideoAutoPlay;
@property(nonatomic) _Bool needsResumeTimelineVideo; // @synthesize needsResumeTimelineVideo=_needsResumeTimelineVideo;
@property(nonatomic) unsigned long long createTimestamp; // @synthesize createTimestamp=_createTimestamp;
@property(retain, nonatomic) WCActionSheet *forwardActionSheet; // @synthesize forwardActionSheet=_forwardActionSheet;
@property(retain, nonatomic) UIViewController<WCFinderCommentBaseViewProtocol> *lastCommentVC; // @synthesize lastCommentVC=_lastCommentVC;
@property(retain, nonatomic) NSMutableDictionary *exposureDict; // @synthesize exposureDict=_exposureDict;
@property(nonatomic) _Bool isSilencePlay; // @synthesize isSilencePlay=_isSilencePlay;
@property(retain, nonatomic) NSIndexPath *currentFocusIndexPath; // @synthesize currentFocusIndexPath=_currentFocusIndexPath;
@property(retain, nonatomic) NSString *currentFocusTid; // @synthesize currentFocusTid=_currentFocusTid;
@property(retain, nonatomic) UIImageView *retryImageView; // @synthesize retryImageView=_retryImageView;
@property(retain, nonatomic) UILabel *stateTipsLabel; // @synthesize stateTipsLabel=_stateTipsLabel;
@property(retain, nonatomic) UIView *loadingViewContainer; // @synthesize loadingViewContainer=_loadingViewContainer;
@property(retain, nonatomic) WCFinderAnimationLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) WCFinderRefreshTableFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) NSString *latestAutoplayVideoTid; // @synthesize latestAutoplayVideoTid=_latestAutoplayVideoTid;
@property(copy, nonatomic) NSString *footerNoMoreTips; // @synthesize footerNoMoreTips=_footerNoMoreTips;
@property(copy, nonatomic) NSString *noDataTipsTitle; // @synthesize noDataTipsTitle=_noDataTipsTitle;
@property(copy, nonatomic) NSString *retryTipsTitle; // @synthesize retryTipsTitle=_retryTipsTitle;
@property(retain, nonatomic) UIMonitorTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <WCFinderFeedListViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <WCFinderFeedListViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void)liveNoticeUserame:(id)arg1 clickLiveNoticeInfo:(id)arg2;
- (void)liveNoticeTableViewCell:(id)arg1 updateLiveNoticeInfo:(id)arg2;
- (void)onItemsExposed:(id)arg1 withOldItems:(id)arg2;
- (void)onClickInduceCommnetView:(id)arg1 forFeedVM:(id)arg2 identifyType:(unsigned long long)arg3 commentPostScene:(long long)arg4;
- (void)clickAuthorCommentAvatarWhenInProfile:(id)arg1;
- (void)clickCommentNickname:(id)arg1 username:(id)arg2 contact:(id)arg3 isWeChatFriend:(_Bool)arg4 dataItem:(id)arg5;
- (void)updateCurrentVideoThumb;
- (void)resetCurrentVideoThumb;
- (void)needsUpdateCurrentVideo:(_Bool)arg1;
- (void)onFinderVideoPlayerStartPlay;
- (void)onFinderDataItemPostingCommentFailBySpecialError:(id)arg1 errorCode:(int)arg2 errorMsg:(id)arg3;
- (void)reportForwordWith:(id)arg1;
- (void)scrollActionSheetDidTapTransparent:(id)arg1;
- (void)scrollActionSheetDidCancel:(id)arg1;
- (void)deleteFeedWithContentVM:(id)arg1;
- (void)didClickToolbarDeleteAction:(id)arg1;
- (void)scrollActionSheet:(id)arg1 didSelecteItem:(id)arg2;
- (void)onClickCommentUserName:(id)arg1 contentVM:(id)arg2;
- (void)finderCommentCell:(id)arg1 didClickCommentLikeWithcomment:(id)arg2 contentVM:(id)arg3;
- (void)onRefreshMediaUI:(id)arg1 needAnimation:(_Bool)arg2;
- (void)onRefreshCommentUI:(id)arg1 needAnimation:(_Bool)arg2;
- (void)onClickCommentAction:(id)arg1 contentVM:(id)arg2;
- (void)showCommentActionSheetWithComment:(id)arg1 contentVM:(id)arg2;
- (void)finderTLFeedPrivateCell:(id)arg1 stateChange:(_Bool)arg2;
- (void)onClickContentMentionAction:(id)arg1 nickname:(id)arg2 dataItem:(id)arg3;
- (void)onClickContentTopicAction:(id)arg1 dataItem:(id)arg2;
- (void)onClickContentExtReadingAction:(id)arg1;
- (void)onContentTableViewCell:(id)arg1 longPressContentAction:(id)arg2 rect:(struct CGRect)arg3;
- (void)onClickContentReadMoreAction:(id)arg1 isExpand:(_Bool)arg2;
- (void)onRefreshContentCellUI:(id)arg1;
- (void)onClickEventEntry:(id)arg1;
- (void)onClickLongEntry:(id)arg1;
- (void)onClickContentUsernameAction:(id)arg1;
- (void)clickContentPOIAction:(id)arg1;
- (void)onRefreshToolbarUI:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onClickToolbarCancelUploading:(id)arg1;
- (void)onClickToolbarRetryUploading:(id)arg1;
- (void)onClickToolbarFeedAllLikeAction:(id)arg1;
- (void)onClickToolbarShareAction:(id)arg1;
- (void)onClickToolbarCollectionAction:(id)arg1;
- (void)showCommentListWithContentVM:(id)arg1 shouldEnterKeyBoard:(_Bool)arg2 refCommentID:(unsigned long long)arg3 commentAction:(unsigned long long)arg4;
- (void)onClickViewAllCommentAction:(id)arg1 isActiveInput:(_Bool)arg2 isFromCommentButton:(_Bool)arg3;
- (void)onClickViewAllCommentAction:(id)arg1 isActiveInput:(_Bool)arg2;
- (void)onClickRealNameAction;
- (void)onClickToolbarLikeAction:(id)arg1 isPrivateLike:(_Bool)arg2;
- (void)onShowLongVideoBubble:(id)arg1;
- (void)tryShowInduceCommentForCurrentPhoto:(id)arg1 preContentVM:(id)arg2;
- (void)onVideoPlayWithReport:(id)arg1 mediaWrap:(id)arg2 currentIndex:(unsigned long long)arg3 forContentVM:(id)arg4;
- (void)onImageMediaTableViewCellPlayPauseWillChange:(_Bool)arg1;
- (_Bool)onMultiMediaCellIsInHotSpots:(id)arg1;
- (_Bool)finderMulitMediaTableViewCellCanProgressGestureWithTid:(id)arg1;
- (void)onHeaderFollowBtnClickAction:(id)arg1 followButton:(id)arg2;
- (void)onHeaderMoreClickAction:(id)arg1;
- (void)onFeedVideoStopPlay:(id)arg1 tid:(id)arg2;
- (void)contentMediaDidEndPlay:(unsigned long long)arg1 contentVM:(id)arg2 finderPlayerReport:(id)arg3;
- (void)retryLoadingVideoResource:(_Bool)arg1;
- (void)photoContentPageTurning:(id)arg1 currentPage:(unsigned long long)arg2 lastPage:(unsigned long long)arg3;
- (void)showSpamTipsWithString:(id)arg1;
- (void)likeFeedContentVMAction:(id)arg1 isPrivateLike:(_Bool)arg2 touchPoint:(struct CGPoint)arg3;
- (void)likeFeedContentVMAction:(id)arg1 isPrivateLike:(_Bool)arg2;
- (void)didFeedDoubleLikeAction:(id)arg1 touchPoint:(struct CGPoint)arg2;
- (void)didFeedDoubleLikeAction:(id)arg1;
- (void)onFeedCellDidClickLiveNowView:(id)arg1 contentVM:(id)arg2;
- (void)onFeedCellDidClickHeaderView:(id)arg1 contentVM:(id)arg2;
- (void)onLiveFeedDidTap:(id)arg1;
- (void)onClickLikedListContactWithWith:(id)arg1 LikeInfo:(id)arg2 ObjectID:(id)arg3;
- (void)onClickLikedListClickMoreActionWith:(id)arg1 ObjectId:(id)arg2;
- (void)onRefreshFriendUI:(id)arg1;
- (void)onClickFollowLikeBtnWithContentVM:(id)arg1;
- (void)onClickFriendLikeListDetail:(id)arg1;
- (_Bool)isEnableTriggerRefreshAtScroll:(id)arg1;
- (void)finderFooterDidTriggerRefresh:(id)arg1;
- (void)didClickFooterRefreshRetry:(id)arg1;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfContnetVMS;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)exposureTime:(id)arg1 index:(long long)arg2;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)onLandScapeBtnClick:(id)arg1;
- (_Bool)_isAuthorViewer;
- (_Bool)_shouldHandleJumpProfileUsername:(id)arg1 contentVM:(id)arg2;
- (id)_tableViewParamModelWithContentVM:(id)arg1;
@property(readonly, nonatomic) _Bool isFullScreenList;
- (void)_preloadVideoItems:(id)arg1;
- (void)_stopPreloadVideoItem:(id)arg1;
- (void)stopPreloadWithIndexPath:(id)arg1;
- (_Bool)isDisableVideoAutoPlay;
- (unsigned long long)refreshTime;
- (unsigned long long)feedViewControllerScene;
- (long long)sectionOfTid:(id)arg1;
- (id)currentVC;
- (id)_contentVMOfTid:(id)arg1;
- (id)_contentVMAtSection:(long long)arg1;
- (_Bool)_isCustomAtSection:(long long)arg1;
- (void)scrollToNextVisibleCellAfterLoading:(struct CGRect)arg1;
- (void)reportCurrentTidStats;
- (void)currentFocusIndexPathWillChanged;
- (void)checkCurrentFocusIndexPath;
- (void)autoPlayVideo;
- (void)_adjustHotAreaAndAutoPlay;
- (void)adjustHotAreaAndAutoPlay;
- (void)preloadVideoItemsWithCurrentIndexPath:(id)arg1;
- (void)preloadVideoItems;
- (void)stopCurrentMedia;
- (void)showInduceCommentForContentVM:(id)arg1 cancelIndeuceCommentForContentVM:(id)arg2;
- (void)showLongVideoBubble:(id)arg1;
- (void)reloadInduceCommentCell:(id)arg1;
- (void)doShowInduceCommentForCurrentPhoto:(id)arg1;
- (void)onTimelineViewEnterBackground:(id)arg1;
- (void)onTimelineViewEnterForeground:(id)arg1;
- (void)setFeedListViewUserInteractionEnabled:(_Bool)arg1;
- (void)removeObserverForForegroundNotification;
- (void)addObserverForForegroundNotification;
- (unsigned long long)supportedInterfaceOrientationsWithVCMask:(unsigned long long)arg1;
- (void)finderReloadRowsAtIndexPaths:(id)arg1 withRowAnimation:(long long)arg2;
- (void)scrollToContentVM:(id)arg1 animated:(_Bool)arg2;
- (void)finderFeedListViewStopCurrentFeedPlay;
- (void)deleteContentVMWithContentVM:(id)arg1 section:(long long)arg2;
- (void)appendContentVMFromSectionIndex:(long long)arg1 toSectionIndex:(long long)arg2;
- (void)finderFeedListDidAppear;
- (void)finderFeedListDidDisappear;
- (void)finderFeedListWillDisappear;
- (void)finderFeedListWillAppear;
- (void)showErrorStatus;
- (void)layoutSubviews;
- (void)reloadRowsAtIndexPaths:(id)arg1 withRowAnimation:(long long)arg2;
- (void)dealloc;
- (void)resetFooterViewNormal;
- (void)processLastVideoHunger;
- (void)resetFooterView:(_Bool)arg1;
- (void)showNoMoreData;
- (void)resetFooterState;
- (void)reloadData;
- (void)resetLoadingStateWithAnimation:(_Bool)arg1;
- (void)startLoadingState;
- (void)stateRetryGestureAction:(id)arg1;
- (void)resetStateTipsLabelWithRetry:(_Bool)arg1;
- (void)setupLandscapeButton;
- (void)setupTipsLabel;
- (void)setupTopLoading;
- (void)setUpFooterView;
- (void)configureTableView;
- (id)initWithFrame:(struct CGRect)arg1 style:(unsigned long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

