//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WCFinderNewsTopicFeedListViewModel;

@protocol WCFinderNewsTopicFeedListViewModelDelegate <NSObject>

@optional
- (void)newsTopicFeedListViewModelTopicSubTitleChanged:(WCFinderNewsTopicFeedListViewModel *)arg1;
- (void)newsTopicFeedListViewModelNoMoreData:(WCFinderNewsTopicFeedListViewModel *)arg1;
- (void)newsTopicFeedListViewModelFetchDataFailed:(WCFinderNewsTopicFeedListViewModel *)arg1;
- (void)newsTopicFeedListViewModel:(WCFinderNewsTopicFeedListViewModel *)arg1 appendDataItemFromIdx:(long long)arg2 toIdx:(long long)arg3;
- (void)newsTopicFeedListViewModelFollowStateChanged:(WCFinderNewsTopicFeedListViewModel *)arg1;
@end

