//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCFinderCreateUserViewControllerDelegate-Protocol.h"
#import "WCFinderTipsViewControllerDelegate-Protocol.h"
#import "WCFinderUserPrepareCgiDelegate-Protocol.h"

@class FinderUserPrepareResponse, NSString, WCFinderDataItem, WCFinderReportPostStateModel;
@protocol WCFinderCreateCoordinatorDelegate;

@interface WCFinderCreateCoordinator : NSObject <WCFinderUserPrepareCgiDelegate, WCFinderCreateUserViewControllerDelegate, WCFinderTipsViewControllerDelegate>
{
    long long _scene;
    unsigned long long _createScene;
    FinderUserPrepareResponse *_userPrepare;
    WCFinderDataItem *_dataItem;
    WCFinderReportPostStateModel *_postStateModel;
    id <WCFinderCreateCoordinatorDelegate> _delegate;
}

+ (long long)convertCreateSceneFrom:(long long)arg1;
+ (_Bool)shouldStartCreateUser;
- (void).cxx_destruct;
@property(nonatomic) __weak id <WCFinderCreateCoordinatorDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WCFinderReportPostStateModel *postStateModel; // @synthesize postStateModel=_postStateModel;
@property(retain, nonatomic) WCFinderDataItem *dataItem; // @synthesize dataItem=_dataItem;
@property(retain, nonatomic) FinderUserPrepareResponse *userPrepare; // @synthesize userPrepare=_userPrepare;
@property(nonatomic) unsigned long long createScene; // @synthesize createScene=_createScene;
@property(nonatomic) long long scene; // @synthesize scene=_scene;
- (void)userPrepareCgi:(id)arg1 didFailWithError:(id)arg2;
- (void)userPrepareCgi:(id)arg1 didGetResponse:(id)arg2;
- (void)reportDataVoluntaryExit:(unsigned long long)arg1;
- (void)tipsVCClickCancelButton:(id)arg1;
- (void)tipsVCClickConfirmButton:(id)arg1;
- (void)createUserFailed;
- (void)cancelCreateUser;
- (void)createUserFinished;
- (void)OnRealnameVerfitySuccessNotification:(id)arg1;
- (void)showCreateAccountTips;
- (void)showRealNameTips;
- (void)dealloc;
- (id)init;
- (void)startRealName;
- (void)startCreateUser;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

