//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"
#import "WCTColumnCoding-Protocol.h"

@class NSString, WCFinderVideoAttachment;

@interface WCFinderAttachment : NSObject <WCTColumnCoding, PBCoding>
{
    int type;
    WCFinderVideoAttachment *videoAttachment;
}

+ (unsigned long long)columnTypeForWCDB;
+ (id)unarchiveWithWCTValue:(id)arg1;
+ (void)initialize;
+ (void)PBArrayAdd_videoAttachment;
+ (void)PBArrayAdd_type;
- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderVideoAttachment *videoAttachment; // @synthesize videoAttachment;
@property(nonatomic) int type; // @synthesize type;
- (id)initWithFinderAttachment:(id)arg1;
- (id)archivedWCTValue;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

