//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "ILinkEventExt-Protocol.h"
#import "WCFinderHeadImageViewDelegate-Protocol.h"

@class MMWebImageView, NSLayoutConstraint, NSString, RichTextView, UIImageView, UILabel, UIView, WCFinderHeadImageView, WCFinderNotifyCenterCellViewModel;
@protocol WCFinderNotifyCenterCellDelegate;

@interface WCFinderNotifyCenterCell : UITableViewCell <WCFinderHeadImageViewDelegate, ILinkEventExt>
{
    id <WCFinderNotifyCenterCellDelegate> _delegate;
    WCFinderHeadImageView *_headImageView;
    MMWebImageView *_thumbImageView;
    RichTextView *_titleView;
    RichTextView *_contentTextView;
    RichTextView *_refContentTextView;
    UILabel *_timestampLabel;
    UIImageView *_interactImageView;
    UIView *_lineView;
    UILabel *_descriptionLabel;
    UIView *_refContentView;
    NSLayoutConstraint *_titleWidthConstraint;
    NSLayoutConstraint *_refContentBottomConstraint;
    NSLayoutConstraint *_refContentHeightConstraint;
    UIView *_pureTextBackGroundView;
    RichTextView *_pureTextView;
    UIView *_refContentLineView;
    WCFinderNotifyCenterCellViewModel *_viewModel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderNotifyCenterCellViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak UIView *refContentLineView; // @synthesize refContentLineView=_refContentLineView;
@property(nonatomic) __weak RichTextView *pureTextView; // @synthesize pureTextView=_pureTextView;
@property(nonatomic) __weak UIView *pureTextBackGroundView; // @synthesize pureTextBackGroundView=_pureTextBackGroundView;
@property(retain, nonatomic) NSLayoutConstraint *refContentHeightConstraint; // @synthesize refContentHeightConstraint=_refContentHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *refContentBottomConstraint; // @synthesize refContentBottomConstraint=_refContentBottomConstraint;
@property(retain, nonatomic) NSLayoutConstraint *titleWidthConstraint; // @synthesize titleWidthConstraint=_titleWidthConstraint;
@property(nonatomic) __weak UIView *refContentView; // @synthesize refContentView=_refContentView;
@property(nonatomic) __weak UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(nonatomic) __weak UIView *lineView; // @synthesize lineView=_lineView;
@property(nonatomic) __weak UIImageView *interactImageView; // @synthesize interactImageView=_interactImageView;
@property(nonatomic) __weak UILabel *timestampLabel; // @synthesize timestampLabel=_timestampLabel;
@property(nonatomic) __weak RichTextView *refContentTextView; // @synthesize refContentTextView=_refContentTextView;
@property(nonatomic) __weak RichTextView *contentTextView; // @synthesize contentTextView=_contentTextView;
@property(nonatomic) __weak RichTextView *titleView; // @synthesize titleView=_titleView;
@property(nonatomic) __weak MMWebImageView *thumbImageView; // @synthesize thumbImageView=_thumbImageView;
@property(nonatomic) __weak WCFinderHeadImageView *headImageView; // @synthesize headImageView=_headImageView;
@property(nonatomic) __weak id <WCFinderNotifyCenterCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onTapThumbImageView;
- (void)onTextClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)finderHeadImageViewDidClick:(id)arg1;
- (void)setUpViewLayout;
- (void)setupRefContentView;
- (void)setUpPureTextView;
- (void)setUpUI;
- (void)updateNofiyCenterCellWithViewModel:(id)arg1 width:(double)arg2;
- (void)prepareForReuse;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

