//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewHeaderFooterView.h>

@class NSMutableArray, NSString, WCFinderContentLoadMoreCardView, WCFinderMoreContentColumnsView;
@protocol WCFinderContentColumnEndViewDelegate;

@interface WCFinderContentColumnEndView : UITableViewHeaderFooterView
{
    id <WCFinderContentColumnEndViewDelegate> _delegate;
    WCFinderContentLoadMoreCardView *_moreCardView;
    WCFinderMoreContentColumnsView *_contentColumnView;
    NSMutableArray *_displayViews;
    NSString *_moreHotLabelTitle;
}

+ (_Bool)shouldDisplayMoreCardView:(long long)arg1;
+ (double)heightEndLinkCard:(id)arg1 moreCardType:(long long)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *moreHotLabelTitle; // @synthesize moreHotLabelTitle=_moreHotLabelTitle;
@property(retain, nonatomic) NSMutableArray *displayViews; // @synthesize displayViews=_displayViews;
@property(retain, nonatomic) WCFinderMoreContentColumnsView *contentColumnView; // @synthesize contentColumnView=_contentColumnView;
@property(retain, nonatomic) WCFinderContentLoadMoreCardView *moreCardView; // @synthesize moreCardView=_moreCardView;
@property(nonatomic) __weak id <WCFinderContentColumnEndViewDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)isView:(id)arg1 displayInScrollView:(id)arg2;
- (void)checkViewExpose:(id)arg1 scrollView:(id)arg2 notifyBlock:(CDUnknownBlockType)arg3 undisplayBlock:(CDUnknownBlockType)arg4;
- (void)onScrollViewDidScroll:(id)arg1;
- (void)onTapMoreCard;
- (void)layoutSubviews;
- (void)setupContentColumnView:(id)arg1;
- (void)setupMoreCardView:(long long)arg1 isFetching:(_Bool)arg2;
- (void)updateWithEndLinkCard:(id)arg1 moreCardType:(long long)arg2 isFetching:(_Bool)arg3 moreHotLabelTitle:(id)arg4;

@end

