//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MMBaseSessionStorage, NSString, WCFinderMsgSessionInfo;

@interface WCFinderMsgSessionInfoStorage : NSObject
{
    _Bool _showingGreetMsgSessionList;
    _Bool _needUpdateGreetMsgSession;
    MMBaseSessionStorage *_sessionStorage;
    MMBaseSessionStorage *_greetMsgSessionStorage;
    NSString *_logName;
    WCFinderMsgSessionInfo *_greetMsgSessionInfo;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool needUpdateGreetMsgSession; // @synthesize needUpdateGreetMsgSession=_needUpdateGreetMsgSession;
@property(retain, nonatomic) WCFinderMsgSessionInfo *greetMsgSessionInfo; // @synthesize greetMsgSessionInfo=_greetMsgSessionInfo;
@property(retain, nonatomic) NSString *logName; // @synthesize logName=_logName;
@property(nonatomic) _Bool showingGreetMsgSessionList; // @synthesize showingGreetMsgSessionList=_showingGreetMsgSessionList;
@property(retain, nonatomic) MMBaseSessionStorage *greetMsgSessionStorage; // @synthesize greetMsgSessionStorage=_greetMsgSessionStorage;
@property(retain, nonatomic) MMBaseSessionStorage *sessionStorage; // @synthesize sessionStorage=_sessionStorage;
- (void)updateGreetMsgSessionWithSessionInfo:(id)arg1;
- (void)updateGreetMsgSessionInfo;
- (_Bool)updateGreetMsgSessionUnreadStatus:(_Bool)arg1;
- (void)makeSureLoadGreetMsgSession;
- (_Bool)hasUnreadInGreetSessionList;
- (_Bool)isGreetMsgSessionUnread;
- (_Bool)updateLastMsgWithSessionId:(id)arg1 lastMsg:(id)arg2;
- (id)clearUnreadCountWithSessionId:(id)arg1;
- (_Bool)clearAllTempSessionsInGreetMsgSessionList;
- (id)unreadCountNumber;
- (id)sessionInfoWithSessionId:(id)arg1;
- (void)findSessionWithSessionId:(id)arg1 result:(id)arg2;
- (id)findSessionWithSessionId:(id)arg1;
- (_Bool)deleteSessionWithSessionId:(id)arg1;
- (void)addOrUpdateSessionWithSessionId:(id)arg1 wrapMsg:(id)arg2 result:(id)arg3 updateBlock:(CDUnknownBlockType)arg4;
- (void)addGreetMsgSessionWithSessionType:(id)arg1 greetSessionId:(id)arg2 unreadStatus:(_Bool)arg3 baseStorageDelagate:(id)arg4;
- (id)initWithNormalSessionType:(id)arg1 logName:(id)arg2 baseStorageDelagate:(id)arg3;

@end

