//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FinderTopicBgmInfo, NSData, NSMutableArray, NSString, UIViewController, WCFinderTopicInfo;
@protocol WCFinderEventPageViewModelDelegate, WCFinderFeedBaseViewControllerProtocol;

@interface WCFinderEventPageViewModel : NSObject
{
    _Bool _continueFlag;
    id <WCFinderEventPageViewModelDelegate> _delegate;
    NSString *_topicTitle;
    unsigned long long _state;
    UIViewController<WCFinderFeedBaseViewControllerProtocol> *_currentViewController;
    long long _tabType;
    long long _innerTabType;
    unsigned long long _eventTopicId;
    NSString *_encryptedTopicId;
    NSString *_latestRequestID;
    WCFinderTopicInfo *_topicInfo;
    FinderTopicBgmInfo *_bgmInfo;
    NSData *_lastBuffer;
    NSMutableArray *_contentVMArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *contentVMArray; // @synthesize contentVMArray=_contentVMArray;
@property(nonatomic) _Bool continueFlag; // @synthesize continueFlag=_continueFlag;
@property(retain, nonatomic) NSData *lastBuffer; // @synthesize lastBuffer=_lastBuffer;
@property(retain, nonatomic) FinderTopicBgmInfo *bgmInfo; // @synthesize bgmInfo=_bgmInfo;
@property(retain, nonatomic) WCFinderTopicInfo *topicInfo; // @synthesize topicInfo=_topicInfo;
@property(copy, nonatomic) NSString *latestRequestID; // @synthesize latestRequestID=_latestRequestID;
@property(copy, nonatomic) NSString *encryptedTopicId; // @synthesize encryptedTopicId=_encryptedTopicId;
@property(nonatomic) unsigned long long eventTopicId; // @synthesize eventTopicId=_eventTopicId;
@property(nonatomic) long long innerTabType; // @synthesize innerTabType=_innerTabType;
@property(nonatomic) long long tabType; // @synthesize tabType=_tabType;
@property(retain, nonatomic) UIViewController<WCFinderFeedBaseViewControllerProtocol> *currentViewController; // @synthesize currentViewController=_currentViewController;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(copy, nonatomic) NSString *topicTitle; // @synthesize topicTitle=_topicTitle;
@property(nonatomic) __weak id <WCFinderEventPageViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void)updateState;
- (void)requestDataWithPullType:(unsigned long long)arg1;
- (id)generateTopicListDetailViewModel;
- (void)requestNextPageData;
- (void)requestFirstPageData;
- (id)initWithTopicParams:(id)arg1 innerTabType:(long long)arg2 fromViewController:(id)arg3;

@end

