//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCFinderBaseCgi.h"

@class FinderClientStatus, NSData, NSMutableArray, NSString, WCFinderStreamLocationInfo;

@interface WCFinderStreamCGI : WCFinderBaseCgi
{
    _Bool _isCancel;
    _Bool _prefetchConsumedFlag;
    CDUnknownBlockType _successful;
    CDUnknownBlockType _failure;
    NSData *_buffer;
    unsigned long long _pullType;
    WCFinderStreamLocationInfo *_locationInfo;
    FinderClientStatus *_status;
    long long _tabType;
    unsigned long long _objectID;
    NSString *_nonceID;
    NSMutableArray *_stats;
    unsigned long long _partialExposedObjectId;
    NSMutableArray *_unreadItems;
    NSString *_tabTipsUsername;
    CDUnknownBlockType _cancelBlock;
    unsigned long long _commentscene;
    long long _specialRequestScene;
    NSData *_tabTipsByPassInfo;
    NSString *_tabTipsPath;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *tabTipsPath; // @synthesize tabTipsPath=_tabTipsPath;
@property(retain, nonatomic) NSData *tabTipsByPassInfo; // @synthesize tabTipsByPassInfo=_tabTipsByPassInfo;
@property(nonatomic) _Bool prefetchConsumedFlag; // @synthesize prefetchConsumedFlag=_prefetchConsumedFlag;
@property(nonatomic) long long specialRequestScene; // @synthesize specialRequestScene=_specialRequestScene;
@property(nonatomic) unsigned long long commentscene; // @synthesize commentscene=_commentscene;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(retain, nonatomic) NSString *tabTipsUsername; // @synthesize tabTipsUsername=_tabTipsUsername;
@property(nonatomic) _Bool isCancel; // @synthesize isCancel=_isCancel;
@property(retain, nonatomic) NSMutableArray *unreadItems; // @synthesize unreadItems=_unreadItems;
@property(nonatomic) unsigned long long partialExposedObjectId; // @synthesize partialExposedObjectId=_partialExposedObjectId;
@property(retain, nonatomic) NSMutableArray *stats; // @synthesize stats=_stats;
@property(retain, nonatomic) NSString *nonceID; // @synthesize nonceID=_nonceID;
@property(nonatomic) unsigned long long objectID; // @synthesize objectID=_objectID;
@property(nonatomic) long long tabType; // @synthesize tabType=_tabType;
@property(retain, nonatomic) FinderClientStatus *status; // @synthesize status=_status;
@property(retain, nonatomic) WCFinderStreamLocationInfo *locationInfo; // @synthesize locationInfo=_locationInfo;
@property(nonatomic) unsigned long long pullType; // @synthesize pullType=_pullType;
@property(retain, nonatomic) NSData *buffer; // @synthesize buffer=_buffer;
@property(copy, nonatomic) CDUnknownBlockType failure; // @synthesize failure=_failure;
@property(copy, nonatomic) CDUnknownBlockType successful; // @synthesize successful=_successful;
- (void)cancelCGIWithBlock:(CDUnknownBlockType)arg1;
- (void)cancelCGI;
- (void)finderCgiDidFailWithError:(id)arg1 response:(id)arg2;
- (void)didGetResponse:(id)arg1;
- (void)createRequest;
- (id)initWithBuffer:(id)arg1 clientStatus:(id)arg2 pullType:(unsigned long long)arg3 location:(id)arg4 tabType:(long long)arg5 objectID:(unsigned long long)arg6 nonceID:(id)arg7 stats:(id)arg8 partialExposedObjectId:(unsigned long long)arg9 unreadItems:(id)arg10 commentscene:(unsigned long long)arg11 specialRequestScene:(long long)arg12 tabTipsUsername:(id)arg13 prefetchConsumedFlag:(_Bool)arg14 tabTipsByPassInfo:(id)arg15 tabTipsPath:(id)arg16 successBlock:(CDUnknownBlockType)arg17 failureBlock:(CDUnknownBlockType)arg18;

@end

