//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CommonMessageCellView.h"

@class MMWebImageView, UIImageView, UILabel, UIView, WCFinderShareLiveConnectInviteCellViewModel;

@interface WCFinderShareLiveConnectInviteCellView : CommonMessageCellView
{
    UILabel *_titleLabel;
    UILabel *_descLabel;
    MMWebImageView *_coverImageView;
    UIView *_separatorLine;
    UIImageView *_iconImageView;
    UILabel *_finderLabel;
    struct CGSize _viewSize;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGSize viewSize; // @synthesize viewSize=_viewSize;
@property(retain, nonatomic) UILabel *finderLabel; // @synthesize finderLabel=_finderLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UIView *separatorLine; // @synthesize separatorLine=_separatorLine;
@property(retain, nonatomic) MMWebImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)onTouchUpInside;
- (void)onTouchDown;
- (struct CGSize)contentViewSize;
- (void)initSubviews;
- (void)layoutContentView;
- (_Bool)canBeReused;

// Remaining properties
@property(retain, nonatomic) WCFinderShareLiveConnectInviteCellViewModel *viewModel; // @dynamic viewModel;

@end

