//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, WCFinderSnsShareInfo;

@interface WCFinderFeedContentTempModel : NSObject
{
    _Bool _hasShowNoticeInfo;
    unsigned long long _friendWatchLivingCount;
    WCFinderSnsShareInfo *_snsShareInfo;
    NSString *_recommendReason;
    unsigned long long _liveOnlineCount;
    unsigned long long _stickyTopTime;
    NSString *_verifyInfo;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *verifyInfo; // @synthesize verifyInfo=_verifyInfo;
@property(nonatomic) unsigned long long stickyTopTime; // @synthesize stickyTopTime=_stickyTopTime;
@property(nonatomic) _Bool hasShowNoticeInfo; // @synthesize hasShowNoticeInfo=_hasShowNoticeInfo;
@property(nonatomic) unsigned long long liveOnlineCount; // @synthesize liveOnlineCount=_liveOnlineCount;
@property(retain, nonatomic) NSString *recommendReason; // @synthesize recommendReason=_recommendReason;
@property(retain, nonatomic) WCFinderSnsShareInfo *snsShareInfo; // @synthesize snsShareInfo=_snsShareInfo;
@property(nonatomic) unsigned long long friendWatchLivingCount; // @synthesize friendWatchLivingCount=_friendWatchLivingCount;

@end

