//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSArray, NSData, NSMutableDictionary, NSString;

@interface WCFinderRedDotCtrlInfo : NSObject <PBCoding>
{
    unsigned int expireTime;
    NSString *tipsID;
    unsigned long long priority;
    unsigned long long type;
    NSData *extInfo;
    long long updateTimeSecond;
    NSArray *showInfos;
    NSMutableDictionary *dicShowInfo;
    NSMutableDictionary *dicShowRelation;
    unsigned long long localReceiveMsTimeStamp;
    long long beginShowTime;
}

+ (id)ctrlInfo:(id)arg1;
+ (void)initialize;
+ (void)PBArrayAdd_beginShowTime;
+ (void)PBArrayAdd_localReceiveMsTimeStamp;
+ (void)PBArrayAdd_expireTime;
+ (void)PBArrayAdd_dicShowRelation;
+ (void)PBArrayAdd_dicShowInfo;
+ (void)PBArrayAdd_showInfos;
+ (void)PBArrayAdd_updateTimeSecond;
+ (void)PBArrayAdd_extInfo;
+ (void)PBArrayAdd_type;
+ (void)PBArrayAdd_priority;
+ (void)PBArrayAdd_tipsID;
- (void).cxx_destruct;
@property(nonatomic) long long beginShowTime; // @synthesize beginShowTime;
@property(nonatomic) unsigned long long localReceiveMsTimeStamp; // @synthesize localReceiveMsTimeStamp;
@property(nonatomic) unsigned int expireTime; // @synthesize expireTime;
@property(retain, nonatomic) NSMutableDictionary *dicShowRelation; // @synthesize dicShowRelation;
@property(retain, nonatomic) NSMutableDictionary *dicShowInfo; // @synthesize dicShowInfo;
@property(retain, nonatomic) NSArray *showInfos; // @synthesize showInfos;
@property(nonatomic) long long updateTimeSecond; // @synthesize updateTimeSecond;
@property(retain, nonatomic) NSData *extInfo; // @synthesize extInfo;
@property(nonatomic) unsigned long long type; // @synthesize type;
@property(nonatomic) unsigned long long priority; // @synthesize priority;
@property(retain, nonatomic) NSString *tipsID; // @synthesize tipsID;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
- (_Bool)isExpireCtrlInfo;
- (id)generateFinderCtrlInfo;
- (_Bool)isPriorityHigherThan:(id)arg1;
- (_Bool)isPriorityHigherOrSameThan:(id)arg1;
- (id)finderExtInfo;
- (void)removeDependentReleation:(id)arg1 childPath:(id)arg2;
- (id)removePathInfoWithKey:(id)arg1;
- (_Bool)isShowInfoEmpty;
- (id)showInfoAtPath:(id)arg1;
- (_Bool)isVaildItem;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

