//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UILabel, UIView;

@interface WCFinderMoreContentColumnsTableViewItemCell : UICollectionViewCell
{
    UILabel *_label;
    UIView *_middleLineView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIView *middleLineView; // @synthesize middleLineView=_middleLineView;
@property(nonatomic) __weak UILabel *label; // @synthesize label=_label;
- (void)setupLabelText:(id)arg1 displayLineView:(_Bool)arg2;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

