//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCFinderModUserInfoExt-Protocol.h"

@class NSData, NSMutableArray, NSString;

@interface WCFinderMentionedListViewModel : NSObject <WCFinderModUserInfoExt>
{
    _Bool _isAuthorPerspective;
    _Bool _fromAuthorPerspective;
    _Bool _noMoreData;
    _Bool _showMentionedTab;
    _Bool _fetchingData;
    _Bool _displayBySetting;
    NSString *_username;
    NSMutableArray *_dataItems;
    unsigned long long _refreshTime;
    NSString *_selfUserName;
    NSData *_lastBuffer;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool displayBySetting; // @synthesize displayBySetting=_displayBySetting;
@property(retain, nonatomic) NSData *lastBuffer; // @synthesize lastBuffer=_lastBuffer;
@property(nonatomic) _Bool fetchingData; // @synthesize fetchingData=_fetchingData;
@property(copy, nonatomic) NSString *selfUserName; // @synthesize selfUserName=_selfUserName;
@property(nonatomic) unsigned long long refreshTime; // @synthesize refreshTime=_refreshTime;
@property(nonatomic) _Bool showMentionedTab; // @synthesize showMentionedTab=_showMentionedTab;
@property(nonatomic) _Bool noMoreData; // @synthesize noMoreData=_noMoreData;
@property(retain, nonatomic) NSMutableArray *dataItems; // @synthesize dataItems=_dataItems;
@property(nonatomic) _Bool fromAuthorPerspective; // @synthesize fromAuthorPerspective=_fromAuthorPerspective;
@property(nonatomic) _Bool isAuthorPerspective; // @synthesize isAuthorPerspective=_isAuthorPerspective;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
- (void)updateShowMentioned;
- (_Bool)fetchIsHiddenMentioned;
- (void)onUserInfoChange;
- (void)preloadVideoItems:(id)arg1;
- (void)stopPreloadVideoItem:(id)arg1;
- (id)contentWithTid:(id)arg1;
- (unsigned long long)contentIndexOfTid:(id)arg1;
- (void)_doRemovedItemsFromVM:(id)arg1;
- (void)_finishedRemoveItems:(id)arg1 success:(_Bool)arg2 errorDesc:(id)arg3;
- (void)deleteItem:(id)arg1;
- (void)_finishFetchData:(id)arg1 lastBuffer:(id)arg2 setNomoreData:(_Bool)arg3 failed:(_Bool)arg4;
- (void)requestNextPage;
- (void)requestFirstPage;
@property(readonly, nonatomic) _Bool isDataEmpty;
- (void)dealloc;
- (void)updateWithContact:(id)arg1;
- (id)initWithContact:(id)arg1 userName:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

