//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FinderLiveLbsInfo, NSArray;
@protocol WCFinderNearbyTabPageViewModelDelegate;

@interface WCFinderNearbyTabPageViewModel : NSObject
{
    FinderLiveLbsInfo *_nearbyVideoTabInfo;
    id <WCFinderNearbyTabPageViewModelDelegate> _delegate;
    NSArray *_liveTabList;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *liveTabList; // @synthesize liveTabList=_liveTabList;
@property(nonatomic) __weak id <WCFinderNearbyTabPageViewModelDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) FinderLiveLbsInfo *nearbyVideoTabInfo; // @synthesize nearbyVideoTabInfo=_nearbyVideoTabInfo;
- (void)requestLiveTabList;

@end

