//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCFinderContactExt-Protocol.h"

@class NSData, NSMutableArray, NSString;
@protocol WCFinderSearchViewModelDelegate;

@interface WCFinderSearchViewModel : NSObject <WCFinderContactExt>
{
    _Bool _queryContinueFlag;
    id <WCFinderSearchViewModelDelegate> _delegate;
    unsigned long long _refreshTime;
    NSString *_searchSessionid;
    NSString *_latestQueryText;
    NSString *_latestRequestID;
    NSMutableArray *_allSearchInfoItems;
    NSMutableArray *_allSearchDataItems;
    NSData *_lastBuffer;
    NSString *_exposeItemInfo;
    NSString *_allExposeItemInfo;
    long long _lastReportExposeTimeInMs;
    unsigned long long _searchSourceType;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long searchSourceType; // @synthesize searchSourceType=_searchSourceType;
@property(nonatomic) long long lastReportExposeTimeInMs; // @synthesize lastReportExposeTimeInMs=_lastReportExposeTimeInMs;
@property(retain, nonatomic) NSString *allExposeItemInfo; // @synthesize allExposeItemInfo=_allExposeItemInfo;
@property(retain, nonatomic) NSString *exposeItemInfo; // @synthesize exposeItemInfo=_exposeItemInfo;
@property(retain, nonatomic) NSData *lastBuffer; // @synthesize lastBuffer=_lastBuffer;
@property(retain, nonatomic) NSMutableArray *allSearchDataItems; // @synthesize allSearchDataItems=_allSearchDataItems;
@property(retain, nonatomic) NSMutableArray *allSearchInfoItems; // @synthesize allSearchInfoItems=_allSearchInfoItems;
@property(nonatomic) _Bool queryContinueFlag; // @synthesize queryContinueFlag=_queryContinueFlag;
@property(retain, nonatomic) NSString *latestRequestID; // @synthesize latestRequestID=_latestRequestID;
@property(retain, nonatomic) NSString *latestQueryText; // @synthesize latestQueryText=_latestQueryText;
@property(copy, nonatomic) NSString *searchSessionid; // @synthesize searchSessionid=_searchSessionid;
@property(nonatomic) unsigned long long refreshTime; // @synthesize refreshTime=_refreshTime;
@property(nonatomic) __weak id <WCFinderSearchViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onFinderContactFollowStatusUpdate:(id)arg1;
- (_Bool)deleteSearchRecord:(id)arg1;
- (_Bool)deleteAllSearchRecord;
- (void)reportItemExposeInfo;
- (void)recordResultDisplay:(id)arg1;
- (void)reportSearchActionInfo:(id)arg1 isClickActionType:(_Bool)arg2;
- (id)searchDataItemAtIndexPath:(id)arg1;
- (id)searchInfoAtIndexPath:(id)arg1;
- (_Bool)isSearchFeedItemEmpty;
- (_Bool)isSearchDataItemSection:(unsigned long long)arg1;
- (_Bool)isSearchInfoSection:(unsigned long long)arg1;
- (_Bool)isSearchInfoCountGreaterThanMax;
- (unsigned long long)searchRowNumsWithSection:(unsigned long long)arg1;
- (unsigned long long)searchNumsOfSection;
- (long long)dataItemSection;
- (void)resetSearchStatus;
- (id)generateSearchListViewModelWithHotWord:(id)arg1;
- (id)generateSearchlistViewModel;
- (id)generateSearchContactViewModel;
- (_Bool)isNoMoreData;
- (id)latestQueryString;
- (void)appendInfos:(id)arg1;
- (void)appendDataItems:(id)arg1;
- (void)onQueryNextPageDataItem;
- (void)queryContactWith:(id)arg1 sessionBuf:(id)arg2 scene:(unsigned long long)arg3;
- (void)queryContactWith:(id)arg1;
- (void)updateSearchSourceType:(unsigned long long)arg1;
- (_Bool)isRepetSearch:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

