//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;
@protocol WCFinderNearbyMoreLiveViewModelDelegate;

@interface WCFinderNearbyMoreLiveViewModel : NSObject
{
    _Bool _hasRefreshLiveTabList;
    id <WCFinderNearbyMoreLiveViewModelDelegate> _delegate;
    NSArray *_liveTabList;
    unsigned long long _fromScene;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long fromScene; // @synthesize fromScene=_fromScene;
@property(nonatomic) _Bool hasRefreshLiveTabList; // @synthesize hasRefreshLiveTabList=_hasRefreshLiveTabList;
@property(retain, nonatomic) NSArray *liveTabList; // @synthesize liveTabList=_liveTabList;
@property(nonatomic) __weak id <WCFinderNearbyMoreLiveViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)isEqualWith:(id)arg1;
- (void)requestLiveTabList;
- (id)initWithLiveTabList:(id)arg1 fromScene:(unsigned long long)arg2;

@end

