//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, WCFinderProfileBrandInfo, WCFinderProfileRedPacketEventView, WCFinderStreamProfileExtInfo;

@protocol WCFinderStreamHeaderActionProtocol <NSObject>

@optional
- (void)onTapRedPacketEvent;
- (void)onRedPacketEventViewClickClose:(WCFinderProfileRedPacketEventView *)arg1;
- (void)onClickViewMorePOIAction:(WCFinderStreamProfileExtInfo *)arg1;
- (void)onClickNavigatePOIAction:(WCFinderStreamProfileExtInfo *)arg1;
- (void)onClickBrandInfo:(WCFinderProfileBrandInfo *)arg1;
- (void)onClickShowWXProfileSwitch:(_Bool)arg1;
- (void)onClickGoToWxProfileView;
- (void)onClickShowNameCheckBox:(_Bool)arg1;
- (void)onClickSignatureAtText:(NSString *)arg1;
- (void)onGuideToSignature;
- (void)onClickLiveNoticeView;
- (void)onClickPrivateMsgBtn;
- (void)onOpenAuthInfoDetail;
- (void)onViewGuarantorProfile;
- (void)onChangeFollowStatus:(unsigned long long)arg1;
- (void)onViewFollowingList;
- (void)onViewFansList;
- (void)onViewMore;
- (void)onViewNotify;
- (void)onChangeBrandImage;
- (void)onViewHDAvatarImage:(struct CGRect)arg1;
@end

