//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WCFinderFeedBaseViewControllerProtocol-Protocol.h"
#import "WCFinderNotifySystemViewModelDelegate-Protocol.h"
#import "WCFinderRefreshTableFooterViewDelegate-Protocol.h"

@class NSMutableSet, NSString, UIButton, UILabel, UITableView, WCFinderAnimationLoadingView, WCFinderNotifySystemViewModel, WCFinderRefreshTableFooterView;

@interface WCFinderNotifySystemMSGViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource, WCFinderRefreshTableFooterViewDelegate, WCFinderNotifySystemViewModelDelegate, WCFinderFeedBaseViewControllerProtocol>
{
    UITableView *_tableView;
    UILabel *_emptyLabel;
    WCFinderAnimationLoadingView *_loadingView;
    UIButton *_retryView;
    WCFinderRefreshTableFooterView *_refreshView;
    WCFinderNotifySystemViewModel *_viewModel;
    NSMutableSet *_exposeSet;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableSet *exposeSet; // @synthesize exposeSet=_exposeSet;
@property(retain, nonatomic) WCFinderNotifySystemViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) WCFinderRefreshTableFooterView *refreshView; // @synthesize refreshView=_refreshView;
@property(retain, nonatomic) UIButton *retryView; // @synthesize retryView=_retryView;
@property(retain, nonatomic) WCFinderAnimationLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UILabel *emptyLabel; // @synthesize emptyLabel=_emptyLabel;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (unsigned long long)feedViewerScene;
- (unsigned long long)feedViewControllerScene;
- (_Bool)isEnableTriggerRefreshAtScroll:(id)arg1;
- (void)finderFooterDidTriggerRefresh:(id)arg1;
- (void)didClickFooterRefreshRetry:(id)arg1;
- (void)notifySystemNeedReloadWithIsLoadMore:(_Bool)arg1;
- (void)notifySystemLoadMoreDataSuccessful;
- (void)notifySystemLoadMoreDataFail;
- (void)notifySystemLoadNoMoreData;
- (id)getCellModelWithIndexPath:(id)arg1;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)showDataItemWasPrivateSetTips;
- (void)showDataItemWasDeletedTips;
- (void)showMentionDetailViewController:(id)arg1 navigationTitle:(id)arg2 shouldShowLikeList:(_Bool)arg3;
- (void)showDataItemDetailVCActionWithViewModel:(id)arg1 shouldShowLikeList:(_Bool)arg2;
- (void)showNotifyLinkActionWithViewModel:(id)arg1;
- (void)fetchNewestMention;
- (void)retryFetchNewestMention;
- (id)createLoadingView;
- (id)createTopRetryView;
- (id)createTopLoadingView;
- (id)createRetryView;
- (void)configureTableView;
- (void)viewDidPop:(_Bool)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

