//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCFinderDiscoveryNearbyLiveCollectionViewCellDelegate-Protocol.h"
#import "WCFinderFeedFlowViewDataSource-Protocol.h"
#import "WCFinderFeedFlowViewDelegate-Protocol.h"
#import "WCFinderFeedFlowViewMonitorDelegate-Protocol.h"
#import "WCFinderNearbyMoreLivePageViewModelDelegate-Protocol.h"

@class FinderLiveTabInfo, MMUIViewController, NSMutableDictionary, NSString, WCFinderFeedFlowView, WCFinderNearbyMoreLivePageViewModel;
@protocol WCFinderFeedBaseViewControllerProtocol, WCFinderNearbyMoreLivePageViewManagerDelegate;

@interface WCFinderNearbyMoreLivePageViewManager : NSObject <WCFinderFeedFlowViewDataSource, WCFinderFeedFlowViewDelegate, WCFinderFeedFlowViewMonitorDelegate, WCFinderNearbyMoreLivePageViewModelDelegate, WCFinderDiscoveryNearbyLiveCollectionViewCellDelegate>
{
    _Bool _isFirstPageRequestFinished;
    id <WCFinderNearbyMoreLivePageViewManagerDelegate> _delegate;
    WCFinderFeedFlowView *_feedFlowView;
    FinderLiveTabInfo *_tabInfo;
    MMUIViewController<WCFinderFeedBaseViewControllerProtocol> *_currentViewController;
    WCFinderNearbyMoreLivePageViewModel *_viewModel;
    NSMutableDictionary *_exposeTimeDict;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *exposeTimeDict; // @synthesize exposeTimeDict=_exposeTimeDict;
@property(nonatomic) _Bool isFirstPageRequestFinished; // @synthesize isFirstPageRequestFinished=_isFirstPageRequestFinished;
@property(retain, nonatomic) WCFinderNearbyMoreLivePageViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak MMUIViewController<WCFinderFeedBaseViewControllerProtocol> *currentViewController; // @synthesize currentViewController=_currentViewController;
@property(retain, nonatomic) FinderLiveTabInfo *tabInfo; // @synthesize tabInfo=_tabInfo;
@property(retain, nonatomic) WCFinderFeedFlowView *feedFlowView; // @synthesize feedFlowView=_feedFlowView;
@property(nonatomic) __weak id <WCFinderNearbyMoreLivePageViewManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onItemsExposed:(id)arg1 withOldItems:(id)arg2;
- (void)onClickCoverContact:(id)arg1 dataItem:(id)arg2;
- (void)finderFeedFlowView:(id)arg1 didClickLinkWithUrl:(id)arg2;
- (id)finderFeedFlowView:(id)arg1 tipsType:(unsigned long long)arg2 inState:(unsigned long long)arg3;
- (void)finderFeedFlowView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)finderFeedFlowView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)finderFeedFlowView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (unsigned long long)finderFeedFlowViewState:(id)arg1;
- (void)finderFeedFlowView:(id)arg1 requestDataWithType:(unsigned long long)arg2;
- (_Bool)finderFeedFlowViewCanPrefetchData:(id)arg1;
- (id)finderFeedFlowViewCurrentViewController:(id)arg1;
- (double)finderFeedFlowView:(id)arg1 heightForCustomSupplementaryViewOfKind:(id)arg2 atSection:(long long)arg3;
- (id)finderFeedFlowView:(id)arg1 customSupplementaryViewOfKind:(id)arg2 atIndexPath:(id)arg3;
- (_Bool)finderFeedFlowView:(id)arg1 isCustomSupplementaryViewOfKind:(id)arg2 atSection:(long long)arg3;
- (id)finderFeedFlowView:(id)arg1 cellConfigAtIndexPath:(id)arg2;
- (double)finderFeedFlowView:(id)arg1 heightForCustomCellAtIndexPath:(id)arg2 itemWidth:(double)arg3;
- (id)finderFeedFlowView:(id)arg1 customCellAtIndexPath:(id)arg2;
- (_Bool)finderFeedFlowView:(id)arg1 isCustomCellAtIndexPath:(id)arg2;
- (id)finderFeedFlowView:(id)arg1 contentVMAtIndexPath:(id)arg2;
- (long long)finderFeedFlowView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInFinderFeedFlowView:(id)arg1;
- (void)nearbyLiveAnchorsFetchFailWithErrorCode:(int)arg1;
- (void)nearbyLiveAnchorsNoMoreData;
- (void)nearbyLiveAnchorsAppendDataFrom:(long long)arg1 toIndex:(long long)arg2;
- (void)nearbyLiveAnchorsReloadAllData;
- (void)exposeMarkRead:(id)arg1 duration:(unsigned long long)arg2;
- (void)exposeItemViewDisappear;
- (void)exposeItemViewAppear;
- (void)viewWillDisappear;
- (void)viewWillAppear;
- (id)initWithLiveTabInfo:(id)arg1 view:(id)arg2 InViewController:(id)arg3 fromScene:(unsigned long long)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

