//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSString, UIPercentDrivenInteractiveTransition, WCFinderPlayBar, WCMegaVideoMedia, WCPlayerView;

@interface WCFinderVideoFullScreenViewController : MMUIViewController <UIViewControllerTransitioningDelegate>
{
    WCMegaVideoMedia *_videoSource;
    WCPlayerView *_playerView;
    WCFinderPlayBar *_playBar;
    UIPercentDrivenInteractiveTransition *_animator;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIPercentDrivenInteractiveTransition *animator; // @synthesize animator=_animator;
@property(retain, nonatomic) WCFinderPlayBar *playBar; // @synthesize playBar=_playBar;
@property(retain, nonatomic) WCPlayerView *playerView; // @synthesize playerView=_playerView;
@property(retain, nonatomic) WCMegaVideoMedia *videoSource; // @synthesize videoSource=_videoSource;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (void)dragPanGesture:(id)arg1;
- (void)tapToExit:(id)arg1;
- (void)setUpBottomView;
- (void)setupClose;
- (void)setupUI;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

