//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MainTableDelegate-Protocol.h"
#import "MultiSelectContactsViewControllerDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WCFinderAuthorityListViewModelDelegate-Protocol.h"
#import "WCFinderRefreshTableFooterViewDelegate-Protocol.h"
#import "WCFinderShieldOtherLiedSearchFeedViewControllerDelegate-Protocol.h"

@class MMUISearchBar, NSString, UIImageView, UILabel, UITableView, UIView, WCFinderAuthoritySearchListViewController, WCFinderRefreshTableFooterView;
@protocol WCFinderAuthorityListViewModelProtocol;

@interface WCFinderAuthorityManagerListViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, WCFinderRefreshTableFooterViewDelegate, WCFinderAuthorityListViewModelDelegate, MultiSelectContactsViewControllerDelegate, WCFinderShieldOtherLiedSearchFeedViewControllerDelegate, MainTableDelegate>
{
    _Bool _autoHideSearchBar;
    UITableView *_tableView;
    id <WCFinderAuthorityListViewModelProtocol> _viewModel;
    WCFinderRefreshTableFooterView *_footerView;
    UILabel *_tipsView;
    UIImageView *_reloadIconView;
    MMUISearchBar *_searchBar;
    UIView *_searchContainer;
    WCFinderAuthoritySearchListViewController *_searchVC;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool autoHideSearchBar; // @synthesize autoHideSearchBar=_autoHideSearchBar;
@property(retain, nonatomic) WCFinderAuthoritySearchListViewController *searchVC; // @synthesize searchVC=_searchVC;
@property(retain, nonatomic) UIView *searchContainer; // @synthesize searchContainer=_searchContainer;
@property(retain, nonatomic) MMUISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) UIImageView *reloadIconView; // @synthesize reloadIconView=_reloadIconView;
@property(retain, nonatomic) UILabel *tipsView; // @synthesize tipsView=_tipsView;
@property(retain, nonatomic) WCFinderRefreshTableFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) id <WCFinderAuthorityListViewModelProtocol> viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
- (double)getContentViewY;
- (double)getMainTableBottomInset;
- (double)getMainTableHeight;
- (double)changeSearchStatusAdjustHeight;
- (void)unembedChildViewController:(id)arg1;
- (void)embedSubviewFromChildViewController:(id)arg1;
- (void)WCFinderShieldOtherLiedSearchFeedViewControllerExit:(id)arg1;
- (void)viewModelBatchConfigFinish:(id)arg1 hasFailed:(_Bool)arg2;
- (_Bool)isViewModelHasData;
- (void)resetEmptyStatusTips;
- (void)viewModelRemoveItemAtIndexPath:(id)arg1;
- (void)viewModelRemovedItemFailed:(id)arg1 errorInfo:(id)arg2;
- (void)viewModelLoadFailed:(id)arg1;
- (void)viewModelDataDidChanged:(id)arg1;
- (void)viewModelHasNoMoreData:(id)arg1;
- (_Bool)isEnableTriggerRefreshAtScroll:(id)arg1;
- (void)finderFooterDidTriggerRefresh:(id)arg1;
- (void)didClickFooterRefreshRetry:(id)arg1;
- (void)onMultiSelectContactReturn:(id)arg1;
- (void)onMultiSelectContactCancelForSns;
- (void)clickRightAddButton;
- (void)onClickSearch;
- (void)updateSearchContainerPosition;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (double)contactCellHeight;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)showSearchBar;
- (double)fixDisplayOffsetY;
- (void)adjustContentSizeAndOffset;
- (void)adjustSearchBarAndInset;
- (void)setupDisplaySearchBar;
- (void)initSearchBar;
- (void)layoutTipsTextIconViews;
- (void)configDisplayRetryView:(_Bool)arg1;
- (void)configDisplayTipsView:(id)arg1;
- (void)configureRightButton;
- (void)configureTableView;
- (_Bool)showNavigationBarSepLine;
@property(readonly, nonatomic) double contentOffsetY;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

