//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

@class UITextField;

@interface WCFinderDebugMentionViewController : MMUIViewController
{
    UITextField *_likeCount;
    UITextField *_commentCount;
    UITextField *_followCount;
    UITextField *_systemCount;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UITextField *systemCount; // @synthesize systemCount=_systemCount;
@property(retain, nonatomic) UITextField *followCount; // @synthesize followCount=_followCount;
@property(retain, nonatomic) UITextField *commentCount; // @synthesize commentCount=_commentCount;
@property(retain, nonatomic) UITextField *likeCount; // @synthesize likeCount=_likeCount;
- (void)sendRequest;
- (void)clickDone;
- (void)viewDidLoad;

@end

