//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel;

@interface WCFinderCommentListDescriptionCell : UITableViewCell
{
    UILabel *_commentDescriptionLabel;
}

+ (double)descriptionCellHeight;
- (void).cxx_destruct;
@property(nonatomic) __weak UILabel *commentDescriptionLabel; // @synthesize commentDescriptionLabel=_commentDescriptionLabel;
- (void)setUpUI;
- (void)updateDescriptionText:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

