//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCActionSheet.h"

@class NSString, UIView;

@interface WCFinderPostEducationActionSheet : WCActionSheet
{
    UIView *_educationView;
    NSString *_titleText;
    NSString *_descText;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *descText; // @synthesize descText=_descText;
@property(retain, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
@property(retain, nonatomic) UIView *educationView; // @synthesize educationView=_educationView;
- (void)clickIKnowButton;
- (id)getEducationView;
- (double)getCustomView:(double)arg1;
- (double)heightOfWholeSheet;
- (id)initWithTitle:(id)arg1 descText:(id)arg2 delegate:(id)arg3;

@end

