//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCSearchReportModel.h"

@class NSString;

@interface WCImageSearchReportModel : WCSearchReportModel
{
    int _cgiRet;
    long long _action;
    long long _source;
    NSString *_picMD5;
    NSString *_cgiAction;
}

+ (id)GenTimeLineImageSearchAction:(long long)arg1 requestId:(id)arg2 source:(long long)arg3 scene:(unsigned int)arg4 snsItem:(id)arg5 chatType:(unsigned long long)arg6 picMD5:(id)arg7;
+ (id)GenChatImageSearchAction:(long long)arg1 requestId:(id)arg2 source:(long long)arg3 scene:(unsigned int)arg4 msgWrap:(id)arg5;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *cgiAction; // @synthesize cgiAction=_cgiAction;
@property(nonatomic) int cgiRet; // @synthesize cgiRet=_cgiRet;
@property(copy, nonatomic) NSString *picMD5; // @synthesize picMD5=_picMD5;
@property(nonatomic) long long source; // @synthesize source=_source;
@property(nonatomic) long long action; // @synthesize action=_action;
- (void)doReport;
- (void)doReport:(long long)arg1;
- (id)reportContent;
- (unsigned int)reportKvId;
- (id)initWithMsgWrap:(id)arg1;

@end

