//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTTableCoding-Protocol.h"

@class NSString;

@interface WCMicroMerchantFeed : NSObject <WCTTableCoding>
{
    unsigned int _groupTime;
    unsigned int _status;
    NSString *_feedId;
    NSString *_groupId;
    NSString *_username;
    NSString *_title;
}

+ (void)__wcdb_column_constraint_85:(struct WCTBinding *)arg1;
+ (void)__wcdb_index_84:(struct WCTBinding *)arg1;
+ (void)__wcdb_column_constraint_83:(struct WCTBinding *)arg1;
+ (void)__wcdb_column_constraint_82:(struct WCTBinding *)arg1;
+ (void)__wcdb_column_constraint_81:(struct WCTBinding *)arg1;
+ (void)__wcdb_column_constraint_80:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)__wcdb_synthesize_79:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)status;
+ (const struct WCTProperty *)__wcdb_synthesize_78:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)title;
+ (const struct WCTProperty *)__wcdb_synthesize_77:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)username;
+ (const struct WCTProperty *)__wcdb_synthesize_76:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)groupTime;
+ (const struct WCTProperty *)__wcdb_synthesize_75:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)groupId;
+ (const struct WCTProperty *)__wcdb_synthesize_74:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)feedId;
+ (id)__wcdbtyper;
+ (const SyntaxList_7f15fe8c *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
- (void).cxx_destruct;
@property(nonatomic) unsigned int status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(nonatomic) unsigned int groupTime; // @synthesize groupTime=_groupTime;
@property(retain, nonatomic) NSString *groupId; // @synthesize groupId=_groupId;
@property(retain, nonatomic) NSString *feedId; // @synthesize feedId=_feedId;
- (id)description;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

