//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCContentItemBaseView.h"

#import "WCAdCountdownViewDelegate-Protocol.h"
#import "WCAdFinderLiveNoticeLogicDelegate-Protocol.h"
#import "WCAdQuicklyAddBrandLogicDelegate-Protocol.h"
#import "WCAdSubscriptionLogicDelegate-Protocol.h"
#import "WCImageViewDelegate-Protocol.h"

@class MMUIButton, MMUILabel, MMUIView, MMWebImageView, NSString, UIImageView, WCAdCountdownView, WCAdCouponLogic, WCAdFinderLiveNoticeLogic, WCAdQuicklyAddBrandLogic, WCAdRollTextView, WCAdSubscriptionLogic, WCAdVoteLineView, WCDataItem, WCFinderLiveIconImageView, WCHighLightButton, WCSightView, WCTimeLineTagView;
@protocol WCTimeLineAdCardBaseViewDelegate;

@interface WCTimeLineAdCardBaseView : WCContentItemBaseView <WCAdSubscriptionLogicDelegate, WCAdQuicklyAddBrandLogicDelegate, WCAdFinderLiveNoticeLogicDelegate, WCAdCountdownViewDelegate, WCImageViewDelegate>
{
    unsigned int _liveStatus;
    id <WCTimeLineAdCardBaseViewDelegate> _delegate;
    WCDataItem *_dataItem;
    double _mediaAreaHeight;
    double _mediaAreaWidth;
    MMUIView *_mediaHolder;
    long long _mediaType;
    MMUIButton *_mediaBgButton;
    MMUILabel *_titleView;
    MMUILabel *_descView;
    WCSightView *_sightView;
    MMUIButton *_actionBtn;
    MMWebImageView *_iconView;
    MMUIView *_weAppTipView;
    WCHighLightButton *_leftButton;
    WCHighLightButton *_rightButton;
    WCAdVoteLineView *_voteLineView;
    MMUIView *_topMaskView;
    WCTimeLineTagView *_tagView;
    MMUIView *_labelView;
    WCAdSubscriptionLogic *_subscriptionLogic;
    UIImageView *_weAppTradingGuaranteeIcon;
    WCAdQuicklyAddBrandLogic *_addBrandLogic;
    WCAdCouponLogic *_adCouponLogic;
    WCAdFinderLiveNoticeLogic *_adFinderLiveNoticeLogic;
    MMUIView *_promotionView;
    WCAdCountdownView *_countdownView;
    MMUIView *_liveStatusView;
    WCFinderLiveIconImageView *_liveStatusIcon;
    MMUILabel *_liveStatusText;
    MMUIView *_liveDescView;
    WCAdRollTextView *_liveDescText;
}

+ (id)textColorForContent:(id)arg1;
+ (id)fontForContent:(id)arg1;
+ (id)fontForTitle:(id)arg1;
+ (_Bool)isValidForShowActionBtn:(id)arg1;
+ (id)fetchTrimDesc:(id)arg1;
+ (_Bool)hasTitle:(id)arg1;
+ (_Bool)hasLeftAndRightButton:(id)arg1;
+ (double)heightForContentWithItem:(id)arg1 font:(id)arg2 maxWidth:(double)arg3;
+ (double)heightForTitleWithItem:(id)arg1 font:(id)arg2;
+ (double)heightForOperationArea:(id)arg1 maxWidth:(double)arg2;
+ (double)heightForMediaView:(id)arg1 maxWidth:(double)arg2;
+ (double)heightForMedia:(id)arg1;
+ (double)heightForMedia:(id)arg1 maxWidth:(double)arg2;
- (void).cxx_destruct;
@property(nonatomic) unsigned int liveStatus; // @synthesize liveStatus=_liveStatus;
@property(retain, nonatomic) WCAdRollTextView *liveDescText; // @synthesize liveDescText=_liveDescText;
@property(retain, nonatomic) MMUIView *liveDescView; // @synthesize liveDescView=_liveDescView;
@property(retain, nonatomic) MMUILabel *liveStatusText; // @synthesize liveStatusText=_liveStatusText;
@property(retain, nonatomic) WCFinderLiveIconImageView *liveStatusIcon; // @synthesize liveStatusIcon=_liveStatusIcon;
@property(retain, nonatomic) MMUIView *liveStatusView; // @synthesize liveStatusView=_liveStatusView;
@property(retain, nonatomic) WCAdCountdownView *countdownView; // @synthesize countdownView=_countdownView;
@property(retain, nonatomic) MMUIView *promotionView; // @synthesize promotionView=_promotionView;
@property(retain, nonatomic) WCAdFinderLiveNoticeLogic *adFinderLiveNoticeLogic; // @synthesize adFinderLiveNoticeLogic=_adFinderLiveNoticeLogic;
@property(retain, nonatomic) WCAdCouponLogic *adCouponLogic; // @synthesize adCouponLogic=_adCouponLogic;
@property(retain, nonatomic) WCAdQuicklyAddBrandLogic *addBrandLogic; // @synthesize addBrandLogic=_addBrandLogic;
@property(retain, nonatomic) UIImageView *weAppTradingGuaranteeIcon; // @synthesize weAppTradingGuaranteeIcon=_weAppTradingGuaranteeIcon;
@property(retain, nonatomic) WCAdSubscriptionLogic *subscriptionLogic; // @synthesize subscriptionLogic=_subscriptionLogic;
@property(retain, nonatomic) MMUIView *labelView; // @synthesize labelView=_labelView;
@property(retain, nonatomic) WCTimeLineTagView *tagView; // @synthesize tagView=_tagView;
@property(retain, nonatomic) MMUIView *topMaskView; // @synthesize topMaskView=_topMaskView;
@property(retain, nonatomic) WCAdVoteLineView *voteLineView; // @synthesize voteLineView=_voteLineView;
@property(retain, nonatomic) WCHighLightButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) WCHighLightButton *leftButton; // @synthesize leftButton=_leftButton;
@property(retain, nonatomic) MMUIView *weAppTipView; // @synthesize weAppTipView=_weAppTipView;
@property(retain, nonatomic) MMWebImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) MMUIButton *actionBtn; // @synthesize actionBtn=_actionBtn;
@property(retain, nonatomic) WCSightView *sightView; // @synthesize sightView=_sightView;
@property(retain, nonatomic) MMUILabel *descView; // @synthesize descView=_descView;
@property(retain, nonatomic) MMUILabel *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) MMUIButton *mediaBgButton; // @synthesize mediaBgButton=_mediaBgButton;
@property(nonatomic) long long mediaType; // @synthesize mediaType=_mediaType;
@property(retain, nonatomic) MMUIView *mediaHolder; // @synthesize mediaHolder=_mediaHolder;
@property(nonatomic) double mediaAreaWidth; // @synthesize mediaAreaWidth=_mediaAreaWidth;
@property(nonatomic) double mediaAreaHeight; // @synthesize mediaAreaHeight=_mediaAreaHeight;
@property(retain, nonatomic) WCDataItem *dataItem; // @synthesize dataItem=_dataItem;
@property(nonatomic) __weak id <WCTimeLineAdCardBaseViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onFinderLiveNoticeReserved;
- (id)genSubscriptionLogicInner;
- (_Bool)checkActionButtonType:(long long)arg1;
- (void)saveOperationLogicInCache:(id)arg1 withSnsId:(id)arg2;
- (id)fetchLogicCacheWithSnsId:(id)arg1;
- (void)onDownloadCancel:(id)arg1;
- (void)onDownloadFailed:(id)arg1;
- (void)onDownloadFinish:(id)arg1;
- (void)onCommitBtnClickWithBrandUsername:(id)arg1;
- (void)onQuicklyAddBrandResult:(long long)arg1 andBrandUsername:(id)arg2;
- (void)updateAdTradingGuaranteeVisibility:(id)arg1;
- (void)checkAndUpdateSubscriptionLogicInfo;
- (id)fetchDefaultSubscriptionHeadInfo;
- (id)fetchSubscriptionStateMMKVKeyWithSnsId:(id)arg1;
- (_Bool)hasSendSubscriptionWithSnsId:(id)arg1;
- (void)setSubscriptionStateInMMKV:(id)arg1;
- (void)updateFinderLiveNoticeReserveInfo;
- (void)updateFinderLiveNoticeReserveBtnStateWithLocal;
- (void)doFinderLiveNoticeReserve;
- (void)doGetCoupon;
- (void)doSubscribe;
- (void)doAddBrandOrEnterBrandProfileVC:(_Bool)arg1;
- (void)updateQuicklyAddBrandBtnState;
- (void)updateSubscriptionBtnState;
- (void)setActionButtonStateEnable:(_Bool)arg1 btnColor:(id)arg2 title:(id)arg3;
- (void)doSubscriptionMessageReport:(long long)arg1 clickSubmit:(_Bool)arg2;
- (void)closePageSheetWithoutSubmit;
- (void)onSubscriptionLogic:(id)arg1 finishedWithResult:(id)arg2 success:(_Bool)arg3 cancel:(_Bool)arg4 errorCode:(long long)arg5;
- (void)removeVoteResultArea;
- (void)updateVoteAdUI;
- (void)onWCCommentDetailViewWillAppear;
- (void)onSelectBtnClick:(id)arg1 isLeft:(_Bool)arg2 originView:(id)arg3;
- (id)fetchMediaHolder;
- (void)initWeAppTipView:(id)arg1;
- (void)initRatingCardView:(id)arg1;
- (id)genAdTagList:(id)arg1;
- (void)onActionBtnClick;
- (void)updateActionButtonTitle:(id)arg1;
- (id)createActionButton:(id)arg1;
- (void)updateSubViewsLayout:(id)arg1;
- (void)initActionButtonLogic:(id)arg1;
- (void)initIconView:(id)arg1;
- (_Bool)isValidToShowIconView:(id)arg1;
- (void)initActionButton:(id)arg1;
- (id)createTextViewWithContent:(id)arg1 textColor:(id)arg2 font:(id)arg3 maxWidth:(double)arg4 isSingleLine:(_Bool)arg5;
- (void)initContentView:(id)arg1 maxWidth:(double)arg2;
- (void)initTitleView:(id)arg1 maxWidth:(double)arg2;
- (id)createVoteLabelView;
- (_Bool)hasVoteTitle;
- (void)calcMediaArea:(id)arg1;
- (void)contentItemDidEndDisplaying;
- (void)contentItemWillDisplay;
- (void)autoPauseWithoutSound;
- (void)autoPlayWithoutSound;
- (id)createSightView:(id)arg1;
- (void)initSightViewForAdCard:(id)arg1;
- (void)initImageViewForAdCard:(id)arg1;
- (double)getMaxWidthForTitleView:(id)arg1;
- (void)initContentArea:(id)arg1;
- (void)delayClickAdCardTouchButton;
- (id)getVoiceOverStrForTimeline;
- (void)onVoiceOverClick;
- (void)onClickBgButton:(id)arg1 forEvent:(id)arg2;
- (void)onFavoriteAddAdCard:(id)arg1;
- (void)showFavoriteAddAdCardMenuitem;
- (void)onLongPressBgButton:(id)arg1;
- (void)onRightButtonClick:(id)arg1 forEvent:(id)arg2;
- (void)onLeftButtonClick:(id)arg1 forEvent:(id)arg2;
- (void)checkVoteBtnState;
- (void)initSelectButton:(id)arg1;
- (void)initVoteResultView:(id)arg1;
- (id)getVoteInfo:(id)arg1 isFirstObj:(_Bool)arg2;
- (id)createSelectButton:(id)arg1 fontSize:(double)arg2 fontColor:(id)arg3 isLeft:(_Bool)arg4;
- (void)removeAllButtons;
- (void)initBgButton:(id)arg1;
- (void)dealloc;
- (void)checkUpdateLiveInfo;
- (void)updateLiveStatus:(int)arg1;
- (void)initLiveInfoView:(id)arg1;
- (void)onCountdownEnd;
- (void)onCountdownUpdate;
- (void)initPromotionView:(id)arg1;
- (_Bool)needShowPromotion:(id)arg1;
- (void)initMediaView:(id)arg1;
- (void)initViewsWithWCDataItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

