//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WSTemplateBaseMgr.h"

#import "IExptServiceExt-Protocol.h"

@interface WCTopicService : WSTemplateBaseMgr <IExptServiceExt>
{
    _Bool _isAvaliableForTextFeaturesInChat;
    _Bool _isAvaliableForTextFeaturesInTimeline;
    _Bool _isAvaliableForShareConentSearch;
    unsigned int _topicMaxCharacterCount;
}

@property(nonatomic) unsigned int topicMaxCharacterCount; // @synthesize topicMaxCharacterCount=_topicMaxCharacterCount;
@property(nonatomic) _Bool isAvaliableForShareConentSearch; // @synthesize isAvaliableForShareConentSearch=_isAvaliableForShareConentSearch;
@property(nonatomic) _Bool isAvaliableForTextFeaturesInTimeline; // @synthesize isAvaliableForTextFeaturesInTimeline=_isAvaliableForTextFeaturesInTimeline;
@property(nonatomic) _Bool isAvaliableForTextFeaturesInChat; // @synthesize isAvaliableForTextFeaturesInChat=_isAvaliableForTextFeaturesInChat;
- (void)onExptItemListChange;
- (_Bool)isAvaliableForTopicSearchTextFeaturesInTimeline;
- (_Bool)isAvaliableForTopicSearchInputShare;
- (_Bool)isAvaliableForTopicSearchTextFeatures;
- (void)dealloc;
- (_Bool)updateCacheTextFeatureEnableInTimeline:(_Bool)arg1;
- (_Bool)updateCacheTextFeatureEnableInChat:(_Bool)arg1;
- (unsigned long long)localJSBizType;
- (unsigned int)packageResouceType;
- (id)templateResouceRootPath;
- (id)appDefaultTemplateResoucePath;
- (void)onServiceInit;

@end

