//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WSWebViewPluginBase.h"

@interface WSWebViewPlugin_ParallelRequest : WSWebViewPluginBase
{
    // Error parsing type: , name: parallelHandlerDict
    // Error parsing type: , name: eventResponseDict
}

- (void).cxx_destruct;
- (id)init;
- (id)getWebViewOwner;
- (unsigned long long)getLocalJSBusinessType;
- (void)eventEndWithHandler:(id)arg1 result:(id)arg2;
- (void)sendEvent:(id)arg1 handler:(id)arg2 result:(id)arg3;
- (void)dispatch:(id)arg1 params:(id)arg2;
- (_Bool)tryUseCacheWithRealEventHandler:(id)arg1;

@end

